const translationCard = document.getElementById("translationCard");
// 诗歌文本c
const poemText = `正说处
后面闪过龙婆龙女道
大王
观看此圣
决非小可
我们这海藏中
那一块天河定底的神珍铁
这几日霞光艳艳
瑞气腾腾
敢莫是该出现
遇此圣也
龙王道
那是大禹治水之时
定江海浅深的一个定子
是一块神铁
能中何用
龙婆道
莫管他用不用
且送与他
凭他怎么改造
送出宫门便了
老龙王依言
尽向悟空说了
悟空道
拿出来我看
龙王摇手道
扛不动
抬不动
须上仙亲去看看
悟空道
在何处
你引我去
龙王果引导至海藏中间
忽见金光万道
龙王指定道
那放光的便是
悟空撩衣上前
摸了一把
乃是一根铁柱子
约有斗来粗
二丈有余长
他尽力两手挝过道
忒粗忒长些
再短细些方可用
说毕
那宝贝就短了几尺
细了一围
悟空又颠一颠道
再细些更好
那宝贝真个又细了几分
悟空十分欢喜
拿出海藏看时
原来两头是两个金箍
中间乃一段乌铁
紧挨箍有镌成的一行字
唤做如意金箍棒
重一万三千五百斤
心中暗喜道
想必这宝贝如人意
一边走
一边心思口念
手颠着道
再短细些更妙
拿出外面
只有二丈长短
碗口粗细
你看他弄神通
丢开解数
打转水晶宫里
唬得老龙王胆战心惊
小龙子魂飞魄散
龟鳖鼋鼍皆缩颈
鱼虾鳌蟹尽藏头
悟空将宝贝执在手中
坐在水晶宫殿上
对龙王笑道
多谢贤邻厚意
龙王道
不敢不敢
悟空道
这块铁虽然好用
还有一说
龙王道
上仙还有甚说
悟空道
当时若无此铁
倒也罢了
如今手中既拿着他
身上无衣服相趁
奈何
你这里若有披挂
索性送我一件
一总奉谢
龙王道
这个却是没有
悟空道
一客不犯二主
若没有
我也定不出此门
龙王道
烦上仙再转一海
或者有之
悟空又道
走三家不如坐一家
千万告求一件
龙王道
委的没有
如有即当奉承
悟空道
真个没有
就和你试试此铁
龙王慌了道
上仙
切莫动手
切莫动手
待我看舍弟处可有
当送一副
悟空道
令弟何在
龙王道
舍弟乃南海龙王敖钦
北海龙王敖顺
西海龙王敖闰是也
悟空道
我老孙不去
不去
俗语谓赊三不敌见二
只望你随高就低的送一副便了
老龙道
不须上仙去
我这里有一面铁鼓
一口金钟
凡有紧急事
擂得鼓响
撞得钟鸣
舍弟们就顷刻而至
悟空道
既是如此
快些去擂鼓撞钟
真个那鼍将便去撞钟
鳖帅即来擂鼓
5
少时
钟鼓响处
果然惊动那三海龙王
须臾来到
一齐在外面会着
敖钦道
大哥
有甚紧事
擂鼓撞钟
老龙道
贤弟
不好说
有一个花果山甚么天生圣人
早间来认我做邻居
后来要求一件兵器
献钢叉嫌小
奉画戟嫌轻
将一块天河定底神珍铁
自己拿出手
丢了些解数
如今坐在宫中
又要索甚么披挂
我处无有
故响钟鸣鼓
请贤弟来
你们可有甚么披挂
送他一副
打发出门去罢了
敖钦闻言
大怒道
我兄弟们
点起兵
拿他不是
老龙道
莫说拿
那块铁
挽着些儿就死
磕着些儿就亡
挨挨皮儿破
擦擦儿筋伤
西海龙王敖闰说
二哥不可与他动手
且只凑副披挂与他
打发他出了门
启表奏上上天
天自诛也
北海龙王敖顺道
说的是
我这里有一双藕丝步云履哩
西海龙王敖闰道
我带了一副锁子黄金甲哩
南海龙王敖钦道
我有一顶凤翅紫金冠哩
老龙大喜
引入水晶宫相见了
以此奉上
悟空将金冠
金甲
云履那穿戴停当
使动如意棒
一路打出去
对众龙道
聒噪
吵闹
打搅
聒噪
四海龙王甚是不平
一边商议进表上奏不题`;

const pinyinMap = {
  正: "zhèng",
  说: "shuō",
  处: "chù",
  后: "hòu",
  面: "miàn",
  闪: "shǎn",
  过: "guò",
  龙: "lóng",
  婆: "pó",
  女: "nǚ",
  道: "dào",
  大: "dài",
  王: "wáng",
  观: "guān",
  看: "kàn",
  此: "cǐ",
  圣: "shèng",
  决: "jué",
  非: "fēi",
  小: "xiǎo",
  可: "kě",
  我: "wǒ",
  们: "men",
  这: "zhè",
  海: "hǎi",
  藏: "cáng",
  中: "zhōng",
  那: "nà",
  一: "yī",
  块: "kuài",
  天: "tiān",
  河: "hé",
  定: "dìng",
  底: "dǐ",
  的: "de",
  神: "shén",
  珍: "zhēn",
  铁: "tiě",
  几: "jǐ",
  日: "rì",
  霞: "xiá",
  光: "guāng",
  艳: "yàn",
  瑞: "ruì",
  气: "qì",
  腾: "téng",
  敢: "gǎn",
  莫: "mò",
  是: "shì",
  该: "gāi",
  出: "chū",
  现: "xiàn",
  遇: "yù",
  也: "yě",
  禹: "yǔ",
  治: "zhì",
  水: "shuǐ",
  之: "zhī",
  时: "shí",
  江: "jiāng",
  浅: "qiǎn",
  深: "shēn",
  个: "gè",
  子: "zi",
  能: "néng",
  何: "hé",
  用: "yòng",
  管: "guǎn",
  他: "tā",
  不: "bù",
  且: "qiě",
  送: "sòng",
  与: "yǔ",
  凭: "píng",
  怎: "zěn",
  么: "me",
  改: "gǎi",
  造: "zào",
  宫: "gōng",
  门: "mén",
  便: "biàn",
  了: "liǎo",
  老: "lǎo",
  依: "yī",
  言: "yán",
  尽: "jǐn",
  向: "xiàng",
  悟: "wù",
  空: "kōng",
  拿: "ná",
  来: "lái",
  摇: "yáo",
  手: "shǒu",
  扛: "káng",
  动: "dòng",
  抬: "tái",
  须: "xū",
  上: "shàng",
  仙: "xiān",
  亲: "qīn",
  去: "qù",
  在: "zài",
  你: "nǐ",
  引: "yǐn",
  果: "guǒ",
  导: "dǎo",
  至: "zhì",
  间: "jiān",
  忽: "hū",
  见: "jiàn",
  金: "jīn",
  万: "wàn",
  指: "zhǐ",
  放: "fàng",
  撩: "liāo",
  衣: "yī",
  前: "qián",
  摸: "mō",
  把: "bǎ",
  乃: "nǎi",
  根: "gēn",
  柱: "zhù",
  约: "yuē",
  有: "yǒu",
  斗: "dòu",
  粗: "cū",
  二: "èr",
  丈: "zhàng",
  余: "yú",
  长: "zhǎng",
  力: "lì",
  两: "liǎng",
  挝: "wō",
  忒: "tè",
  些: "xiē",
  再: "zài",
  短: "duǎn",
  细: "xì",
  方: "fāng",
  毕: "bì",
  宝: "bǎo",
  贝: "bèi",
  就: "jiù",
  尺: "chǐ",
  围: "wéi",
  又: "yòu",
  颠: "diān",
  更: "gèng",
  好: "hǎo",
  真: "zhēn",
  分: "fēn",
  十: "shí",
  欢: "huān",
  喜: "xǐ",
  原: "yuán",
  头: "tóu",
  箍: "gū",
  段: "duàn",
  乌: "wū",
  紧: "jǐn",
  挨: "āi",
  镌: "juān",
  成: "chéng",
  行: "háng",
  字: "zì",
  唤: "huàn",
  做: "zuò",
  如: "rú",
  意: "yì",
  棒: "bàng",
  重: "zhòng",
  三: "sān",
  千: "qiān",
  五: "wǔ",
  百: "bǎi",
  斤: "jīn",
  心: "xīn",
  暗: "àn",
  想: "xiǎng",
  必: "bì",
  人: "rén",
  边: "biān",
  走: "zǒu",
  思: "sī",
  口: "kǒu",
  念: "niàn",
  着: "zhe",
  妙: "miào",
  外: "wài",
  只: "zhǐ",
  碗: "wǎn",
  弄: "nòng",
  通: "tōng",
  丢: "diū",
  开: "kāi",
  解: "jiě",
  数: "shù",
  打: "dǎ",
  转: "zhuǎn",
  晶: "jīng",
  里: "lǐ",
  唬: "hǔ",
  得: "dé",
  胆: "dǎn",
  战: "zhàn",
  惊: "jīng",
  魂: "hún",
  飞: "fēi",
  魄: "pò",
  散: "sàn",
  龟: "guī",
  鳖: "biē",
  鼋: "yuán",
  鼍: "tuó",
  皆: "jiē",
  缩: "suō",
  颈: "jǐng",
  鱼: "yú",
  虾: "xiā",
  鳌: "áo",
  蟹: "xiè",
  将: "jiāng",
  执: "zhí",
  坐: "zuò",
  殿: "diàn",
  对: "duì",
  笑: "xiào",
  多: "duō",
  谢: "xiè",
  贤: "xián",
  邻: "lín",
  厚: "hòu",
  虽: "suī",
  然: "rán",
  还: "hái",
  甚: "shèn",
  当: "dāng",
  若: "ruò",
  无: "wú",
  倒: "dào",
  罢: "bà",
  今: "jīn",
  既: "jì",
  身: "shēn",
  服: "fú",
  相: "xiāng",
  趁: "chèn",
  奈: "nài",
  披: "pī",
  挂: "guà",
  索: "suǒ",
  性: "xìng",
  件: "jiàn",
  总: "zǒng",
  奉: "fèng",
  却: "què",
  没: "méi",
  客: "kè",
  犯: "fàn",
  主: "zhǔ",
  烦: "fán",
  或: "huò",
  者: "zhě",
  家: "jiā",
  告: "gào",
  求: "qiú",
  委: "wěi",
  即: "jí",
  承: "chéng",
  和: "hé",
  试: "shì",
  慌: "huāng",
  切: "qiè",
  待: "dài",
  舍: "shě",
  弟: "dì",
  副: "fù",
  令: "lìng",
  南: "nán",
  敖: "áo",
  钦: "qīn",
  北: "běi",
  顺: "shùn",
  西: "xī",
  闰: "rùn",
  孙: "sūn",
  俗: "sú",
  语: "yǔ",
  谓: "wèi",
  赊: "shē",
  敌: "dí",
  望: "wàng",
  随: "suí",
  高: "gāo",
  低: "dī",
  鼓: "gǔ",
  钟: "zhōng",
  凡: "fán",
  急: "jí",
  事: "shì",
  擂: "léi",
  响: "xiǎng",
  撞: "zhuàng",
  鸣: "míng",
  顷: "qǐng",
  刻: "kè",
  而: "ér",
  快: "kuài",
  帅: "shuài",
  5: "5",
  少: "shǎo",
  臾: "yú",
  到: "dào",
  齐: "qí",
  会: "huì",
  哥: "gē",
  花: "huā",
  山: "shān",
  生: "shēng",
  早: "zǎo",
  认: "rèn",
  居: "jū",
  要: "yào",
  兵: "bīng",
  器: "qì",
  献: "xiàn",
  钢: "gāng",
  叉: "chā",
  嫌: "xián",
  画: "huà",
  戟: "jǐ",
  轻: "qīng",
  自: "zì",
  己: "jǐ",
  故: "gù",
  请: "qǐng",
  发: "fā",
  闻: "wén",
  怒: "nù",
  兄: "xiōng",
  点: "diǎn",
  起: "qǐ",
  挽: "wǎn",
  儿: "ér",
  死: "sǐ",
  磕: "kē",
  亡: "wáng",
  皮: "pí",
  破: "pò",
  擦: "cā",
  筋: "jīn",
  伤: "shāng",
  凑: "còu",
  启: "qǐ",
  表: "biǎo",
  奏: "zòu",
  诛: "zhū",
  双: "shuāng",
  藕: "ǒu",
  丝: "sī",
  步: "bù",
  云: "yún",
  履: "lǚ",
  哩: "lī",
  带: "dài",
  锁: "suǒ",
  黄: "huáng",
  甲: "jiǎ",
  顶: "dǐng",
  凤: "fèng",
  翅: "chì",
  紫: "zǐ",
  冠: "guān",
  入: "rù",
  以: "yǐ",
  穿: "chuān",
  戴: "dài",
  停: "tíng",
  使: "shǐ",
  路: "lù",
  众: "zhòng",
  聒: "guā",
  噪: "zào",
  吵: "chǎo",
  闹: "nào",
  搅: "jiǎo",
  四: "sì",
  平: "píng",
  商: "shāng",
  议: "yì",
  进: "jìn",
  题: "tí",
};

const translations_en = {
  正: "just",
  说: "explain",
  处: "Where",
  后: "back",
  面: "noodle",
  闪: "flash",
  过: "Pass",
  龙: "dragon",
  婆: "Mom",
  女: "female",
  道: "road",
  大: "big",
  王: "king",
  观: "View",
  看: "look",
  此: "this",
  圣: "Saint",
  决: "Decision",
  非: "No",
  小: "Small",
  可: "Can",
  我: "I",
  们: "We",
  这: "this",
  海: "ocean",
  藏: "Tibetan",
  中: "middle",
  那: "That",
  一: "one",
  块: "piece",
  天: "sky",
  河: "river",
  定: "Certainly",
  底: "end",
  的: "of",
  神: "god",
  珍: "Jen",
  铁: "iron",
  几: "Several",
  日: "day",
  霞: "Xia",
  光: "Light",
  艳: "Beautiful",
  瑞: "Rui",
  气: "gas",
  腾: "Teng",
  敢: "dare",
  莫: "Mo",
  是: "yes",
  该: "Should",
  出: "out",
  现: "now",
  遇: "Meet",
  也: "also",
  禹: "Yu",
  治: "rule",
  水: "water",
  之: "Of",
  时: "hour",
  江: "River",
  浅: "shallow",
  深: "deep",
  个: "indivual",
  子: "son",
  能: "able",
  何: "what",
  用: "use",
  管: "Tube",
  他: "he",
  不: "No",
  且: "and",
  送: "deliver",
  与: "and",
  凭: "By",
  怎: "How",
  么: "Is it",
  改: "change",
  造: "make",
  宫: "palace",
  门: "Door",
  便: "Hope",
  了: "It's",
  老: "old",
  依: "according to",
  言: "Word",
  尽: "All",
  向: "Towards",
  悟: "Enlightenment",
  空: "null",
  拿: "take",
  来: "Come",
  摇: "shake",
  手: "hand",
  扛: "Carry",
  动: "move",
  抬: "lift",
  须: "Must",
  上: "superior",
  仙: "Fairy",
  亲: "relative",
  去: "go",
  在: "exist",
  你: "you",
  引: "lead",
  果: "fruit",
  导: "guide",
  至: "to",
  间: "between",
  忽: "suddenly",
  见: "See",
  金: "gold",
  万: "Ten thousand",
  指: "refer to",
  放: "put",
  撩: "tease",
  衣: "Clothes",
  前: "forward",
  摸: "touch",
  把: "Bundle",
  乃: "So",
  根: "root",
  柱: "column",
  约: "about",
  有: "have",
  斗: "fight",
  粗: "thick",
  二: "two",
  丈: "ten feet",
  余: "Remain",
  长: "long",
  力: "force",
  两: "two",
  挝: "Os",
  忒: "How",
  些: "some",
  再: "Again",
  短: "short",
  细: "thin",
  方: "square",
  毕: "complete",
  宝: "precious",
  贝: "cowry",
  就: "At once",
  尺: "ruler",
  围: "Surrounding",
  又: "again",
  颠: "Far",
  更: "Even",
  好: "good",
  真: "real",
  分: "point",
  十: "ten",
  欢: "joyous",
  喜: "happiness",
  原: "Original",
  头: "head",
  箍: "hoop",
  段: "part",
  乌: "Wu",
  紧: "tight",
  挨: "suffer",
  镌: "engrave",
  成: "become",
  行: "OK",
  字: "Character",
  唤: "Call",
  做: "Do",
  如: "like",
  意: "meaning",
  棒: "Great",
  重: "Heavy",
  三: "three",
  千: "thousand",
  五: "five",
  百: "Hundred",
  斤: "catty",
  心: "Heart",
  暗: "dark",
  想: "think",
  必: "must",
  人: "people",
  边: "side",
  走: "Walk",
  思: "think",
  口: "mouth",
  念: "read",
  着: "Put",
  妙: "wonderful",
  外: "outside",
  只: "Only",
  碗: "bowl",
  弄: "alley",
  通: "Pass",
  丢: "leave",
  开: "open",
  解: "untie",
  数: "number",
  打: "beat",
  转: "change",
  晶: "crystal",
  里: "inside",
  唬: "fool",
  得: "have to",
  胆: "Bold",
  战: "war",
  惊: "shock",
  魂: "soul",
  飞: "fly",
  魄: "soul",
  散: "Scattered",
  龟: "turtle",
  鳖: "turtle",
  鼋: "sea ​​turtle",
  鼍: "turtle",
  皆: "all",
  缩: "Shrink",
  颈: "neck",
  鱼: "fish",
  虾: "shrimp",
  鳌: "Ao",
  蟹: "crab",
  将: "Will",
  执: "Persistence",
  坐: "sit",
  殿: "temple",
  对: "right",
  笑: "laugh",
  多: "many",
  谢: "Thanks",
  贤: "Virtue",
  邻: "adjacent",
  厚: "thick",
  虽: "although",
  然: "Of course",
  还: "return",
  甚: "very",
  当: "when",
  若: "like",
  无: "none",
  倒: "fall",
  罢: "stop",
  今: "now",
  既: "now that",
  身: "body",
  服: "Clothes",
  相: "Mutually",
  趁: "take advantage of",
  奈: "Nye",
  披: "路",
  挂: "hang",
  索: "Search",
  性: "sex",
  件: "Parts",
  总: "total",
  奉: "Feng",
  却: "but",
  没: "without",
  客: "guest",
  犯: "Infringement",
  主: "host",
  烦: "bother",
  或: "or",
  者: "Those",
  家: "Home",
  告: "tell",
  求: "beg",
  委: "Commission",
  即: "Right now",
  承: "Inherited",
  和: "and",
  试: "try",
  慌: "Panic",
  切: "cut",
  待: "treat",
  舍: "Abandon",
  弟: "younger brother",
  副: "vice",
  令: "make",
  南: "South",
  敖: "Ao",
  钦: "Qin",
  北: "north",
  顺: "Sure",
  西: "West",
  闰: "Leap",
  孙: "Sun",
  俗: "Vulgar",
  语: "language",
  谓: "Present",
  赊: "buy on credit",
  敌: "enemy",
  望: "see",
  随: "With",
  高: "high",
  低: "Low",
  鼓: "drum",
  钟: "bell",
  凡: "Any",
  急: "urgent",
  事: "thing",
  擂: "beat",
  响: "ring",
  撞: "Collide",
  鸣: "Ting",
  顷: "沪",
  刻: "carve",
  而: "and",
  快: "quick",
  帅: "handsome",
  5: "5",
  少: "few",
  臾: "For a moment",
  到: "arrive",
  齐: "together",
  会: "meeting",
  哥: "elder brother",
  花: "flower",
  山: "Mountain",
  生: "born",
  早: "morning",
  认: "recognize",
  居: "Residence",
  要: "want",
  兵: "Soldier",
  器: "Device",
  献: "offer",
  钢: "steel",
  叉: "fork",
  嫌: "Dislike",
  画: "painting",
  戟: "halberd",
  轻: "light",
  自: "since",
  己: "It's own",
  故: "Therefore",
  请: "please",
  发: "hair",
  闻: "smell",
  怒: "anger",
  兄: "Brother",
  点: "point",
  起: "rise",
  挽: "pull",
  儿: "Son",
  死: "die",
  磕: "knock",
  亡: "Death",
  皮: "Skin",
  破: "break",
  擦: "wipe",
  筋: "Tendons",
  伤: "hurt",
  凑: "Make up",
  启: "start",
  表: "surface",
  奏: "Play",
  诛: "punish",
  双: "pair",
  藕: "Lotus",
  丝: "Silk",
  步: "step",
  云: "cloud",
  履: "shoe",
  哩: "Li",
  带: "bring",
  锁: "Lock",
  黄: "yellow",
  甲: "First",
  顶: "top",
  凤: "phoenix",
  翅: "wing",
  紫: "purple",
  冠: "crown",
  入: "enter",
  以: "by",
  穿: "wear",
  戴: "Wear",
  停: "stop",
  使: "make",
  路: "road",
  众: "All",
  聒: "Hollow",
  噪: "noise",
  吵: "Quarrel",
  闹: "Furious",
  搅: "stir",
  四: "Four",
  平: "flat",
  商: "business",
  议: "Discussion",
  进: "Enter",
  题: "question",
};

const translations_de = {
  正: "Nur",
  说: "erklären",
  处: "Wo",
  后: "zurück",
  面: "Nudel",
  闪: "Blitz",
  过: "Passieren",
  龙: "Drachen",
  婆: "Mama",
  女: "weiblich",
  道: "Straße",
  大: "groß",
  王: "König",
  观: "Sicht",
  看: "sehen",
  此: "Das",
  圣: "Heilige",
  决: "Entscheidung",
  非: "NEIN",
  小: "Klein",
  可: "Kann",
  我: "ICH",
  们: "Wir",
  这: "Das",
  海: "Ozean",
  藏: "Tibetaner",
  中: "Mitte",
  那: "Das",
  一: "eins",
  块: "Stück",
  天: "Himmel",
  河: "Fluss",
  定: "Sicherlich",
  底: "Ende",
  的: "von",
  神: "Gott",
  珍: "Jen",
  铁: "Eisen",
  几: "Mehrere",
  日: "Tag",
  霞: "Xia",
  光: "Licht",
  艳: "Schön",
  瑞: "Rui",
  气: "Gas",
  腾: "Teng",
  敢: "wagen",
  莫: "MO",
  是: "Ja",
  该: "Sollen",
  出: "aus",
  现: "Jetzt",
  遇: "Treffen",
  也: "Auch",
  禹: "Yu",
  治: "Regel",
  水: "Wasser",
  之: "Von",
  时: "Stunde",
  江: "Fluss",
  浅: "seicht",
  深: "tief",
  个: "indival",
  子: "Sohn",
  能: "fähig",
  何: "Was",
  用: "verwenden",
  管: "Rohr",
  他: "Er",
  不: "NEIN",
  且: "Und",
  送: "liefern",
  与: "Und",
  凭: "Von",
  怎: "Wie",
  么: "Ist es",
  改: "ändern",
  造: "machen",
  宫: "Palast",
  门: "Tür",
  便: "Hoffnung",
  了: "Es ist",
  老: "alt",
  依: "entsprechend",
  言: "Wort",
  尽: "Alle",
  向: "In Richtung",
  悟: "Aufklärung",
  空: "NULL",
  拿: "nehmen",
  来: "Kommen",
  摇: "Shake",
  手: "Hand",
  扛: "Tragen",
  动: "bewegen",
  抬: "Aufzug",
  须: "Muss",
  上: "Vorgesetzter",
  仙: "Fee",
  亲: "relativ",
  去: "gehen",
  在: "existieren",
  你: "Du",
  引: "führen",
  果: "Obst",
  导: "Führung",
  至: "Zu",
  间: "zwischen",
  忽: "plötzlich",
  见: "Sehen",
  金: "Gold",
  万: "Zehntausend",
  指: "beziehen sich auf",
  放: "setzen",
  撩: "necken",
  衣: "Kleidung",
  前: "nach vorne",
  摸: "berühren",
  把: "Bündeln",
  乃: "Also",
  根: "Wurzel",
  柱: "Spalte",
  约: "um",
  有: "haben",
  斗: "kämpfen",
  粗: "dick",
  二: "zwei",
  丈: "zehn Fuß",
  余: "Bleiben",
  长: "lang",
  力: "Gewalt",
  两: "zwei",
  挝: "Betriebssystem",
  忒: "Wie",
  些: "manche",
  再: "Wieder",
  短: "kurz",
  细: "dünn",
  方: "Quadrat",
  毕: "vollständig",
  宝: "wertvoll",
  贝: "Cowry",
  就: "Auf einmal",
  尺: "Herrscher",
  围: "Umgeben",
  又: "wieder",
  颠: "Weit",
  更: "Sogar",
  好: "Gut",
  真: "real",
  分: "Punkt",
  十: "zehn",
  欢: "freudig",
  喜: "Glück",
  原: "Original",
  头: "Kopf",
  箍: "Band",
  段: "Teil",
  乌: "Wu",
  紧: "eng",
  挨: "leiden",
  镌: "gravieren",
  成: "werden",
  行: "OK",
  字: "Charakter",
  唤: "Anruf",
  做: "Tun",
  如: "wie",
  意: "Bedeutung",
  棒: "Großartig",
  重: "Schwer",
  三: "drei",
  千: "tausend",
  五: "fünf",
  百: "Hundert",
  斤: "katt",
  心: "Herz",
  暗: "dunkel",
  想: "denken",
  必: "muss",
  人: "Menschen",
  边: "Seite",
  走: "Gehen",
  思: "denken",
  口: "Mund",
  念: "lesen",
  着: "Setzen",
  妙: "wunderbar",
  外: "draußen",
  只: "Nur",
  碗: "Schüssel",
  弄: "Gasse",
  通: "Passieren",
  丢: "verlassen",
  开: "offen",
  解: "lösen",
  数: "Nummer",
  打: "schlagen",
  转: "ändern",
  晶: "Kristall",
  里: "innen",
  唬: "Narr",
  得: "müssen",
  胆: "Deutlich",
  战: "Krieg",
  惊: "Schock",
  魂: "Seele",
  飞: "fliegen",
  魄: "Seele",
  散: "Verstreut",
  龟: "Schildkröte",
  鳖: "Schildkröte",
  鼋: "Meeresschildkröte",
  鼍: "Schildkröte",
  皆: "alle",
  缩: "Schrumpfen",
  颈: "Nacken",
  鱼: "Fisch",
  虾: "Garnele",
  鳌: "Ao",
  蟹: "Krabbe",
  将: "Wille",
  执: "Ausdauer",
  坐: "sitzen",
  殿: "Tempel",
  对: "Rechts",
  笑: "lachen",
  多: "viele",
  谢: "Danke",
  贤: "Tugend",
  邻: "benachbart",
  厚: "dick",
  虽: "Obwohl",
  然: "Natürlich",
  还: "zurückkehren",
  甚: "sehr",
  当: "Wann",
  若: "wie",
  无: "keiner",
  倒: "fallen",
  罢: "stoppen",
  今: "Jetzt",
  既: "Nun das",
  身: "Körper",
  服: "Kleidung",
  相: "Gegenseitig",
  趁: "in Anspruch nehmen",
  奈: "Nye",
  披: "路",
  挂: "aufhängen",
  索: "Suchen",
  性: "Sex",
  件: "Teile",
  总: "gesamt",
  奉: "Feng",
  却: "Aber",
  没: "ohne",
  客: "Gast",
  犯: "Verletzung",
  主: "Gastgeber",
  烦: "sich kümmern",
  或: "oder",
  者: "Diese",
  家: "Heim",
  告: "erzählen",
  求: "bitten",
  委: "Kommission",
  即: "Im Augenblick",
  承: "Geerbt",
  和: "Und",
  试: "versuchen",
  慌: "Panik",
  切: "schneiden",
  待: "behandeln",
  舍: "Aufgeben",
  弟: "jüngerer Bruder",
  副: "Vize",
  令: "machen",
  南: "Süden",
  敖: "Ao",
  钦: "Qin",
  北: "Norden",
  顺: "Sicher",
  西: "West",
  闰: "Sprung",
  孙: "Sonne",
  俗: "Vulgär",
  语: "Sprache",
  谓: "Gegenwärtig",
  赊: "Kredite kaufen",
  敌: "Feind",
  望: "sehen",
  随: "Mit",
  高: "hoch",
  低: "Niedrig",
  鼓: "Trommel",
  钟: "Glocke",
  凡: "Beliebig",
  急: "dringend",
  事: "Ding",
  擂: "schlagen",
  响: "Ring",
  撞: "Kollidieren",
  鸣: "Ting",
  顷: "沪",
  刻: "schnitzen",
  而: "Und",
  快: "schnell",
  帅: "gutaussehend",
  5: "5",
  少: "wenige",
  臾: "Für einen Moment",
  到: "ankommen",
  齐: "zusammen",
  会: "treffen",
  哥: "älterer Bruder",
  花: "Blume",
  山: "Berg",
  生: "geboren",
  早: "Morgen",
  认: "erkennen",
  居: "Residenz",
  要: "wollen",
  兵: "Soldat",
  器: "Gerät",
  献: "Angebot",
  钢: "Stahl",
  叉: "Gabel",
  嫌: "Abneigung",
  画: "Malerei",
  戟: "Hellebarde",
  轻: "Licht",
  自: "seit",
  己: "Es ist eigen",
  故: "daher",
  请: "Bitte",
  发: "Haar",
  闻: "Geruch",
  怒: "Wut",
  兄: "Bruder",
  点: "Punkt",
  起: "erheben",
  挽: "ziehen",
  儿: "Sohn",
  死: "sterben",
  磕: "klopfen",
  亡: "Tod",
  皮: "Haut",
  破: "brechen",
  擦: "wischen",
  筋: "Sehnen",
  伤: "verletzt",
  凑: "Bilden",
  启: "Start",
  表: "Oberfläche",
  奏: "Spielen",
  诛: "bestrafen",
  双: "Paar",
  藕: "Lotus",
  丝: "Seide",
  步: "Schritt",
  云: "Wolke",
  履: "Schuh",
  哩: "Li",
  带: "bringen",
  锁: "Sperren",
  黄: "Gelb",
  甲: "Erste",
  顶: "Spitze",
  凤: "Phönix",
  翅: "Flügel",
  紫: "lila",
  冠: "Krone",
  入: "eingeben",
  以: "von",
  穿: "tragen",
  戴: "Tragen",
  停: "stoppen",
  使: "machen",
  路: "Straße",
  众: "Alle",
  聒: "Hohl",
  噪: "Lärm",
  吵: "Streit",
  闹: "Wütend",
  搅: "Aufsehen",
  四: "Vier",
  平: "Wohnung",
  商: "Geschäft",
  议: "Diskussion",
  进: "Eingeben",
  题: "Frage",
};

const translations_fr = {
  正: "juste",
  说: "expliquer",
  处: "Où",
  后: "dos",
  面: "nouille",
  闪: "éclair",
  过: "Passer",
  龙: "dragon",
  婆: "Maman",
  女: "femelle",
  道: "route",
  大: "grand",
  王: "roi",
  观: "Voir",
  看: "regarder",
  此: "ce",
  圣: "Saint",
  决: "Décision",
  非: "Non",
  小: "Petit",
  可: "Peut",
  我: "je",
  们: "Nous",
  这: "ce",
  海: "océan",
  藏: "Tibétain",
  中: "milieu",
  那: "Que",
  一: "un",
  块: "morceau",
  天: "ciel",
  河: "rivière",
  定: "Certainement",
  底: "fin",
  的: "de",
  神: "Dieu",
  珍: "Jen",
  铁: "fer",
  几: "Plusieurs",
  日: "jour",
  霞: "Xia",
  光: "Lumière",
  艳: "Beau",
  瑞: "Rui",
  气: "gaz",
  腾: "Tendre",
  敢: "oser",
  莫: "MO",
  是: "Oui",
  该: "Devrait",
  出: "dehors",
  现: "maintenant",
  遇: "Rencontrer",
  也: "aussi",
  禹: "Yu",
  治: "règle",
  水: "eau",
  之: "De",
  时: "heure",
  江: "Rivière",
  浅: "peu profond",
  深: "profond",
  个: "autonome",
  子: "fils",
  能: "capable",
  何: "quoi",
  用: "utiliser",
  管: "Tube",
  他: "il",
  不: "Non",
  且: "et",
  送: "livrer",
  与: "et",
  凭: "Par",
  怎: "Comment",
  么: "Est-ce",
  改: "changement",
  造: "faire",
  宫: "palais",
  门: "Porte",
  便: "Espoir",
  了: "C'est",
  老: "vieux",
  依: "selon",
  言: "Mot",
  尽: "Tous",
  向: "Vers",
  悟: "Éclaircissement",
  空: "nul",
  拿: "prendre",
  来: "Viens",
  摇: "secouer",
  手: "main",
  扛: "Porter",
  动: "se déplacer",
  抬: "ascenseur",
  须: "Doit",
  上: "supérieur",
  仙: "Fée",
  亲: "relatif",
  去: "aller",
  在: "exister",
  你: "toi",
  引: "plomb",
  果: "fruit",
  导: "guide",
  至: "à",
  间: "entre",
  忽: "soudainement",
  见: "Voir",
  金: "or",
  万: "Dix mille",
  指: "se référer à",
  放: "mettre",
  撩: "taquiner",
  衣: "Vêtements",
  前: "avant",
  摸: "touche",
  把: "Paquet",
  乃: "Donc",
  根: "racine",
  柱: "colonne",
  约: "à propos",
  有: "avoir",
  斗: "lutte",
  粗: "épais",
  二: "deux",
  丈: "dix pieds",
  余: "Rester",
  长: "long",
  力: "forcer",
  两: "deux",
  挝: "OS",
  忒: "Comment",
  些: "quelques",
  再: "Encore",
  短: "court",
  细: "mince",
  方: "carré",
  毕: "complet",
  宝: "précieux",
  贝: "bouc",
  就: "Immédiatement",
  尺: "règle",
  围: "Environnant",
  又: "encore",
  颠: "Loin",
  更: "Même",
  好: "bien",
  真: "réel",
  分: "indiquer",
  十: "dix",
  欢: "joyeux",
  喜: "bonheur",
  原: "Original",
  头: "tête",
  箍: "cerceau",
  段: "partie",
  乌: "Wu",
  紧: "serré",
  挨: "souffrir",
  镌: "graver",
  成: "devenir",
  行: "D'ACCORD",
  字: "Personnage",
  唤: "Appel",
  做: "Faire",
  如: "comme",
  意: "signification",
  棒: "Super",
  重: "Lourd",
  三: "trois",
  千: "mille",
  五: "cinq",
  百: "Cent",
  斤: "méchant",
  心: "Cœur",
  暗: "sombre",
  想: "pense",
  必: "doit",
  人: "personnes",
  边: "côté",
  走: "Marcher",
  思: "pense",
  口: "bouche",
  念: "lire",
  着: "Mettre",
  妙: "merveilleux",
  外: "dehors",
  只: "Seulement",
  碗: "bol",
  弄: "ruelle",
  通: "Passer",
  丢: "partir",
  开: "ouvrir",
  解: "délier",
  数: "nombre",
  打: "battre",
  转: "changement",
  晶: "cristal",
  里: "à l'intérieur",
  唬: "idiot",
  得: "devoir",
  胆: "Audacieux",
  战: "guerre",
  惊: "choc",
  魂: "âme",
  飞: "voler",
  魄: "âme",
  散: "Dispersé",
  龟: "tortue",
  鳖: "tortue",
  鼋: "tortue de mer",
  鼍: "tortue",
  皆: "tous",
  缩: "Rétrécir",
  颈: "cou",
  鱼: "poisson",
  虾: "crevette",
  鳌: "AO",
  蟹: "crabe",
  将: "Volonté",
  执: "Persistance",
  坐: "s'asseoir",
  殿: "temple",
  对: "droite",
  笑: "rire",
  多: "beaucoup",
  谢: "Merci",
  贤: "Vertu",
  邻: "adjacent",
  厚: "épais",
  虽: "bien que",
  然: "Bien sûr",
  还: "retour",
  甚: "très",
  当: "quand",
  若: "comme",
  无: "aucun",
  倒: "automne",
  罢: "arrêt",
  今: "maintenant",
  既: "maintenant que",
  身: "corps",
  服: "Vêtements",
  相: "Mutuellement",
  趁: "profiter de",
  奈: "Nye",
  披: "路",
  挂: "accrocher",
  索: "Recherche",
  性: "sexe",
  件: "Parties",
  总: "total",
  奉: "Feng",
  却: "mais",
  没: "sans",
  客: "invité",
  犯: "Infraction",
  主: "hôte",
  烦: "déranger",
  或: "ou",
  者: "Ceux",
  家: "Maison",
  告: "dire",
  求: "mendier",
  委: "Commission",
  即: "Tout de suite",
  承: "Hérité",
  和: "et",
  试: "essayer",
  慌: "Panique",
  切: "couper",
  待: "traiter",
  舍: "Abandonner",
  弟: "jeune frère",
  副: "vice",
  令: "faire",
  南: "Sud",
  敖: "AO",
  钦: "Qin",
  北: "nord",
  顺: "Bien sûr",
  西: "Ouest",
  闰: "Saut",
  孙: "Soleil",
  俗: "Vulgaire",
  语: "langue",
  谓: "Présent",
  赊: "Acheter à crédit",
  敌: "ennemi",
  望: "voir",
  随: "Avec",
  高: "haut",
  低: "Faible",
  鼓: "tambour",
  钟: "cloche",
  凡: "N'importe lequel",
  急: "urgent",
  事: "chose",
  擂: "battre",
  响: "anneau",
  撞: "Entrer en collision",
  鸣: "Ting",
  顷: "沪",
  刻: "tailler",
  而: "et",
  快: "rapide",
  帅: "beau",
  5: "5",
  少: "peu",
  臾: "Pendant un moment",
  到: "arriver",
  齐: "ensemble",
  会: "réunion",
  哥: "frère aîné",
  花: "fleur",
  山: "Montagne",
  生: "né",
  早: "matin",
  认: "reconnaître",
  居: "Résidence",
  要: "vouloir",
  兵: "Soldat",
  器: "Appareil",
  献: "offre",
  钢: "acier",
  叉: "fourchette",
  嫌: "Aversion",
  画: "peinture",
  戟: "hallebarde",
  轻: "lumière",
  自: "depuis",
  己: "C'est propre",
  故: "Donc",
  请: "s'il te plaît",
  发: "cheveux",
  闻: "odeur",
  怒: "colère",
  兄: "Frère",
  点: "indiquer",
  起: "augmenter",
  挽: "tirer",
  儿: "Fils",
  死: "mourir",
  磕: "frappe",
  亡: "La mort",
  皮: "Peau",
  破: "casser",
  擦: "essuyer",
  筋: "Tendons",
  伤: "blesser",
  凑: "Se maquiller",
  启: "commencer",
  表: "surface",
  奏: "Jouer",
  诛: "punir",
  双: "paire",
  藕: "Lotus",
  丝: "Soie",
  步: "étape",
  云: "nuage",
  履: "chaussure",
  哩: "Li",
  带: "apporter",
  锁: "Verrouillage",
  黄: "jaune",
  甲: "D'abord",
  顶: "haut",
  凤: "phénix",
  翅: "aile",
  紫: "violet",
  冠: "couronne",
  入: "entrer",
  以: "par",
  穿: "porter",
  戴: "Porter",
  停: "arrêt",
  使: "faire",
  路: "route",
  众: "Tous",
  聒: "Creux",
  噪: "bruit",
  吵: "Querelle",
  闹: "Furieux",
  搅: "remuer",
  四: "Quatre",
  平: "plat",
  商: "entreprise",
  议: "Discussion",
  进: "Entrer",
  题: "question",
};

const tianwen_translation_map_en = {
  正说处: "The right place to talk",
  后面闪过龙婆龙女道: "The Luang Po Long Nu's story flashed behind",
  大王: "The King",
  观看此圣: "Watch this saint",
  决非小可: "Not small",
  我们这海藏中: "We are in the sea",
  那一块天河定底的神珍铁:
    "That precious iron that is fixed on the bottom of the sky",
  这几日霞光艳艳: "These days, the glow is bright",
  瑞气腾腾: "Ruiqi",
  敢莫是该出现: "Dare you should show up",
  遇此圣也: "Meet this saint",
  龙王道: "Dragon King's Way",
  那是大禹治水之时: "That was when Dayu controlled the flood",
  定江海浅深的一个定子:
    "A stator that can be used to determine the depth of the river and sea",
  是一块神铁: "It's a magical iron",
  能中何用: "What can be used for",
  龙婆道: "Luang Po Tao",
  莫管他用不用: "Don't care whether he uses it or not",
  且送与他: "Give him a gift",
  凭他怎么改造: "How to transform it",
  送出宫门便了: "It's time to send it out of the palace gate",
  老龙王依言: "The old dragon king as he said",
  尽向悟空说了: "Say it all to Wukong",
  悟空道: "Wukong Tao",
  拿出来我看: "Take it out and I'll see",
  龙王摇手道: "Dragon King waves his hands",
  扛不动: "Can't carry it",
  抬不动: "Can't lift",
  须上仙亲去看看: "I'll go and see it with my own eyes",
  悟空道: "Wukong Tao",
  在何处: "Where is it",
  你引我去: "You lead me there",
  龙王果引导至海藏中间:
    "Dragon King Fruit guides to the middle of the treasury",
  忽见金光万道: "Suddenly, I saw thousands of golden lights",
  龙王指定道: "Dragon King designated road",
  那放光的便是: "The one that shines is",
  悟空撩衣上前: "Wukong flirts with his clothes",
  摸了一把: "Touched",
  乃是一根铁柱子: "It's an iron pillar",
  约有斗来粗: "I'm going to have a fight",
  二丈有余长: "Two feet long",
  他尽力两手挝过道: "He tried his best to exert the aisle",
  忒粗忒长些: "Too thicker and longer",
  再短细些方可用: "A shorter and thinner can be used",
  说毕: "After saying",
  那宝贝就短了几尺: "That baby is a few feet shorter",
  细了一围: "A little thin",
  悟空又颠一颠道: "Wukong was confused again",
  再细些更好: "Better to be more detailed",
  那宝贝真个又细了几分: "That baby is a little bit more delicate",
  悟空十分欢喜: "Wukong is very happy",
  拿出海藏看时: "When I took it out of the sea treasury",
  原来两头是两个金箍:
    "It turns out that there are two golden hoops on both ends",
  中间乃一段乌铁: "There is a black iron in the middle",
  紧挨箍有镌成的一行字: "A line of characters engraved next to the hoop",
  唤做如意金箍棒: "Call it Ruyi Golden Hoop",
  重一万三千五百斤: "Weighing 13,500 kilograms",
  心中暗喜道: "I secretly said happily",
  想必这宝贝如人意: "I guess this baby is as good as everyone",
  一边走: "Walking while",
  一边心思口念: "Thoughts and chants",
  手颠着道: "Hands swaying",
  再短细些更妙: "It's better to be shorter or thinner",
  拿出外面: "Take it out",
  只有二丈长短: "Only two feet long",
  碗口粗细: "Bowl thickness",
  你看他弄神通: "Look at him doing magical powers",
  丢开解数: "Lost the solution number",
  打转水晶宫里: "Turning around in the Crystal Palace",
  唬得老龙王胆战心惊: "The old dragon king was frightened",
  小龙子魂飞魄散: "Little Dragonson's soul is gone",
  龟鳖鼋鼍皆缩颈: "All turtles and tortoises and turtles shrink their necks",
  鱼虾鳌蟹尽藏头: "Fish, shrimp, crabs, hide their heads",
  悟空将宝贝执在手中: "Wukong holds the baby in his hand",
  坐在水晶宫殿上: "Sitting in the Crystal Palace",
  对龙王笑道: "Smile to the Dragon King",
  多谢贤邻厚意: "Thank you for your kindness",
  龙王道: "Dragon King's Way",
  不敢不敢: "Don't dare, don't dare",
  悟空道: "Wukong Tao",
  这块铁虽然好用: "Although this iron is easy to use",
  还有一说: "Another thing to say",
  龙王道: "Dragon King's Way",
  上仙还有甚说: "What else does the immortal say",
  悟空道: "Wukong Tao",
  当时若无此铁: "If there was no such iron at that time",
  倒也罢了: "Not bad",
  如今手中既拿着他: "Now holding him in your hand",
  身上无衣服相趁: "No clothes on your body",
  奈何: "How",
  你这里若有披挂: "If you have a hang here",
  索性送我一件: "Give me one",
  一总奉谢: "Thank you",
  龙王道: "Dragon King's Way",
  这个却是没有: "But this is not",
  悟空道: "Wukong Tao",
  一客不犯二主: "One guest will not offend two masters",
  若没有: "If not",
  我也定不出此门: "I can't make it out, either",
  龙王道: "Dragon King's Way",
  烦上仙再转一海: "I'm sorry for the immortals to turn another sea",
  或者有之: "Or some",
  悟空又道: "Wukong said again",
  走三家不如坐一家: "It’s better to sit in one place than to walk three",
  千万告求一件: "I'll ask for one",
  龙王道: "Dragon King's Way",
  委的没有: "No",
  如有即当奉承: "If there is anything, please flatter it",
  悟空道: "Wukong Tao",
  真个没有: "Really no",
  就和你试试此铁: "Just try this iron with you",
  龙王慌了道: "The Dragon King said in panic",
  上仙: "The Immortal",
  切莫动手: "Don't do it",
  切莫动手: "Don't do it",
  待我看舍弟处可有: "I'll see if my brother's place is there",
  当送一副: "Give one",
  悟空道: "Wukong Tao",
  令弟何在: "Where is Ling?",
  龙王道: "Dragon King's Way",
  舍弟乃南海龙王敖钦:
    "My younger brother is Ao Qin, the Dragon King of the South China Sea",
  北海龙王敖顺: "North Sea Dragon King Ao Shun",
  西海龙王敖闰是也: "The Dragon King of the West Sea is also",
  悟空道: "Wukong Tao",
  我老孙不去: "My old grandson won't go",
  不去: "Don't go",
  俗语谓赊三不敌见二:
    'As the saying goes, "Credit Three is not the same as seeing two"',
  只望你随高就低的送一副便了: "I just hope you will give me a pair as you like",
  老龙道: "Old Dragon",
  不须上仙去: "No need to go to the immortal",
  我这里有一面铁鼓: "I have an iron drum here",
  一口金钟: "A golden bell",
  凡有紧急事: "Any urgent matter",
  擂得鼓响: "The drum beats",
  撞得钟鸣: "The bell rings",
  舍弟们就顷刻而至: "My brothers arrived in an instant",
  悟空道: "Wukong Tao",
  既是如此: "Since that's the case",
  快些去擂鼓撞钟: "Go and beat the drum and hit the bell quickly",
  真个那鼍将便去撞钟: "That turtle hit the bell",
  鳖帅即来擂鼓: "The turtle coach is coming to beat the drums",
  5: "5",
  少时: "A few times",
  钟鼓响处: "Where the bell and drums sound",
  果然惊动那三海龙王: "Sure enough, the Dragon King of the Three Seas",
  须臾来到: "Coming in a moment",
  一齐在外面会着: "Meet outside together",
  敖钦道: "Ao Qindao",
  大哥: "Big brother",
  有甚紧事: "Something is so important",
  擂鼓撞钟: "Beat the drum and hit the bell",
  老龙道: "Old Dragon",
  贤弟: "Brother",
  不好说: "Not easy to say",
  有一个花果山甚么天生圣人:
    "There is a Huaguo Mountain, what is a natural saint",
  早间来认我做邻居: "Come to recognize me as your neighbor in the morning",
  后来要求一件兵器: "Later, a weapon was requested",
  献钢叉嫌小: "The steel fork is small",
  奉画戟嫌轻: "The painting halberd is light",
  将一块天河定底神珍铁:
    "A piece of divine iron that sets the bottom of the sky",
  自己拿出手: "Take it out yourself",
  丢了些解数: "Lost some solutions",
  如今坐在宫中: "Sitting in the palace now",
  又要索甚么披挂: "What other hangs are you going to ask for?",
  我处无有: "I have nothing",
  故响钟鸣鼓: "Therefore, the bells and drums ring",
  请贤弟来: "Please come here by my dear brother",
  你们可有甚么披挂: "What kind of hang do you have",
  送他一副: "Give him a pair",
  打发出门去罢了: "Just send it out",
  敖钦闻言: "Ao Qin heard",
  大怒道: "Furiously said",
  我兄弟们: "My brothers",
  点起兵: "Start a troops",
  拿他不是: "Not taking him",
  老龙道: "Old Dragon",
  莫说拿: "Don't say take it",
  那块铁: "That iron",
  挽着些儿就死: "If you hold it a little, you will die",
  磕着些儿就亡: "Knocking a little",
  挨挨皮儿破: "Going to the skin",
  擦擦儿筋伤: "Rub the tendon injury",
  西海龙王敖闰说: "The Dragon King of the West Sea Ao Run said",
  二哥不可与他动手: "Second brother can't fight him",
  且只凑副披挂与他: "And only the pair of robes and him",
  打发他出了门: "Send him out of the door",
  启表奏上上天: "Reveal the melody of heaven",
  天自诛也: "God will kill you",
  北海龙王敖顺道: "North Sea Dragon King Ao Shundao",
  说的是: "What I mean",
  我这里有一双藕丝步云履哩: "I have a pair of lotus silk slivered clouds here",
  西海龙王敖闰道: "The Dragon King of the West Sea Ao Rundao",
  我带了一副锁子黄金甲哩: "I brought a pair of golden armors with locks",
  南海龙王敖钦道: "Ao Qindao, the Dragon King of the South China Sea",
  我有一顶凤翅紫金冠哩: "I have a purple gold crown with phoenix wings",
  老龙大喜: "Old Dragon is very happy",
  引入水晶宫相见了: "Introduce Crystal Palace to meet",
  以此奉上: "Offer this",
  悟空将金冠: "Wukong takes the golden crown",
  金甲: "Golden Armor",
  云履那穿戴停当: "Yunlu's dressing stops",
  使动如意棒: "Make the best wishes",
  一路打出去: "Try it all the way",
  对众龙道: "The Way of Dragons",
  聒噪: "Noisy",
  吵闹: "noisy",
  打搅: "disturb",
  聒噪: "Noisy",
  四海龙王甚是不平: "The Dragon King of the Four Seas is very unfair",
  一边商议进表上奏不题:
    "While discussing the report, no question will be given",
};

const tianwen_translation_map_de = {
  正说处: "Der richtige Ort zum Reden",
  后面闪过龙婆龙女道: "Die Geschichte von Luang Po Long Nus blitzte dahinter",
  大王: "Der König",
  观看此圣: "Beobachten Sie diesen Heiligen",
  决非小可: "Nicht klein",
  我们这海藏中: "Wir sind im Meer",
  那一块天河定底的神珍铁:
    "Das kostbare Eisen, das am Boden des Himmels fixiert ist",
  这几日霞光艳艳: "Heutzutage ist das Leuchten hell",
  瑞气腾腾: "Ruiqi",
  敢莫是该出现: "Wagen Sie, Sie sollten auftauchen",
  遇此圣也: "Treffen Sie diesen Heiligen",
  龙王道: "Weg des Drachenkönigs",
  那是大禹治水之时: "Dann kontrollierte Dayu die Flut",
  定江海浅深的一个定子:
    "Ein Stator, mit dem die Tiefe von Fluss und Meer bestimmen kann",
  是一块神铁: "Es ist ein magisches Eisen",
  能中何用: "Was kann für verwendet werden",
  龙婆道: "Luang Po Tao",
  莫管他用不用: "Es ist egal, ob er es benutzt oder nicht",
  且送与他: "Gib ihm ein Geschenk",
  凭他怎么改造: "Wie man es verwandelt",
  送出宫门便了: "Es ist Zeit, es aus dem Palasttor zu schicken",
  老龙王依言: "Der alte Drachenkönig, wie er sagte",
  尽向悟空说了: "Sag alles zu Wukong",
  悟空道: "Wukong Tao",
  拿出来我看: "Nehmen Sie es heraus und ich werde sehen",
  龙王摇手道: "Drachenkönig winkt die Hände",
  扛不动: "Kann es nicht tragen",
  抬不动: "Kann nicht heben",
  须上仙亲去看看: "Ich werde es mit meinen eigenen Augen sehen",
  悟空道: "Wukong Tao",
  在何处: "Wo ist es",
  你引我去: "Du führst mich dorthin",
  龙王果引导至海藏中间:
    "Dragon King Fruit Guides in die Mitte des Finanzministeriums",
  忽见金光万道: "Plötzlich sah ich Tausende von goldenen Lichtern",
  龙王指定道: "Dragon King als Straße ausgewiesen",
  那放光的便是: "Derjenige, der glänzt ist",
  悟空撩衣上前: "Wukong flirtet mit seinen Kleidern",
  摸了一把: "Berührt",
  乃是一根铁柱子: "Es ist eine Eisensäule",
  约有斗来粗: "Ich werde einen Kampf haben",
  二丈有余长: "Zwei Fuß lang",
  他尽力两手挝过道: "Er versuchte sein Bestes, um den Gang auszuüben",
  忒粗忒长些: "Zu dicker und länger",
  再短细些方可用: "Ein kürzerer und dünnerer kann verwendet werden",
  说毕: "Nachdem er gesagt hatte",
  那宝贝就短了几尺: "Das Baby ist ein paar Meter kürzer",
  细了一围: "Ein wenig dünn",
  悟空又颠一颠道: "Wukong war wieder verwirrt",
  再细些更好: "Besser detaillierter sein",
  那宝贝真个又细了几分: "Das Baby ist ein bisschen empfindlicher",
  悟空十分欢喜: "Wukong ist sehr glücklich",
  拿出海藏看时: "Als ich es aus dem Meeres Schatzkammer nahm",
  原来两头是两个金箍:
    "Es stellt sich heraus, dass es an beiden Enden zwei goldene Reifen gibt",
  中间乃一段乌铁: "Es gibt ein schwarzes Eisen in der Mitte",
  紧挨箍有镌成的一行字: "Eine Reihe von Charakteren neben dem Reifen graviert",
  唤做如意金箍棒: "Nennen Sie es Ruyi Golden Hoop",
  重一万三千五百斤: "Mit einem Gewicht von 13.500 Kilogramm",
  心中暗喜道: "Ich sagte heimlich glücklich glücklich",
  想必这宝贝如人意: "Ich denke, dieses Baby ist so gut wie alle",
  一边走: "Gehen während",
  一边心思口念: "Gedanken und Gesänge",
  手颠着道: "Hände schwanken",
  再短细些更妙: "Es ist besser, kürzer oder dünner zu sein",
  拿出外面: "Nimm es raus",
  只有二丈长短: "Nur zwei Fuß lang",
  碗口粗细: "Schüsselstärke",
  你看他弄神通: "Schau ihn an, wie er magische Kräfte macht",
  丢开解数: "Verloren die Lösungsnummer",
  打转水晶宫里: "Drehen sich im Kristallpalast um",
  唬得老龙王胆战心惊: "Der alte Drachenkönig hatte verängstigt",
  小龙子魂飞魄散: "Little Dragonsons Seele ist weg",
  龟鳖鼋鼍皆缩颈:
    "Alle Schildkröten und Schildkröten und Schildkröten verkleinern ihren Hals",
  鱼虾鳌蟹尽藏头: "Fisch, Garnelen, Krabben, verstecken ihre Köpfe",
  悟空将宝贝执在手中: "Wukong hält das Baby in der Hand",
  坐在水晶宫殿上: "Im Kristallpalast sitzen",
  对龙王笑道: "Lächle dem Drachenkönig",
  多谢贤邻厚意: "Vielen Dank für Ihre Freundlichkeit",
  龙王道: "Weg des Drachenkönigs",
  不敢不敢: "Tragen Sie es nicht, wagen Sie es nicht",
  悟空道: "Wukong Tao",
  这块铁虽然好用: "Obwohl dieses Eisen einfach zu bedienen ist",
  还有一说: "Eine andere Sache zu sagen",
  龙王道: "Weg des Drachenkönigs",
  上仙还有甚说: "Was sagt der Unsterbliche sonst noch?",
  悟空道: "Wukong Tao",
  当时若无此铁: "Wenn es zu dieser Zeit kein solches Eisen gab",
  倒也罢了: "Nicht schlecht",
  如今手中既拿着他: "Jetzt halten Sie ihn in Ihrer Hand",
  身上无衣服相趁: "Keine Kleidung auf Ihrem Körper",
  奈何: "Wie",
  你这里若有披挂: "Wenn Sie hier einen Aufhängen haben",
  索性送我一件: "Gib mir einen",
  一总奉谢: "Danke",
  龙王道: "Weg des Drachenkönigs",
  这个却是没有: "Aber das ist nicht",
  悟空道: "Wukong Tao",
  一客不犯二主: "Ein Gast wird zwei Meister nicht beleidigen",
  若没有: "Wenn nicht",
  我也定不出此门: "Ich kann es auch nicht schaffen",
  龙王道: "Weg des Drachenkönigs",
  烦上仙再转一海:
    "Es tut mir leid, dass die Unsterblichen ein weiteres Meer drehen",
  或者有之: "Oder einige",
  悟空又道: "Sagte Wukong erneut",
  走三家不如坐一家: "Es ist besser, an einem Ort zu sitzen, als drei zu laufen",
  千万告求一件: "Ich werde nach einem fragen",
  龙王道: "Weg des Drachenkönigs",
  委的没有: "NEIN",
  如有即当奉承: "Wenn es etwas gibt, schmeicheln Sie es bitte",
  悟空道: "Wukong Tao",
  真个没有: "Wirklich nein",
  就和你试试此铁: "Probieren Sie einfach dieses Eisen mit Ihnen",
  龙王慌了道: "Sagte der Drachenkönig in Panik",
  上仙: "Der Unsterbliche",
  切莫动手: "Tu es nicht",
  切莫动手: "Tu es nicht",
  待我看舍弟处可有: "Ich werde sehen, ob der Platz meines Bruders da ist",
  当送一副: "Gib einen",
  悟空道: "Wukong Tao",
  令弟何在: "Wo ist Ling?",
  龙王道: "Weg des Drachenkönigs",
  舍弟乃南海龙王敖钦:
    "Mein jüngerer Bruder ist Ao Qin, der Drachenkönig des Südchinesischen Meeres",
  北海龙王敖顺: "Drachenkönig der Nordsee Ao Shun",
  西海龙王敖闰是也: "Der Drachenkönig der Westmeer ist auch",
  悟空道: "Wukong Tao",
  我老孙不去: "Mein alter Enkel wird nicht gehen",
  不去: "Geh nicht",
  俗语谓赊三不敌见二:
    'Wie das Sprichwort sagt: "Credit Three ist nicht dasselbe wie zwei zu sehen."',
  只望你随高就低的送一副便了:
    "Ich hoffe nur, dass Sie mir ein Paar geben, wie Sie möchten",
  老龙道: "Alter Drache",
  不须上仙去: "Keine Notwendigkeit, zum Unsterblichen zu gehen",
  我这里有一面铁鼓: "Ich habe hier eine eiserne Trommel",
  一口金钟: "Eine goldene Glocke",
  凡有紧急事: "Jede dringende Angelegenheit",
  擂得鼓响: "Die Trommel schlägt",
  撞得钟鸣: "Die Glocke klingelt",
  舍弟们就顷刻而至: "Meine Brüder kamen sofort an",
  悟空道: "Wukong Tao",
  既是如此: "Da ist das der Fall",
  快些去擂鼓撞钟: "Geh und schlage die Trommel und schlage schnell die Glocke",
  真个那鼍将便去撞钟: "Diese Schildkröte traf die Glocke",
  鳖帅即来擂鼓: "Der Turtle -Trainer kommt, um die Trommeln zu schlagen",
  5: "5",
  少时: "Ein paar Mal",
  钟鼓响处: "Wo die Glocke und Trommeln klingen",
  果然惊动那三海龙王: "Sicher genug, der Drachenkönig der drei Meere",
  须臾来到: "Einen Moment kommen",
  一齐在外面会着: "Treffen Sie sich zusammen zusammen",
  敖钦道: "Ao Qindao",
  大哥: "Big Brother",
  有甚紧事: "Etwas ist so wichtig",
  擂鼓撞钟: "Schlagen Sie die Trommel und schlagen Sie die Glocke",
  老龙道: "Alter Drache",
  贤弟: "Bruder",
  不好说: "Nicht leicht zu sagen",
  有一个花果山甚么天生圣人:
    "Es gibt einen Huaguo -Berg, was ein natürlicher Heiliger ist",
  早间来认我做邻居:
    "Kommen Sie, um mich morgens als Ihren Nachbarn zu erkennen",
  后来要求一件兵器: "Später wurde eine Waffe angefordert",
  献钢叉嫌小: "Die Stahlgabel ist klein",
  奉画戟嫌轻: "Das Gemäldehaleberd ist leicht",
  将一块天河定底神珍铁: "Ein Stück göttliches Eisen, das den Himmelboden setzt",
  自己拿出手: "Nehmen Sie es selbst heraus",
  丢了些解数: "Einige Lösungen verloren",
  如今坐在宫中: "Jetzt im Palast sitzen",
  又要索甚么披挂: "Nach welchen anderen Hängen werden Sie fragen?",
  我处无有: "Ich habe nichts",
  故响钟鸣鼓: "Daher klingeln die Glocken und Trommeln",
  请贤弟来: "Bitte komm mit meinem lieben Bruder hierher",
  你们可有甚么披挂: "Was für ein Hang hast du?",
  送他一副: "Gib ihm ein Paar",
  打发出门去罢了: "Senden Sie es einfach aus",
  敖钦闻言: "Ao Qin hörte",
  大怒道: "Sagte wütend",
  我兄弟们: "Meine Brüder",
  点起兵: "Starten Sie eine Truppen",
  拿他不是: "Ihn nicht nehmen",
  老龙道: "Alter Drache",
  莫说拿: "Sag nicht, nimm es",
  那块铁: "Das Eisen",
  挽着些儿就死: "Wenn Sie es ein wenig halten, werden Sie sterben",
  磕着些儿就亡: "Ein wenig klopfen",
  挨挨皮儿破: "Gehäutet werden",
  擦擦儿筋伤: "Reiben Sie die Sehnenverletzung",
  西海龙王敖闰说: "Der Drachenkönig des Westsee -AO -Laufs sagte",
  二哥不可与他动手: "Der zweite Bruder kann ihn nicht bekämpfen",
  且只凑副披挂与他: "Und nur das Paar Roben und er",
  打发他出了门: "Schick ihn aus der Tür",
  启表奏上上天: "Enthüllen Sie die Melodie des Himmels",
  天自诛也: "Gott wird dich töten",
  北海龙王敖顺道: "Nordsee Drachen König Ao Shundao",
  说的是: "Was ich meine",
  我这里有一双藕丝步云履哩:
    "Ich habe hier ein Paar Lotus -Seiden -Splitter -Wolken",
  西海龙王敖闰道: "Der Drachenkönig des Westsee Ao Rundao",
  我带了一副锁子黄金甲哩:
    "Ich brachte ein Paar goldene Rüstungen mit Schlösser mit",
  南海龙王敖钦道: "Ao Qindao, der Drachenkönig des Südchinesischen Meeres",
  我有一顶凤翅紫金冠哩: "Ich habe eine lila Goldkrone mit Phoenix -Flügeln",
  老龙大喜: "Der alte Drache ist sehr glücklich",
  引入水晶宫相见了: "Stellen Sie den Kristallpalast vor, um sich zu treffen",
  以此奉上: "Bieten Sie dies an",
  悟空将金冠: "Wukong nimmt die goldene Krone",
  金甲: "Goldene Rüstung",
  云履那穿戴停当: "Yunlus Dressing stoppt",
  使动如意棒: "Die besten Wünsche machen",
  一路打出去: "Versuchen Sie es den ganzen Weg",
  对众龙道: "Die Drachen",
  聒噪: "Laut",
  吵闹: "laut",
  打搅: "stören",
  聒噪: "Laut",
  四海龙王甚是不平: "Der Drachenkönig der vier Meere ist sehr unfair",
  一边商议进表上奏不题:
    "Während der Diskussion des Berichts wird keine Frage gestellt",
};

const tianwen_translation_map_fr = {
  正说处: "Le bon endroit pour parler",
  后面闪过龙婆龙女道:
    "L'histoire de Luang Po Long Nu s'est précipitée derrière",
  大王: "Le roi",
  观看此圣: "Regardez ce saint",
  决非小可: "Pas petit",
  我们这海藏中: "Nous sommes dans la mer",
  那一块天河定底的神珍铁: "Ce fer précieux qui est fixé au fond du ciel",
  这几日霞光艳艳: "Ces jours-ci, la lueur est brillante",
  瑞气腾腾: "Ruiqi",
  敢莫是该出现: "Osez-vous vous présenter",
  遇此圣也: "Rencontrer ce saint",
  龙王道: "Dragon King's Way",
  那是大禹治水之时: "C'est à ce moment que Dayu a contrôlé l'inondation",
  定江海浅深的一个定子:
    "Un stator qui peut être utilisé pour déterminer la profondeur de la rivière et de la mer",
  是一块神铁: "C'est un fer magique",
  能中何用: "Ce qui peut être utilisé pour",
  龙婆道: "Luang Po Tao",
  莫管他用不用: "Je ne me soucie pas s'il l'utilise ou non",
  且送与他: "Offrez-lui un cadeau",
  凭他怎么改造: "Comment le transformer",
  送出宫门便了: "Il est temps de l'envoyer de la porte du palais",
  老龙王依言: "Le vieux roi de dragon comme il l'a dit",
  尽向悟空说了: "Dites tout à Wukong",
  悟空道: "Wukong Tao",
  拿出来我看: "Sortez et je verrai",
  龙王摇手道: "Dragon King agite ses mains",
  扛不动: "Je ne peux pas le porter",
  抬不动: "Je ne peux pas soulever",
  须上仙亲去看看: "Je vais aller le voir de mes propres yeux",
  悟空道: "Wukong Tao",
  在何处: "Où est-il",
  你引我去: "Tu me conduis là-bas",
  龙王果引导至海藏中间: "Dragon King Fruit guides au milieu du Trésor",
  忽见金光万道: "Soudain, j'ai vu des milliers de lumières dorées",
  龙王指定道: "Dragon King Route désignée",
  那放光的便是: "Celui qui brille est",
  悟空撩衣上前: "Wukong flirte avec ses vêtements",
  摸了一把: "Touché",
  乃是一根铁柱子: "C'est un pilier en fer",
  约有斗来粗: "Je vais me battre",
  二丈有余长: "Deux pieds de long",
  他尽力两手挝过道: "Il a fait de son mieux pour exercer l'allée",
  忒粗忒长些: "Trop plus épais et plus long",
  再短细些方可用: "Un plus court et plus mince peut être utilisé",
  说毕: "Après avoir dit",
  那宝贝就短了几尺: "Ce bébé est à quelques pieds plus court",
  细了一围: "Un peu mince",
  悟空又颠一颠道: "Wukong était à nouveau confus",
  再细些更好: "Mieux vaut être plus détaillé",
  那宝贝真个又细了几分: "Ce bébé est un peu plus délicat",
  悟空十分欢喜: "Wukong est très heureux",
  拿出海藏看时: "Quand je l'ai sorti du trésor marin",
  原来两头是两个金箍:
    "Il s'avère qu'il y a deux cerceaux dorés aux deux extrémités",
  中间乃一段乌铁: "Il y a un fer noir au milieu",
  紧挨箍有镌成的一行字: "Une ligne de personnages gravés à côté du cerceau",
  唤做如意金箍棒: "Appelez ça Ruyi Golden Hoop",
  重一万三千五百斤: "Pesant 13 500 kilogrammes",
  心中暗喜道: "J'ai secrètement dit",
  想必这宝贝如人意: "Je suppose que ce bébé est aussi bon que tout le monde",
  一边走: "Marcher pendant que",
  一边心思口念: "Pensées et chants",
  手颠着道: "Les mains qui se balancent",
  再短细些更妙: "Il vaut mieux être plus court ou plus mince",
  拿出外面: "Retirer",
  只有二丈长短: "Seulement deux pieds de long",
  碗口粗细: "Taille du bol",
  你看他弄神通: "Regarde-le faire des pouvoirs magiques",
  丢开解数: "Perdu le numéro de solution",
  打转水晶宫里: "Se retourner dans le Crystal Palace",
  唬得老龙王胆战心惊: "Le vieux roi de dragon avait peur",
  小龙子魂飞魄散: "L'âme de Little Dragonson est partie",
  龟鳖鼋鼍皆缩颈:
    "Toutes les tortues et tortues et tortues rétrécissent le cou",
  鱼虾鳌蟹尽藏头: "Poisson, crevettes, crabes, cachez la tête",
  悟空将宝贝执在手中: "Wukong tient le bébé à la main",
  坐在水晶宫殿上: "Assis dans le Crystal Palace",
  对龙王笑道: "Sourire au roi dragon",
  多谢贤邻厚意: "Merci pour votre gentillesse",
  龙王道: "Dragon King's Way",
  不敢不敢: "N'ose pas, n'ose pas",
  悟空道: "Wukong Tao",
  这块铁虽然好用: "Bien que ce fer soit facile à utiliser",
  还有一说: "Une autre chose à dire",
  龙王道: "Dragon King's Way",
  上仙还有甚说: "Que dit l'immortel d'autre",
  悟空道: "Wukong Tao",
  当时若无此铁: "S'il n'y avait pas de fer à ce moment-là",
  倒也罢了: "Pas mal",
  如今手中既拿着他: "Maintenant le tenant dans ta main",
  身上无衣服相趁: "Pas de vêtements sur votre corps",
  奈何: "Comment",
  你这里若有披挂: "Si vous avez un accrochage ici",
  索性送我一件: "Donnez-moi un",
  一总奉谢: "Merci",
  龙王道: "Dragon King's Way",
  这个却是没有: "Mais ce n'est pas",
  悟空道: "Wukong Tao",
  一客不犯二主: "Un invité n'offensera pas deux maîtres",
  若没有: "Sinon",
  我也定不出此门: "Je ne peux pas le faire non plus",
  龙王道: "Dragon King's Way",
  烦上仙再转一海: "Je suis désolé que les Immortels tournent une autre mer",
  或者有之: "Ou certains",
  悟空又道: "Wukong a dit à nouveau",
  走三家不如坐一家:
    "Il vaut mieux s'asseoir à un seul endroit que de marcher trois",
  千万告求一件: "Je vais en demander un",
  龙王道: "Dragon King's Way",
  委的没有: "Non",
  如有即当奉承: "S'il y a quelque chose, veuillez le flatter",
  悟空道: "Wukong Tao",
  真个没有: "Vraiment non",
  就和你试试此铁: "Essayez juste ce fer avec toi",
  龙王慌了道: "Le roi du dragon a dit en panique",
  上仙: "L'immortel",
  切莫动手: "Ne fais pas ça",
  切莫动手: "Ne fais pas ça",
  待我看舍弟处可有: "Je vais voir si la place de mon frère est là",
  当送一副: "En donner un",
  悟空道: "Wukong Tao",
  令弟何在: "Où est Ling?",
  龙王道: "Dragon King's Way",
  舍弟乃南海龙王敖钦:
    "Mon frère cadet est Ao Qin, le roi dragon de la mer de Chine méridionale",
  北海龙王敖顺: "Le roi du dragon de la mer du Nord ao shun",
  西海龙王敖闰是也: "Le roi dragon de la mer Ouest est aussi",
  悟空道: "Wukong Tao",
  我老孙不去: "Mon vieux petit-fils n'ira pas",
  不去: "Ne va pas",
  俗语谓赊三不敌见二:
    'Comme le dit le dicton, "le crédit trois n\'est pas la même chose que de voir deux"',
  只望你随高就低的送一副便了:
    "J'espère juste que tu me donneras une paire comme tu veux",
  老龙道: "Vieux dragon",
  不须上仙去: "Pas besoin d'aller à l'immortel",
  我这里有一面铁鼓: "J'ai un tambour de fer ici",
  一口金钟: "Une cloche dorée",
  凡有紧急事: "Toute question urgente",
  擂得鼓响: "Le tambour bat",
  撞得钟鸣: "La cloche sonne",
  舍弟们就顷刻而至: "Mes frères sont arrivés en un instant",
  悟空道: "Wukong Tao",
  既是如此: "Puisque c'est le cas",
  快些去擂鼓撞钟: "Allez battre le tambour et frappez rapidement la cloche",
  真个那鼍将便去撞钟: "Cette tortue a frappé la cloche",
  鳖帅即来擂鼓: "L'entraîneur des tortues vient battre les tambours",
  5: "5",
  少时: "Plusieurs fois",
  钟鼓响处: "Où la cloche et les tambours sont",
  果然惊动那三海龙王: "Effectivement, le roi dragon des trois mers",
  须臾来到: "Venir dans un instant",
  一齐在外面会着: "Se rencontrer à l'extérieur ensemble",
  敖钦道: "AO Qindao",
  大哥: "Grand frère",
  有甚紧事: "Quelque chose est si important",
  擂鼓撞钟: "Battre le tambour et frapper la cloche",
  老龙道: "Vieux dragon",
  贤弟: "Frère",
  不好说: "Pas facile à dire",
  有一个花果山甚么天生圣人:
    "Il y a une montagne Huaguo, qu'est-ce qu'un saint naturel",
  早间来认我做邻居: "Venez me reconnaître comme votre voisin le matin",
  后来要求一件兵器: "Plus tard, une arme a été demandée",
  献钢叉嫌小: "La fourche en acier est petite",
  奉画戟嫌轻: "La peinture Halleber est légère",
  将一块天河定底神珍铁: "Un morceau de fer divin qui dérange le bas du ciel",
  自己拿出手: "Sortez-le vous-même",
  丢了些解数: "Perdu certaines solutions",
  如今坐在宫中: "Assis dans le palais maintenant",
  又要索甚么披挂: "Quels autres accrochages allez-vous demander?",
  我处无有: "Je n'ai rien",
  故响钟鸣鼓: "Par conséquent, les cloches et les tambours sonnent",
  请贤弟来: "Venez ici par mon cher frère",
  你们可有甚么披挂: "Quel genre de suspension avez-vous",
  送他一副: "Donnez-lui une paire",
  打发出门去罢了: "Envoyez-le",
  敖钦闻言: "Ao qin entendu",
  大怒道: "Dit furieusement",
  我兄弟们: "Mes frères",
  点起兵: "Démarrer les troupes",
  拿他不是: "Ne le prenant pas",
  老龙道: "Vieux dragon",
  莫说拿: "Ne dis pas prendre",
  那块铁: "Ce fer",
  挽着些儿就死: "Si vous le tenez un peu, vous mourrez",
  磕着些儿就亡: "Frapper un peu",
  挨挨皮儿破: "Aller à la peau",
  擦擦儿筋伤: "Frotter la blessure au tendon",
  西海龙王敖闰说: "Le roi dragon de la mer de la mer Ouest a dit",
  二哥不可与他动手: "Le deuxième frère ne peut pas le combattre",
  且只凑副披挂与他: "Et seulement la paire de robes et lui",
  打发他出了门: "Envoyez-le hors de la porte",
  启表奏上上天: "Révéler la mélodie du ciel",
  天自诛也: "Dieu vous tuera",
  北海龙王敖顺道: "King du dragon de la mer du Nord Ao Shundao",
  说的是: "Ce que je veux dire",
  我这里有一双藕丝步云履哩:
    "J'ai une paire de nuages ​​coupés de soie Lotus ici",
  西海龙王敖闰道: "Le roi dragon de la mer Ouest Ao Rundao",
  我带了一副锁子黄金甲哩:
    "J'ai apporté une paire d'armures d'or avec des serrures",
  南海龙王敖钦道: "Ao Qindao, le roi dragon de la mer de Chine méridionale",
  我有一顶凤翅紫金冠哩:
    "J'ai une couronne en or violet avec des ailes de phénix",
  老龙大喜: "Le vieux dragon est très heureux",
  引入水晶宫相见了: "Présenter Crystal Palace pour se rencontrer",
  以此奉上: "Offrir ceci",
  悟空将金冠: "Wukong prend la couronne d'or",
  金甲: "Armure dorée",
  云履那穿戴停当: "Le pansement de Yunlu s'arrête",
  使动如意棒: "Faites les meilleurs voeux",
  一路打出去: "Essayez-le tout le chemin",
  对众龙道: "Les dragons",
  聒噪: "Bruyant",
  吵闹: "bruyant",
  打搅: "déranger",
  聒噪: "Bruyant",
  四海龙王甚是不平: "Le roi dragon des quatre mers est très injuste",
  一边商议进表上奏不题:
    "Tout en discutant du rapport, aucune question ne sera donnée",
};



const synth = window.speechSynthesis;
let utterance = null;

// 状态跟踪
const charStates = {};

// 页面加载完成后初始化
document.addEventListener("DOMContentLoaded", function () {
  renderPoem();
});

// 渲染诗歌
function renderPoem() {
  const poemContainer = document.getElementById("poemContainer");
  const lines = poemText.split("\n");

  lines.forEach((line) => {
    const lineDiv = document.createElement("div");
    lineDiv.className = "poem-line";

    // 处理每个字符
    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      // 跳过空格
      if (char.trim() === "") {
        const spaceSpan = document.createElement("span");
        spaceSpan.textContent = " ";
        lineDiv.appendChild(spaceSpan);
        continue;
      }

      // 创建字符容器
      const charContainer = document.createElement("div");
      charContainer.className = "char-container";

      // 创建字符显示
      const charSpan = document.createElement("span");
      charSpan.className = "char";
      charSpan.textContent = char;

      // 创建拼音显示
      const pinyinSpan = document.createElement("span");
      pinyinSpan.className = "pinyin";

      // 创建翻译显示
      const transSpan = document.createElement("span");
      transSpan.className = "translation";

      // 添加到容器
      charContainer.appendChild(pinyinSpan);
      charContainer.appendChild(charSpan);
      charContainer.appendChild(transSpan);

      // 添加点击事件
      charContainer.addEventListener("click", () =>
        handleCharClick(char, pinyinSpan, transSpan)
      );

      // 添加到行
      lineDiv.appendChild(charContainer);
    }

    // 添加行控制按钮
    const controlsDiv = document.createElement("div");
    controlsDiv.className = "line-controls";

    const readBtn = document.createElement("button");
    readBtn.textContent = "朗读";
    readBtn.addEventListener("click", () => readLine(line));

    const transBtn = document.createElement("button");
    transBtn.textContent = "翻译";
    transBtn.addEventListener("click", () => showLineTranslation(line));

    controlsDiv.appendChild(readBtn);
    controlsDiv.appendChild(transBtn);
    lineDiv.appendChild(controlsDiv);

    // 添加到容器
    poemContainer.appendChild(lineDiv);
  });
}

// 处理字符点击
function handleCharClick(char, pinyinSpan, transSpan) {
  const charId = `${char}-${pinyinSpan.id}`; // 创建唯一标识

  // 初始化状态
  if (!charStates[charId]) {
    charStates[charId] = 0;
  }

  // 更新状态
  charStates[charId]++;
  if (charStates[charId] > 3) {
    charStates[charId] = 1;
  }

  // 根据状态执行操作
  switch (charStates[charId]) {
    case 1: // 朗读字符
      readChar(char);
      updateStatus(`朗读字符: ${char}`);
      break;
    case 2: // 显示拼音
      showPinyin(char, pinyinSpan);
      updateStatus(`显示拼音: ${char}`);
      break;
    case 3: // 显示翻译
      showTranslation(char, transSpan);
      updateStatus(`显示翻译: ${char}`);
      break;
  }
}

// 显示拼音
function showPinyin(char, pinyinSpan) {
  // 这里应该调用拼音库，简化处理

  const py = pinyinMap[char] || "?";
  pinyinSpan.textContent = py;
  pinyinSpan.style.display = "block";

  // 3秒后自动隐藏
  setTimeout(() => {
    pinyinSpan.style.display = "none";
    // 重置状态以便下次点击
    const charId = `${char}-${pinyinSpan.id}`;
    charStates[charId] = 0;
  }, 8000);
}

// 朗读字符
function readChar(char) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(char);
  utterance.lang = "zh-CN";
  utterance.rate = 0.7; // 设置为正常速度的70%
  synth.speak(utterance);
}

// 显示翻译
function showTranslation(char, transSpan) {
  const lang = document.getElementById("languageSelect").value;

  const translationCard = document.getElementById("translationCard");

  const translateMap = {
    de: translations_de[char] || "Keine Übersetzung",
    fr: translations_fr[char] || "Pas de traduction",
    en: translations_en[char] || "No translation",
  };
  const translate = translateMap[lang];
  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">汉字：</div>
    <div class="info-content">${char}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translate}</div>
  </div>
`;

  translationCard.style.display = "block";

  const charId = `${char}-${transSpan.id}`;
  charStates[charId] = 0;
}

function closeTranslationCard() {
  const translationCard = document.getElementById("translationCard");
  translationCard.style.display = "none";
}

// 朗读整行
function readLine(line) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(line);
  utterance.lang = "zh-CN";
  utterance.rate = 0.6; // 设置为正常速度的60%，更慢一些
  synth.speak(utterance);

  updateStatus(`朗读: ${line}`);
}

function showLineTranslation(line) {
  const lang = document.getElementById("languageSelect").value;
  const translatedMap = {
    de: tianwen_translation_map_de,
    fr: tianwen_translation_map_fr,
    en: tianwen_translation_map_en,
  };
  const translatedLine =
    translatedMap[lang]?.[line] || "（keine Übersetzung gefunden）";
  const translationCard = document.getElementById("translationCard");

  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">原文：</div>
    <div class="info-content">${line}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translatedLine}</div>
  </div>
`;

  translationCard.style.display = "block";

  updateStatus(`显示翻译: ${line.substring(0, 15)}...`);
}

// 更新状态栏
function updateStatus(message) {
  document.getElementById("statusBar").textContent = message;
}
