const translationCard = document.getElementById("translationCard");
// 诗歌文本c
const poemText = `你看这猴王
分开水道
径回铁板桥头
撺将上去
只见四个老猴
领着众猴
都在桥边等候
忽然见悟空跳出波外
身上更无一点水湿
金灿灿的
走上桥来
唬得众猴一齐跪下道
大王
好华彩耶
好华彩耶
悟空满面春风
高登宝座
将铁棒竖在当中
那些猴不知好歹
都来拿那宝贝
却便似蜻蜓撼铁树
分毫也不能禁动
一个个咬指伸舌道
爷爷呀
这般重
亏你怎的拿来也
悟空近前
舒开手一把挝起
对众笑道
物各有主
这宝贝镇于海藏中
也不知几千百年
可可的今岁放光
龙王只认做是块黑铁
又唤做天河镇底神珍
那厮每都扛抬不动
请我亲去拿之
那时此宝有二丈多长
斗来粗细
被我挝他一把
意思嫌大
他就小了许多
再教小些
他又小了许多
再教小些
他又小了许多
急对天光看处
上有一行字
乃如意金箍棒
一万三千五百斤
你都站开
等我再叫他变一变着
他将那宝贝颠在手中
叫
小小小
即时就小做一个绣花针儿相似
可以揌在耳朵里面藏下
众猴骇然
叫道
大王
还拿出来耍耍
猴王真个去耳朵里拿出
托放掌上叫
大大大
即又大做斗来粗细
二丈长短
他弄到欢喜处
跳上桥
走出洞外
将宝贝攥在手中
做一个法天象地的神通
把腰一躬
叫声长
他就长的高万丈
头如泰山
腰如峻岭
眼如闪电
口似血盆
牙如剑戟
手中那棒
上抵三十三天
下至十八层地狱
把些虎豹狼虫
满山群怪
七十二洞妖王
都唬得磕头礼拜
战兢兢魄散魂飞
霎时收了法像
将宝贝还变做个绣花针儿
藏在耳内
复归洞府
慌得那各洞妖王
都来参贺
此时遂大开旗鼓
响振铜锣
广设珍馐百味
满斟椰液萄浆
与众饮宴多时
却又依前教演
猴王将那四个老猴封为健将
将两个赤尻马猴唤做马流二元帅
两个通背猿猴唤做崩芭二将军
将那安营下寨
赏罚诸事
都付与四键将维持
他放下心
日逐腾云驾雾
遨游四海
行乐千山
施武艺
遍访英豪
弄神通
广交贤友
此时又会了个七弟兄
乃牛魔王
蛟魔王
鹏魔王
狮驼王
猕猴王
犭禺狨王
连自家美猴王七个
日逐讲文论武
走斝传觞
弦歌吹舞
朝去暮回
无般儿不乐
把那个万里之遥
只当庭闱之路
所谓点头径过三千里
扭腰八百有馀程
一日
在本洞吩咐四健将安排筵宴
请六王赴饮
杀牛宰马
祭天享地
着众怪跳舞欢歌
俱吃得酩酊大醉
送六王出去
却又赏劳大小头目
在铁板桥边松阴之下
霎时间睡着
四健将领众围护
不敢高声`;

const pinyinMap = {
  你: "nǐ",
  看: "kàn",
  这: "zhè",
  猴: "hóu",
  王: "wáng",
  分: "fēn",
  开: "kāi",
  水: "shuǐ",
  道: "dào",
  径: "jìng",
  回: "huí",
  铁: "tiě",
  板: "bǎn",
  桥: "qiáo",
  头: "tóu",
  撺: "cuān",
  将: "jiāng",
  上: "shǎng",
  去: "qù",
  只: "zhī",
  见: "jiàn",
  四: "sì",
  个: "gè",
  老: "lǎo",
  领: "lǐng",
  着: "zhe",
  众: "zhòng",
  都: "dōu",
  在: "zài",
  边: "biān",
  等: "děng",
  候: "hòu",
  忽: "hū",
  然: "rán",
  悟: "wù",
  空: "kōng",
  跳: "tiào",
  出: "chū",
  波: "bō",
  外: "wài",
  身: "shēn",
  更: "gèng",
  无: "wú",
  一: "yì",
  点: "diǎn",
  湿: "shī",
  金: "jīn",
  灿: "càn",
  的: "de",
  走: "zǒu",
  来: "lái",
  唬: "hǔ",
  得: "dé",
  齐: "qí",
  跪: "guì",
  下: "xià",
  大: "dà",
  好: "hǎo",
  华: "huá",
  彩: "cǎi",
  耶: "yé",
  满: "mǎn",
  面: "miàn",
  春: "chūn",
  风: "fēng",
  高: "gāo",
  登: "dēng",
  宝: "bǎo",
  座: "zuò",
  棒: "bàng",
  竖: "shù",
  当: "dāng",
  中: "zhōng",
  那: "nà",
  些: "xiē",
  不: "bù",
  知: "zhī",
  歹: "dǎi",
  拿: "ná",
  贝: "bèi",
  却: "què",
  便: "biàn",
  似: "shì",
  蜻: "qīng",
  蜓: "tíng",
  撼: "hàn",
  树: "shù",
  毫: "háo",
  也: "yě",
  能: "néng",
  禁: "jìn",
  动: "dòng",
  咬: "yǎo",
  指: "zhǐ",
  伸: "shēn",
  舌: "shé",
  爷: "yé",
  呀: "ya",
  般: "bān",
  重: "zhòng",
  亏: "kuī",
  怎: "zěn",
  近: "jìn",
  前: "qián",
  舒: "shū",
  手: "shǒu",
  把: "bǎ",
  挝: "wō",
  起: "qǐ",
  对: "duì",
  笑: "xiào",
  物: "wù",
  各: "gè",
  有: "yǒu",
  主: "zhǔ",
  镇: "zhèn",
  于: "yú",
  海: "hǎi",
  藏: "cáng",
  几: "jǐ",
  千: "qiān",
  百: "bǎi",
  年: "nián",
  可: "kě",
  今: "jīn",
  岁: "suì",
  放: "fàng",
  光: "guāng",
  龙: "lóng",
  认: "rèn",
  做: "zuò",
  是: "shì",
  块: "kuài",
  黑: "hēi",
  又: "yòu",
  唤: "huàn",
  天: "tiān",
  河: "hé",
  底: "dǐ",
  神: "shén",
  珍: "zhēn",
  厮: "sī",
  每: "měi",
  扛: "káng",
  抬: "tái",
  请: "qǐng",
  我: "wǒ",
  亲: "qīn",
  之: "zhī",
  时: "shí",
  此: "cǐ",
  二: "èr",
  丈: "zhàng",
  多: "duō",
  长: "zhǎng",
  斗: "dòu",
  粗: "cū",
  细: "xì",
  被: "bèi",
  他: "tā",
  意: "yì",
  思: "sī",
  嫌: "xián",
  就: "jiù",
  小: "xiǎo",
  了: "le",
  许: "xǔ",
  再: "zài",
  教: "jiào",
  急: "jí",
  处: "chù",
  行: "xíng",
  字: "zì",
  乃: "nǎi",
  如: "rú",
  箍: "gū",
  万: "wàn",
  三: "sān",
  五: "wǔ",
  斤: "jīn",
  站: "zhàn",
  叫: "jiào",
  变: "biàn",
  颠: "diān",
  即: "jí",
  绣: "xiù",
  花: "huā",
  针: "zhēn",
  儿: "ér",
  相: "xiāng",
  以: "yǐ",
  揌: "sāi",
  耳: "ěr",
  朵: "duǒ",
  里: "lǐ",
  骇: "hài",
  还: "hái",
  耍: "shuǎ",
  真: "zhēn",
  托: "tuō",
  掌: "zhǎng",
  短: "duǎn",
  弄: "nòng",
  到: "dào",
  欢: "huān",
  喜: "xǐ",
  洞: "dòng",
  攥: "zuàn",
  法: "fǎ",
  象: "xiàng",
  地: "dì",
  通: "tōng",
  腰: "yāo",
  躬: "gōng",
  声: "shēng",
  泰: "tài",
  山: "shān",
  峻: "jùn",
  岭: "lǐng",
  眼: "yǎn",
  闪: "shǎn",
  电: "diàn",
  口: "kǒu",
  血: "xuè",
  盆: "pén",
  牙: "yá",
  剑: "jiàn",
  戟: "jǐ",
  抵: "dǐ",
  十: "shí",
  至: "zhì",
  八: "bā",
  层: "céng",
  狱: "yù",
  虎: "hǔ",
  豹: "bào",
  狼: "láng",
  虫: "chóng",
  群: "qún",
  怪: "guài",
  七: "qī",
  妖: "yāo",
  磕: "kē",
  礼: "lǐ",
  拜: "bài",
  战: "zhàn",
  兢: "jīng",
  魄: "pò",
  散: "sàn",
  魂: "hún",
  飞: "fēi",
  霎: "shà",
  收: "shōu",
  像: "xiàng",
  内: "nèi",
  复: "fù",
  归: "guī",
  府: "fǔ",
  慌: "huāng",
  参: "cān",
  贺: "hè",
  遂: "suì",
  旗: "qí",
  鼓: "gǔ",
  响: "xiǎng",
  振: "zhèn",
  铜: "tóng",
  锣: "luó",
  广: "guǎng",
  设: "shè",
  馐: "xiū",
  味: "wèi",
  斟: "zhēn",
  椰: "yē",
  液: "yè",
  萄: "táo",
  浆: "jiāng",
  与: "yǔ",
  饮: "yǐn",
  宴: "yàn",
  依: "yī",
  演: "yǎn",
  封: "fēng",
  为: "wèi",
  健: "jiàn",
  两: "liǎng",
  赤: "chì",
  尻: "kāo",
  马: "mǎ",
  流: "liú",
  元: "yuán",
  帅: "shuài",
  背: "bèi",
  猿: "yuán",
  崩: "bēng",
  芭: "bā",
  军: "jūn",
  安: "ān",
  营: "yíng",
  寨: "zhài",
  赏: "shǎng",
  罚: "fá",
  诸: "zhū",
  事: "shì",
  付: "fù",
  键: "jiàn",
  维: "wéi",
  持: "chí",
  心: "xīn",
  日: "rì",
  逐: "zhú",
  腾: "téng",
  云: "yún",
  驾: "jià",
  雾: "wù",
  遨: "áo",
  游: "yóu",
  乐: "lè",
  施: "shī",
  武: "wǔ",
  艺: "yì",
  遍: "biàn",
  访: "fǎng",
  英: "yīng",
  豪: "háo",
  交: "jiāo",
  贤: "xián",
  友: "yǒu",
  会: "huì",
  弟: "dì",
  兄: "xiōng",
  牛: "niú",
  魔: "mó",
  蛟: "jiāo",
  鹏: "péng",
  狮: "shī",
  驼: "tuó",
  猕: "mí",
  犭: "quǎn",
  禺: "yú",
  狨: "róng",
  连: "lián",
  自: "zì",
  家: "jiā",
  美: "měi",
  讲: "jiǎng",
  文: "wén",
  论: "lùn",
  斝: "jiǎ",
  传: "chuán",
  觞: "shāng",
  弦: "xián",
  歌: "gē",
  吹: "chuī",
  舞: "wǔ",
  朝: "zhāo",
  暮: "mù",
  遥: "yáo",
  庭: "tíng",
  闱: "wéi",
  路: "lù",
  所: "suǒ",
  谓: "wèi",
  过: "guò",
  扭: "niǔ",
  馀: "yú",
  程: "chéng",
  本: "běn",
  吩: "fēn",
  咐: "fù",
  排: "pái",
  筵: "yán",
  六: "liù",
  赴: "fù",
  杀: "shā",
  宰: "zǎi",
  祭: "jì",
  享: "xiǎng",
  俱: "jù",
  吃: "chī",
  酩: "mǐng",
  酊: "dǐng",
  醉: "zuì",
  送: "sòng",
  劳: "láo",
  目: "mù",
  松: "sōng",
  阴: "yīn",
  间: "jiān",
  睡: "shuì",
  围: "wéi",
  护: "hù",
  敢: "gǎn",
};

const translations_en = {
  你: "you",
  看: "look",
  这: "this",
  猴: "monkey",
  王: "king",
  分: "point",
  开: "open",
  水: "water",
  道: "road",
  径: "path",
  回: "Back",
  铁: "iron",
  板: "plate",
  桥: "bridge",
  头: "head",
  撺: "throw",
  将: "Will",
  上: "superior",
  去: "go",
  只: "Only",
  见: "See",
  四: "Four",
  个: "indivual",
  老: "old",
  领: "collar",
  着: "Put",
  众: "All",
  都: "All",
  在: "exist",
  边: "side",
  等: "wait",
  候: "Wait",
  忽: "suddenly",
  然: "Of course",
  悟: "Enlightenment",
  空: "null",
  跳: "Jump",
  出: "out",
  波: "Wave",
  外: "outside",
  身: "body",
  更: "Even",
  无: "none",
  一: "one",
  点: "point",
  湿: "wet",
  金: "gold",
  灿: "Can",
  的: "of",
  走: "Walk",
  来: "Come",
  唬: "fool",
  得: "have to",
  齐: "together",
  跪: "kneel",
  下: "Down",
  大: "big",
  好: "good",
  华: "magnificent",
  彩: "color",
  耶: "yeah",
  满: "Full",
  面: "noodle",
  春: "spring",
  风: "wind",
  高: "high",
  登: "Login",
  宝: "precious",
  座: "seat",
  棒: "Great",
  竖: "vertical",
  当: "when",
  中: "middle",
  那: "That",
  些: "some",
  不: "No",
  知: "Know",
  歹: "bad",
  拿: "take",
  贝: "cowry",
  却: "but",
  便: "Hope",
  似: "like",
  蜻: "dragonfly",
  蜓: "dragonfly",
  撼: "shake",
  树: "Tree",
  毫: "海海",
  也: "also",
  能: "able",
  禁: "ban",
  动: "move",
  咬: "bite",
  指: "refer to",
  伸: "stretch",
  舌: "tongue",
  爷: "Grandpa",
  呀: "ah",
  般: "Normal",
  重: "Heavy",
  亏: "deficit",
  怎: "How",
  近: "close",
  前: "forward",
  舒: "Sweet",
  手: "hand",
  把: "Bundle",
  挝: "Os",
  起: "rise",
  对: "right",
  笑: "laugh",
  物: "Things",
  各: "each",
  有: "have",
  主: "host",
  镇: "town",
  于: "At",
  海: "ocean",
  藏: "Tibetan",
  几: "Several",
  千: "thousand",
  百: "Hundred",
  年: "Year",
  可: "Can",
  今: "now",
  岁: "age",
  放: "put",
  光: "Light",
  龙: "dragon",
  认: "recognize",
  做: "Do",
  是: "yes",
  块: "piece",
  黑: "black",
  又: "again",
  唤: "Call",
  天: "sky",
  河: "river",
  底: "end",
  神: "god",
  珍: "Jen",
  厮: "Friend",
  每: "Every",
  扛: "Carry",
  抬: "lift",
  请: "please",
  我: "I",
  亲: "relative",
  之: "Of",
  时: "hour",
  此: "this",
  二: "two",
  丈: "ten feet",
  多: "many",
  长: "long",
  斗: "fight",
  粗: "thick",
  细: "thin",
  被: "quilt",
  他: "he",
  意: "meaning",
  思: "think",
  嫌: "Dislike",
  就: "At once",
  小: "Small",
  了: "It's",
  许: "May",
  再: "Again",
  教: "teach",
  急: "urgent",
  处: "Where",
  行: "OK",
  字: "Character",
  乃: "So",
  如: "like",
  箍: "hoop",
  万: "Ten thousand",
  三: "three",
  五: "five",
  斤: "catty",
  站: "stand",
  叫: "Call",
  变: "Change",
  颠: "Far",
  即: "Right now",
  绣: "Embroidery",
  花: "flower",
  针: "Needle",
  儿: "Son",
  相: "Mutually",
  以: "by",
  揌: "Stop",
  耳: "Ear",
  朵: "Duo",
  里: "inside",
  骇: "startle",
  还: "return",
  耍: "Play",
  真: "real",
  托: "Hope",
  掌: "Palm",
  短: "short",
  弄: "alley",
  到: "arrive",
  欢: "joyous",
  喜: "happiness",
  洞: "Hole",
  攥: "Clench",
  法: "Law",
  象: "elephant",
  地: "land",
  通: "Pass",
  腰: "waist",
  躬: "bow",
  声: "Voice",
  泰: "Thai",
  山: "Mountain",
  峻: "Jun",
  岭: "ridge",
  眼: "Eye",
  闪: "flash",
  电: "electricity",
  口: "mouth",
  血: "Blood",
  盆: "pot",
  牙: "tooth",
  剑: "sword",
  戟: "halberd",
  抵: "Arrive",
  十: "ten",
  至: "to",
  八: "eight",
  层: "layer",
  狱: "prison",
  虎: "Tiger",
  豹: "Leopard",
  狼: "Wolf",
  虫: "insect",
  群: "group",
  怪: "Strange",
  七: "seven",
  妖: "Demon",
  磕: "knock",
  礼: "present",
  拜: "bye",
  战: "war",
  兢: "Virginity",
  魄: "soul",
  散: "Scattered",
  魂: "soul",
  飞: "fly",
  霎: "Suddenly",
  收: "receive",
  像: "picture",
  内: "Inside",
  复: "complex",
  归: "Go home",
  府: "House",
  慌: "Panic",
  参: "Ginseng",
  贺: "Congratulations",
  遂: "So",
  旗: "flag",
  鼓: "drum",
  响: "ring",
  振: "Vibrate",
  铜: "copper",
  锣: "gong",
  广: "wide",
  设: "set up",
  馐: "delicate",
  味: "taste",
  斟: "Pour",
  椰: "Coconut",
  液: "liquid",
  萄: "Grapes",
  浆: "Slurry",
  与: "and",
  饮: "drink",
  宴: "feast",
  依: "according to",
  演: "play",
  封: "seal up",
  为: "for",
  健: "Healthy",
  两: "two",
  赤: "red",
  尻: "Butt",
  马: "horse",
  流: "flow",
  元: "Yuan",
  帅: "handsome",
  背: "back",
  猿: "ape",
  崩: "collapse",
  芭: "Ba",
  军: "military",
  安: "install",
  营: "camp",
  寨: "Village",
  赏: "reward",
  罚: "Punishment",
  诸: "various",
  事: "thing",
  付: "pay",
  键: "key",
  维: "dimension",
  持: "hold",
  心: "Heart",
  日: "day",
  逐: "By",
  腾: "Teng",
  云: "cloud",
  驾: "drive",
  雾: "fog",
  遨: "excursion",
  游: "tour",
  乐: "happy",
  施: "Shi",
  武: "Wu",
  艺: "art",
  遍: "all over",
  访: "visit",
  英: "Britain",
  豪: "Hao",
  交: "pay",
  贤: "Virtue",
  友: "friend",
  会: "meeting",
  弟: "younger brother",
  兄: "Brother",
  牛: "ox",
  魔: "magic",
  蛟: "Jiao",
  鹏: "Peng",
  狮: "lion",
  驼: "camel",
  猕: "macaque",
  犭: "南",
  禺: "Yu",
  狨: "Craft",
  连: "even",
  自: "since",
  家: "Home",
  美: "beautiful",
  讲: "speak",
  文: "arts",
  论: "Argument",
  斝: "jade cup with ears",
  传: "pass",
  觞: "feast",
  弦: "string",
  歌: "Song",
  吹: "blow",
  舞: "dance",
  朝: "towards",
  暮: "twilight",
  遥: "remote",
  庭: "court",
  闱: "Examination",
  路: "road",
  所: "Place",
  谓: "Present",
  过: "Pass",
  扭: "Twist",
  馀: "Remaining",
  程: "Procedure",
  本: "Book",
  吩: "Poison",
  咐: "Instructions",
  排: "Row",
  筵: "feast",
  六: "six",
  赴: "go",
  杀: "kill",
  宰: "slaughter",
  祭: "Sacrifice",
  享: "Enjoy",
  俱: "all",
  吃: "eat",
  酩: "Moor",
  酊: "Tincture",
  醉: "drunk",
  送: "deliver",
  劳: "labor",
  目: "Meaning",
  松: "loose",
  阴: "Negative",
  间: "between",
  睡: "sleep",
  围: "Surrounding",
  护: "Protection",
  敢: "dare",
};

const translations_de = {
  你: "Du",
  看: "sehen",
  这: "Das",
  猴: "Affe",
  王: "König",
  分: "Punkt",
  开: "offen",
  水: "Wasser",
  道: "Straße",
  径: "Weg",
  回: "Zurück",
  铁: "Eisen",
  板: "Platte",
  桥: "Brücke",
  头: "Kopf",
  撺: "werfen",
  将: "Wille",
  上: "Vorgesetzter",
  去: "gehen",
  只: "Nur",
  见: "Sehen",
  四: "Vier",
  个: "indival",
  老: "alt",
  领: "Kragen",
  着: "Setzen",
  众: "Alle",
  都: "Alle",
  在: "existieren",
  边: "Seite",
  等: "Warten",
  候: "Warten",
  忽: "plötzlich",
  然: "Natürlich",
  悟: "Aufklärung",
  空: "NULL",
  跳: "Springen",
  出: "aus",
  波: "Welle",
  外: "draußen",
  身: "Körper",
  更: "Sogar",
  无: "keiner",
  一: "eins",
  点: "Punkt",
  湿: "nass",
  金: "Gold",
  灿: "Kann",
  的: "von",
  走: "Gehen",
  来: "Kommen",
  唬: "Narr",
  得: "müssen",
  齐: "zusammen",
  跪: "knien",
  下: "Runter",
  大: "groß",
  好: "Gut",
  华: "herrlich",
  彩: "Farbe",
  耶: "Ja",
  满: "Voll",
  面: "Nudel",
  春: "Frühling",
  风: "Wind",
  高: "hoch",
  登: "Login",
  宝: "wertvoll",
  座: "Sitz",
  棒: "Großartig",
  竖: "Vertikale",
  当: "Wann",
  中: "Mitte",
  那: "Das",
  些: "manche",
  不: "NEIN",
  知: "Wissen",
  歹: "schlecht",
  拿: "nehmen",
  贝: "Cowry",
  却: "Aber",
  便: "Hoffnung",
  似: "wie",
  蜻: "Libelle",
  蜓: "Libelle",
  撼: "Shake",
  树: "Baum",
  毫: "海海",
  也: "Auch",
  能: "fähig",
  禁: "Verbot",
  动: "bewegen",
  咬: "beißen",
  指: "beziehen sich auf",
  伸: "strecken",
  舌: "Zunge",
  爷: "Opa",
  呀: "Ah",
  般: "Normal",
  重: "Schwer",
  亏: "Defizit",
  怎: "Wie",
  近: "schließen",
  前: "nach vorne",
  舒: "Süß",
  手: "Hand",
  把: "Bündeln",
  挝: "Betriebssystem",
  起: "erheben",
  对: "Rechts",
  笑: "lachen",
  物: "Dinge",
  各: "jede",
  有: "haben",
  主: "Gastgeber",
  镇: "Stadt",
  于: "Bei",
  海: "Ozean",
  藏: "Tibetaner",
  几: "Mehrere",
  千: "tausend",
  百: "Hundert",
  年: "Jahr",
  可: "Kann",
  今: "Jetzt",
  岁: "Alter",
  放: "setzen",
  光: "Licht",
  龙: "Drachen",
  认: "erkennen",
  做: "Tun",
  是: "Ja",
  块: "Stück",
  黑: "Schwarz",
  又: "wieder",
  唤: "Anruf",
  天: "Himmel",
  河: "Fluss",
  底: "Ende",
  神: "Gott",
  珍: "Jen",
  厮: "Freund",
  每: "Jeder",
  扛: "Tragen",
  抬: "Aufzug",
  请: "Bitte",
  我: "ICH",
  亲: "relativ",
  之: "Von",
  时: "Stunde",
  此: "Das",
  二: "zwei",
  丈: "zehn Fuß",
  多: "viele",
  长: "lang",
  斗: "kämpfen",
  粗: "dick",
  细: "dünn",
  被: "Decke",
  他: "Er",
  意: "Bedeutung",
  思: "denken",
  嫌: "Abneigung",
  就: "Auf einmal",
  小: "Klein",
  了: "Es ist",
  许: "Mai",
  再: "Wieder",
  教: "unterrichten",
  急: "dringend",
  处: "Wo",
  行: "OK",
  字: "Charakter",
  乃: "Also",
  如: "wie",
  箍: "Band",
  万: "Zehntausend",
  三: "drei",
  五: "fünf",
  斤: "katt",
  站: "Stand",
  叫: "Anruf",
  变: "Ändern",
  颠: "Weit",
  即: "Im Augenblick",
  绣: "Stickerei",
  花: "Blume",
  针: "Nadel",
  儿: "Sohn",
  相: "Gegenseitig",
  以: "von",
  揌: "Stoppen",
  耳: "Ohr",
  朵: "Duo",
  里: "innen",
  骇: "erschrecken",
  还: "zurückkehren",
  耍: "Spielen",
  真: "real",
  托: "Hoffnung",
  掌: "Palme",
  短: "kurz",
  弄: "Gasse",
  到: "ankommen",
  欢: "freudig",
  喜: "Glück",
  洞: "Loch",
  攥: "Ballen",
  法: "Gesetz",
  象: "Elefant",
  地: "Land",
  通: "Passieren",
  腰: "Taille",
  躬: "Bogen",
  声: "Stimme",
  泰: "Thai",
  山: "Berg",
  峻: "Jun",
  岭: "Grat",
  眼: "Auge",
  闪: "Blitz",
  电: "Strom",
  口: "Mund",
  血: "Blut",
  盆: "Pot",
  牙: "Zahn",
  剑: "Schwert",
  戟: "Hellebarde",
  抵: "Ankommen",
  十: "zehn",
  至: "Zu",
  八: "acht",
  层: "Schicht",
  狱: "Gefängnis",
  虎: "Tiger",
  豹: "Leopard",
  狼: "Wolf",
  虫: "Insekt",
  群: "Gruppe",
  怪: "Seltsam",
  七: "Sieben",
  妖: "Dämon",
  磕: "klopfen",
  礼: "gegenwärtig",
  拜: "Tschüss",
  战: "Krieg",
  兢: "Jungfräulichkeit",
  魄: "Seele",
  散: "Verstreut",
  魂: "Seele",
  飞: "fliegen",
  霎: "Plötzlich",
  收: "erhalten",
  像: "Bild",
  内: "Innen",
  复: "Komplex",
  归: "Nach Hause gehen",
  府: "Haus",
  慌: "Panik",
  参: "Ginseng",
  贺: "Glückwunsch",
  遂: "Also",
  旗: "Flagge",
  鼓: "Trommel",
  响: "Ring",
  振: "Vibrieren",
  铜: "Kupfer",
  锣: "Gong",
  广: "breit",
  设: "aufstellen",
  馐: "empfindlich",
  味: "schmecken",
  斟: "Gießen",
  椰: "Kokosnuss",
  液: "flüssig",
  萄: "Trauben",
  浆: "Aufschlämmung",
  与: "Und",
  饮: "trinken",
  宴: "Fest",
  依: "entsprechend",
  演: "spielen",
  封: "versiegeln",
  为: "für",
  健: "Gesund",
  两: "zwei",
  赤: "Rot",
  尻: "Hintern",
  马: "Pferd",
  流: "fließen",
  元: "Yuan",
  帅: "gutaussehend",
  背: "zurück",
  猿: "Affe",
  崩: "Zusammenbruch",
  芭: "Ba",
  军: "Militär",
  安: "installieren",
  营: "Lager",
  寨: "Dorf",
  赏: "belohnen",
  罚: "Bestrafung",
  诸: "verschieden",
  事: "Ding",
  付: "zahlen",
  键: "Schlüssel",
  维: "Dimension",
  持: "halten",
  心: "Herz",
  日: "Tag",
  逐: "Von",
  腾: "Teng",
  云: "Wolke",
  驾: "fahren",
  雾: "Nebel",
  遨: "Ausflug",
  游: "Tour",
  乐: "Glücklich",
  施: "Shi",
  武: "Wu",
  艺: "Kunst",
  遍: "Überall",
  访: "besuchen",
  英: "Großbritannien",
  豪: "Hao",
  交: "zahlen",
  贤: "Tugend",
  友: "Freund",
  会: "treffen",
  弟: "jüngerer Bruder",
  兄: "Bruder",
  牛: "Ochse",
  魔: "Magie",
  蛟: "Jiao",
  鹏: "Peng",
  狮: "Löwe",
  驼: "Kamel",
  猕: "Makaken",
  犭: "南",
  禺: "Yu",
  狨: "Handwerk",
  连: "sogar",
  自: "seit",
  家: "Heim",
  美: "Schön",
  讲: "sprechen",
  文: "Künste",
  论: "Argument",
  斝: "Jade Cup mit Ohren",
  传: "passieren",
  觞: "Fest",
  弦: "Saite",
  歌: "Lied",
  吹: "Schlag",
  舞: "tanzen",
  朝: "in Richtung",
  暮: "Dämmerung",
  遥: "Fernbedienung",
  庭: "Gericht",
  闱: "Prüfung",
  路: "Straße",
  所: "Ort",
  谓: "Gegenwärtig",
  过: "Passieren",
  扭: "Twist",
  馀: "Übrig",
  程: "Verfahren",
  本: "Buch",
  吩: "Gift",
  咐: "Anweisungen",
  排: "Reihe",
  筵: "Fest",
  六: "sechs",
  赴: "gehen",
  杀: "töten",
  宰: "schlachten",
  祭: "Opfern",
  享: "Genießen",
  俱: "alle",
  吃: "essen",
  酩: "Moor",
  酊: "Tinktur",
  醉: "betrunken",
  送: "liefern",
  劳: "Arbeit",
  目: "Bedeutung",
  松: "lose",
  阴: "Negativ",
  间: "zwischen",
  睡: "schlafen",
  围: "Umgeben",
  护: "Schutz",
  敢: "wagen",
};

const translations_fr = {
  你: "toi",
  看: "regarder",
  这: "ce",
  猴: "singe",
  王: "roi",
  分: "indiquer",
  开: "ouvrir",
  水: "eau",
  道: "route",
  径: "chemin",
  回: "Dos",
  铁: "fer",
  板: "plaque",
  桥: "pont",
  头: "tête",
  撺: "lancer",
  将: "Volonté",
  上: "supérieur",
  去: "aller",
  只: "Seulement",
  见: "Voir",
  四: "Quatre",
  个: "autonome",
  老: "vieux",
  领: "collier",
  着: "Mettre",
  众: "Tous",
  都: "Tous",
  在: "exister",
  边: "côté",
  等: "attendez",
  候: "Attendez",
  忽: "soudainement",
  然: "Bien sûr",
  悟: "Éclaircissement",
  空: "nul",
  跳: "Saut",
  出: "dehors",
  波: "Vague",
  外: "dehors",
  身: "corps",
  更: "Même",
  无: "aucun",
  一: "un",
  点: "indiquer",
  湿: "mouillé",
  金: "or",
  灿: "Peut",
  的: "de",
  走: "Marcher",
  来: "Viens",
  唬: "idiot",
  得: "devoir",
  齐: "ensemble",
  跪: "s'agenouiller",
  下: "Vers le bas",
  大: "grand",
  好: "bien",
  华: "magnifique",
  彩: "couleur",
  耶: "Ouais",
  满: "Complet",
  面: "nouille",
  春: "printemps",
  风: "vent",
  高: "haut",
  登: "Se connecter",
  宝: "précieux",
  座: "siège",
  棒: "Super",
  竖: "verticale",
  当: "quand",
  中: "milieu",
  那: "Que",
  些: "quelques",
  不: "Non",
  知: "Savoir",
  歹: "mauvais",
  拿: "prendre",
  贝: "bouc",
  却: "mais",
  便: "Espoir",
  似: "comme",
  蜻: "libellule",
  蜓: "libellule",
  撼: "secouer",
  树: "Arbre",
  毫: "海海",
  也: "aussi",
  能: "capable",
  禁: "interdire",
  动: "se déplacer",
  咬: "mordre",
  指: "se référer à",
  伸: "extensible",
  舌: "langue",
  爷: "Grand-père",
  呀: "ah",
  般: "Normale",
  重: "Lourd",
  亏: "déficit",
  怎: "Comment",
  近: "fermer",
  前: "avant",
  舒: "Doux",
  手: "main",
  把: "Paquet",
  挝: "OS",
  起: "augmenter",
  对: "droite",
  笑: "rire",
  物: "Des choses",
  各: "chaque",
  有: "avoir",
  主: "hôte",
  镇: "ville",
  于: "À",
  海: "océan",
  藏: "Tibétain",
  几: "Plusieurs",
  千: "mille",
  百: "Cent",
  年: "Année",
  可: "Peut",
  今: "maintenant",
  岁: "âge",
  放: "mettre",
  光: "Lumière",
  龙: "dragon",
  认: "reconnaître",
  做: "Faire",
  是: "Oui",
  块: "morceau",
  黑: "noir",
  又: "encore",
  唤: "Appel",
  天: "ciel",
  河: "rivière",
  底: "fin",
  神: "Dieu",
  珍: "Jen",
  厮: "Ami",
  每: "Chaque",
  扛: "Porter",
  抬: "ascenseur",
  请: "s'il te plaît",
  我: "je",
  亲: "relatif",
  之: "De",
  时: "heure",
  此: "ce",
  二: "deux",
  丈: "dix pieds",
  多: "beaucoup",
  长: "long",
  斗: "lutte",
  粗: "épais",
  细: "mince",
  被: "édredon",
  他: "il",
  意: "signification",
  思: "pense",
  嫌: "Aversion",
  就: "Immédiatement",
  小: "Petit",
  了: "C'est",
  许: "Peut",
  再: "Encore",
  教: "enseigner",
  急: "urgent",
  处: "Où",
  行: "D'ACCORD",
  字: "Personnage",
  乃: "Donc",
  如: "comme",
  箍: "cerceau",
  万: "Dix mille",
  三: "trois",
  五: "cinq",
  斤: "méchant",
  站: "rester",
  叫: "Appel",
  变: "Changement",
  颠: "Loin",
  即: "Tout de suite",
  绣: "Broderie",
  花: "fleur",
  针: "Aiguille",
  儿: "Fils",
  相: "Mutuellement",
  以: "par",
  揌: "Arrêt",
  耳: "Oreille",
  朵: "Duo",
  里: "à l'intérieur",
  骇: "surprendre",
  还: "retour",
  耍: "Jouer",
  真: "réel",
  托: "Espoir",
  掌: "Palmier",
  短: "court",
  弄: "ruelle",
  到: "arriver",
  欢: "joyeux",
  喜: "bonheur",
  洞: "Trou",
  攥: "Serrer",
  法: "Loi",
  象: "éléphant",
  地: "atterrir",
  通: "Passer",
  腰: "taille",
  躬: "arc",
  声: "Voix",
  泰: "thaïlandais",
  山: "Montagne",
  峻: "Juin",
  岭: "crête",
  眼: "Œil",
  闪: "éclair",
  电: "électricité",
  口: "bouche",
  血: "Sang",
  盆: "pot",
  牙: "dent",
  剑: "épée",
  戟: "hallebarde",
  抵: "Arriver",
  十: "dix",
  至: "à",
  八: "huit",
  层: "couche",
  狱: "prison",
  虎: "Tigre",
  豹: "Léopard",
  狼: "Loup",
  虫: "insecte",
  群: "groupe",
  怪: "Étrange",
  七: "Sept",
  妖: "Démon",
  磕: "frappe",
  礼: "présent",
  拜: "au revoir",
  战: "guerre",
  兢: "Virginité",
  魄: "âme",
  散: "Dispersé",
  魂: "âme",
  飞: "voler",
  霎: "Soudainement",
  收: "recevoir",
  像: "image",
  内: "À l'intérieur",
  复: "complexe",
  归: "Rentrer chez eux",
  府: "Maison",
  慌: "Panique",
  参: "Ginseng",
  贺: "Félicitations",
  遂: "Donc",
  旗: "drapeau",
  鼓: "tambour",
  响: "anneau",
  振: "Vibrer",
  铜: "cuivre",
  锣: "gong",
  广: "large",
  设: "installation",
  馐: "délicat",
  味: "goût",
  斟: "Verser",
  椰: "Noix de coco",
  液: "liquide",
  萄: "Raisins",
  浆: "Boue",
  与: "et",
  饮: "boire",
  宴: "festin",
  依: "selon",
  演: "jouer",
  封: "sceller",
  为: "pour",
  健: "En bonne santé",
  两: "deux",
  赤: "rouge",
  尻: "Bout",
  马: "cheval",
  流: "couler",
  元: "Yuan",
  帅: "beau",
  背: "dos",
  猿: "singe",
  崩: "effondrement",
  芭: "Ba",
  军: "militaire",
  安: "installer",
  营: "camp",
  寨: "Village",
  赏: "récompense",
  罚: "Punition",
  诸: "divers",
  事: "chose",
  付: "payer",
  键: "clé",
  维: "dimension",
  持: "prise",
  心: "Cœur",
  日: "jour",
  逐: "Par",
  腾: "Tendre",
  云: "nuage",
  驾: "conduire",
  雾: "brouillard",
  遨: "excursion",
  游: "tournée",
  乐: "heureux",
  施: "Shi",
  武: "Wu",
  艺: "art",
  遍: "partout",
  访: "visite",
  英: "Grande-Bretagne",
  豪: "Hao",
  交: "payer",
  贤: "Vertu",
  友: "ami",
  会: "réunion",
  弟: "jeune frère",
  兄: "Frère",
  牛: "bœuf",
  魔: "magie",
  蛟: "Jiao",
  鹏: "Tamiser",
  狮: "lion",
  驼: "chameau",
  猕: "macaque",
  犭: "南",
  禺: "Yu",
  狨: "Artisanat",
  连: "même",
  自: "depuis",
  家: "Maison",
  美: "beau",
  讲: "parler",
  文: "arts",
  论: "Argument",
  斝: "tasse de jade avec oreilles",
  传: "passer",
  觞: "festin",
  弦: "chaîne",
  歌: "Chanson",
  吹: "souffler",
  舞: "danse",
  朝: "vers",
  暮: "crépuscule",
  遥: "télécommande",
  庭: "tribunal",
  闱: "Examen",
  路: "route",
  所: "Lieu",
  谓: "Présent",
  过: "Passer",
  扭: "Torsion",
  馀: "Restant",
  程: "Procédure",
  本: "Livre",
  吩: "Poison",
  咐: "Instructions",
  排: "Rangée",
  筵: "festin",
  六: "six",
  赴: "aller",
  杀: "tuer",
  宰: "abattage",
  祭: "Sacrifier",
  享: "Apprécier",
  俱: "tous",
  吃: "manger",
  酩: "Amarrer",
  酊: "Teinture",
  醉: "ivre",
  送: "livrer",
  劳: "travail",
  目: "Signification",
  松: "lâche",
  阴: "Négatif",
  间: "entre",
  睡: "dormir",
  围: "Environnant",
  护: "Protection",
  敢: "oser",
};

const tianwen_translation_map_en = {
  你看这猴王: "Look at this monkey king",
  分开水道: "Divide the waterway",
  径回铁板桥头: "Go back to the iron bridge head",
  撺将上去: "Go up",
  只见四个老猴: "Only four old monkeys",
  领着众猴: "Lead the monkeys",
  都在桥边等候: "All waiting by the bridge",
  忽然见悟空跳出波外: "Suddenly, Wukong jumped out of the wave",
  身上更无一点水湿: "There is no moisture on the body",
  金灿灿的: "Golden",
  走上桥来: "Come on the bridge",
  唬得众猴一齐跪下道:
    "The monkeys were so scared that they knelt down and said",
  大王: "The King",
  好华彩耶: "Very colorful",
  好华彩耶: "Very colorful",
  悟空满面春风: "Wukong is covered in spring breeze",
  高登宝座: "Gordon throne",
  将铁棒竖在当中: "Put the iron rod in it",
  那些猴不知好歹: "Those monkeys don't know what's good",
  都来拿那宝贝: "Come and get that treasure",
  却便似蜻蜓撼铁树: "But it's like a dragonfly shaking an iron tree",
  分毫也不能禁动: "Can't ban it at all",
  一个个咬指伸舌道:
    "One by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one",
  爷爷呀: "Grandpa",
  这般重: "So heavy",
  亏你怎的拿来也: "Why did you bring it?",
  悟空近前: "Wukong is approaching",
  舒开手一把挝起: "Let go of your hands",
  对众笑道: "Smile to everyone",
  物各有主: "Each thing has its own master",
  这宝贝镇于海藏中: "This treasure is in the sea treasury",
  也不知几千百年: "Not sure how many thousands of years",
  可可的今岁放光: "The Cocoa shines this year",
  龙王只认做是块黑铁:
    "The Dragon King only considers it to be a piece of black iron",
  又唤做天河镇底神珍:
    "Also called the God of Heavenly Treasures in the bottom of Tianhe Town",
  那厮每都扛抬不动: "That guy never lifts it",
  请我亲去拿之: "Please ask me to get it in person",
  那时此宝有二丈多长: "At that time, this treasure was more than two feet long",
  斗来粗细: "The thickness of the bucket",
  被我挝他一把: "I've given him a hand",
  意思嫌大: "It's very meaningful",
  他就小了许多: "He's much smaller",
  再教小些: "Teach it a little bit smaller",
  他又小了许多: "He's much younger again",
  再教小些: "Teach it a little bit smaller",
  他又小了许多: "He's much younger again",
  急对天光看处: "Look at the sky light urgently",
  上有一行字: "There is a line of words on it",
  乃如意金箍棒: "Naruyi Golden Hoop",
  一万三千五百斤: "Ten thousand three thousand five hundred kilograms",
  你都站开: "You're standing",
  等我再叫他变一变着: "I'll tell him to change",
  他将那宝贝颠在手中: "He put the baby in his hand",
  叫: "Call",
  小小小: "Little little",
  即时就小做一个绣花针儿相似: "Just make an embroidery needle in real time.",
  可以揌在耳朵里面藏下: "Can be hidden in your ears",
  众猴骇然: "The monkeys were shocked",
  叫道: "Calling",
  大王: "The King",
  还拿出来耍耍: "And take it out to play",
  猴王真个去耳朵里拿出: "The Monkey King really took it out from his ear",
  托放掌上叫: "Put it on your palm and call",
  大大大: "Big big",
  即又大做斗来粗细: "It's a big hit to make the thickness",
  二丈长短: "Two feet long",
  他弄到欢喜处: "He got a happy place",
  跳上桥: "Jump onto the bridge",
  走出洞外: "Walk out of the cave",
  将宝贝攥在手中: "Hold the baby in your hand",
  做一个法天象地的神通: "Be a magical power to do the world",
  把腰一躬: "Bow your waist",
  叫声长: "Long scream",
  他就长的高万丈: "He's so tall",
  头如泰山: "Head like Mount Tai",
  腰如峻岭: "The waist is like a steep",
  眼如闪电: "Eyes like lightning",
  口似血盆: "The mouth is like a bloody basin",
  牙如剑戟: "Teeth like a sword",
  手中那棒: "That stick in hand",
  上抵三十三天: "Thirty-three days",
  下至十八层地狱: "Down to the eighteenth level of hell",
  把些虎豹狼虫: "Put some tiger, leopard, wolf insects",
  满山群怪: "Monsters all over the mountain",
  七十二洞妖王: "Seventy-two cave demon kings",
  都唬得磕头礼拜: "All are so scared that they kowtow to worship",
  战兢兢魄散魂飞: "Flying with fear",
  霎时收了法像: "I immediately collected the magic image",
  将宝贝还变做个绣花针儿: "Turn your baby into an embroidery needle",
  藏在耳内: "Hidden in the ears",
  复归洞府: "Return to the cave house",
  慌得那各洞妖王: "The demon kings of the caves were so panicked",
  都来参贺: "Come and congratulate",
  此时遂大开旗鼓: "At this time, the flags and drums were opened",
  响振铜锣: "The gong is vibrated",
  广设珍馐百味: "Set up a wide range of delicious foods",
  满斟椰液萄浆: "Pour coconut liquor",
  与众饮宴多时: "Have a long time to have a banquet",
  却又依前教演: "But he performed according to the previous teaching",
  猴王将那四个老猴封为健将:
    "The Monkey King named the four old monkeys as strong generals",
  将两个赤尻马猴唤做马流二元帅:
    "Call the two red-butt horse monkeys to be the second Marshal of Horses and Liushu",
  两个通背猿猴唤做崩芭二将军:
    "Two monkeys on the back are called the two generals of Bengba",
  将那安营下寨: "Let that camp",
  赏罚诸事: "Rewards and punishments",
  都付与四键将维持: "All four keys will be maintained",
  他放下心: "He feels relieved",
  日逐腾云驾雾: "The sun rushes to the clouds",
  遨游四海: "Travel around the world",
  行乐千山: "Walking in the thousands of mountains",
  施武艺: "Shi Wuyi",
  遍访英豪: "Visiting the British",
  弄神通: "Enjoy supernatural powers",
  广交贤友: "Make friends",
  此时又会了个七弟兄: "At this time, I met another seven brother",
  乃牛魔王: "The Bull Demon King",
  蛟魔王: "Dragon Demon King",
  鹏魔王: "The Demon King",
  狮驼王: "Lion Camel King",
  猕猴王: "The Macaque King",
  犭禺狨王: "King of the sage",
  连自家美猴王七个: "Even the seven Monkey Kings in my own",
  日逐讲文论武: "Talk about literature and martial arts every day",
  走斝传觞: "Walking in the past",
  弦歌吹舞: "Strings and dances",
  朝去暮回: "Go back in the morning",
  无般儿不乐: "Nothing happy",
  把那个万里之遥: "Put that far away",
  只当庭闱之路: "Just to the road to court",
  所谓点头径过三千里: "The so-called nodding path is over three thousand miles",
  扭腰八百有馀程: "Twisting your waist for more than 800 years",
  一日: "One day",
  在本洞吩咐四健将安排筵宴:
    "Instruct the four generals to arrange a banquet in this cave",
  请六王赴饮: "Invite the six kings to drink",
  杀牛宰马: "Kill cattle and horses",
  祭天享地: "Sacrifice to heaven and earth",
  着众怪跳舞欢歌: "Dancing and singing with all the monsters",
  俱吃得酩酊大醉: "All drunk",
  送六王出去: "Send the Six Kings out",
  却又赏劳大小头目: "But he rewarded the leaders of all sizes",
  在铁板桥边松阴之下: "Under the pine shade beside the iron bridge",
  霎时间睡着: "Sleeping in an instant",
  四健将领众围护: "Four heroes lead the siege",
  不敢高声: "Don't dare to speak loudly",
};

const tianwen_translation_map_de = {
  你看这猴王: "Schau dir diesen Affenkönig an",
  分开水道: "Teilen Sie die Wasserstraße",
  径回铁板桥头: "Geh zurück zum Eisenbrückenkopf",
  撺将上去: "Steigen",
  只见四个老猴: "Nur vier alte Affen",
  领着众猴: "Führe die Affen",
  都在桥边等候: "Alle warten an der Brücke",
  忽然见悟空跳出波外: "Plötzlich sprang Wukong aus der Welle",
  身上更无一点水湿: "Es gibt keine Feuchtigkeit am Körper",
  金灿灿的: "Golden",
  走上桥来: "Komm auf die Brücke",
  唬得众猴一齐跪下道:
    "Die Affen hatten so viel Angst, dass sie sich kniete und sagten",
  大王: "Der König",
  好华彩耶: "Sehr farbenfroh",
  好华彩耶: "Sehr farbenfroh",
  悟空满面春风: "Wukong ist mit Frühlingsbrise bedeckt",
  高登宝座: "Gordon Thron",
  将铁棒竖在当中: "Legen Sie die Eisenstange hinein",
  那些猴不知好歹: "Diese Affen wissen nicht, was gut ist",
  都来拿那宝贝: "Komm und hol diesen Schatz",
  却便似蜻蜓撼铁树:
    "Aber es ist wie eine Libelle, die einen Eisenbaum schüttelt",
  分毫也不能禁动: "Kann es überhaupt nicht verbieten",
  一个个咬指伸舌道:
    "One by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, one by one, einzeln, eins nach eins, nacheinander, eins nacheinander, eins nacheinander, einzeln, eins nach eins, eins nach eins, eins nach dem anderen",
  爷爷呀: "Opa",
  这般重: "So schwer",
  亏你怎的拿来也: "Warum hast du es mitgebracht?",
  悟空近前: "Wukong nähert sich",
  舒开手一把挝起: "Lass deine Hände los",
  对众笑道: "Lächle allen",
  物各有主: "Jedes Ding hat seinen eigenen Meister",
  这宝贝镇于海藏中: "Dieser Schatz ist im Meeres Schatzkammer",
  也不知几千百年: "Ich bin mir nicht sicher, wie viele tausend Jahre",
  可可的今岁放光: "Das Jahr des Kokos scheint",
  龙王只认做是块黑铁:
    "Der Drachenkönig betrachtet es nur als ein Stück schwarzes Eisen",
  又唤做天河镇底神珍:
    "Auch der Gott der himmlischen Schätze im Grund der Stadt Tianhe genannt",
  那厮每都扛抬不动: "Dieser Typ hebt es nie an",
  请我亲去拿之: "Bitte bitten Sie mich, es persönlich zu bekommen",
  那时此宝有二丈多长: "Zu dieser Zeit war dieser Schatz mehr als zwei Fuß lang",
  斗来粗细: "Die Dicke des Eimers",
  被我挝他一把: "Ich habe ihm eine Hand gegeben",
  意思嫌大: "Es ist sehr bedeutungsvoll",
  他就小了许多: "Er ist viel kleiner",
  再教小些: "Bringen Sie es ein bisschen kleiner bei",
  他又小了许多: "Er ist wieder viel jünger",
  再教小些: "Bringen Sie es ein bisschen kleiner bei",
  他又小了许多: "Er ist wieder viel jünger",
  急对天光看处: "Schauen Sie dringend das Himmellicht an",
  上有一行字: "Es gibt eine Reihe von Wörtern darauf",
  乃如意金箍棒: "Naruyi Golden Hoop",
  一万三千五百斤: "Zehntausend dreitausend fünfhundert Kilogramm",
  你都站开: "Du stehst",
  等我再叫他变一变着: "Ich werde ihm sagen, er soll sich ändern",
  他将那宝贝颠在手中: "Er legte das Baby in seine Hand",
  叫: "Anruf",
  小小小: "Little Little",
  即时就小做一个绣花针儿相似:
    "Machen Sie einfach eine Stickernadel in Echtzeit.",
  可以揌在耳朵里面藏下: "Kann in deinen Ohren verborgen werden",
  众猴骇然: "Die Affen waren schockiert",
  叫道: "Berufung",
  大王: "Der König",
  还拿出来耍耍: "Und nimm es zum Spielen heraus",
  猴王真个去耳朵里拿出: "Der Affenkönig nahm es wirklich aus seinem Ohr",
  托放掌上叫: "Legen Sie es auf Ihre Handfläche und rufen Sie an",
  大大大: "Big Big",
  即又大做斗来粗细: "Es ist ein großer Treffer, um die Dicke zu machen",
  二丈长短: "Zwei Fuß lang",
  他弄到欢喜处: "Er bekam einen glücklichen Ort",
  跳上桥: "Auf die Brücke springen",
  走出洞外: "Aus der Höhle gehen",
  将宝贝攥在手中: "Halten Sie das Baby in der Hand",
  做一个法天象地的神通: "Eine magische Kraft sein, die Welt zu tun",
  把腰一躬: "Verbeuge deine Taille",
  叫声长: "Langer Schrei",
  他就长的高万丈: "Er ist so groß",
  头如泰山: "Kopf wie Mount Tai",
  腰如峻岭: "Die Taille ist wie ein Steiler",
  眼如闪电: "Augen wie Blitz",
  口似血盆: "Der Mund ist wie ein blutiges Becken",
  牙如剑戟: "Zähne wie ein Schwert",
  手中那棒: "Das bleibt in der Hand",
  上抵三十三天: "Dreiunddreißig Tage",
  下至十八层地狱: "Bis zur achtzehnten Hölle der Hölle",
  把些虎豹狼虫: "Setzen Sie etwas Tiger, Leopard, Wolfsekten ein",
  满山群怪: "Monster auf dem ganzen Berg",
  七十二洞妖王: "Zweiundsiebzig Höhlendämonenkönige",
  都唬得磕头礼拜: "Alle haben so Angst, dass sie zu verehren, um zu verehren",
  战兢兢魄散魂飞: "Mit Angst fliegen",
  霎时收了法像: "Ich habe sofort das magische Bild gesammelt",
  将宝贝还变做个绣花针儿: "Verwandeln Sie Ihr Baby in eine Stickernadel",
  藏在耳内: "Versteckt in den Ohren",
  复归洞府: "Kehre zum Höhlenhaus zurück",
  慌得那各洞妖王: "Die Dämonenkönige der Höhlen waren so in Panik geraten",
  都来参贺: "Komm und gratuliere",
  此时遂大开旗鼓: "Zu dieser Zeit wurden die Flaggen und Trommeln geöffnet",
  响振铜锣: "Der Gong wird vibriert",
  广设珍馐百味: "Richten Sie eine breite Palette köstlicher Lebensmittel ein",
  满斟椰液萄浆: "Gießen Sie Kokosnusslauge",
  与众饮宴多时: "Haben eine lange Zeit, um ein Bankett zu haben",
  却又依前教演: "Aber er trat nach dem vorherigen Lehren auf",
  猴王将那四个老猴封为健将:
    "Der Affenkönig nannte die vier alten Affen als starke Generäle",
  将两个赤尻马猴唤做马流二元帅:
    "Rufen Sie die beiden rot-Butt-Pferdesaffen an, um der zweite Marschall von Pferden und Liushu zu sein",
  两个通背猿猴唤做崩芭二将军:
    "Zwei Affen auf der Rückseite werden als zwei Generäle von Bengba bezeichnet",
  将那安营下寨: "Lass das camp",
  赏罚诸事: "Belohnungen und Strafen",
  都付与四键将维持: "Alle vier Schlüssel werden beibehalten",
  他放下心: "Er fühlt sich erleichtert",
  日逐腾云驾雾: "Die Sonne eilt zu den Wolken",
  遨游四海: "Reisen Sie um die Welt",
  行乐千山: "Gehen in den Tausenden von Bergen",
  施武艺: "Shi Wuyi",
  遍访英豪: "Besuchen Sie die Briten",
  弄神通: "Genießen Sie übernatürliche Kräfte",
  广交贤友: "Freunde machen",
  此时又会了个七弟兄: "Zu dieser Zeit traf ich einen weiteren sieben Bruder",
  乃牛魔王: "Der Bullenkönig",
  蛟魔王: "Dragon Dämon King",
  鹏魔王: "Der Dämonenkönig",
  狮驼王: "Löwenkamelkönig",
  猕猴王: "Der Macaken -König",
  犭禺狨王: "König des Weisen",
  连自家美猴王七个: "Sogar die sieben Monkey Kings in meinen eigenen",
  日逐讲文论武: "Sprechen Sie jeden Tag über Literatur und Kampfkunst",
  走斝传觞: "In der Vergangenheit gehen",
  弦歌吹舞: "Saiten und Tänze",
  朝去暮回: "Morgens zurückgehen",
  无般儿不乐: "Nichts glücklich",
  把那个万里之遥: "Streichen Sie so weit weg",
  只当庭闱之路: "Nur auf die Straße vor Gericht",
  所谓点头径过三千里:
    "Der sogenannte Nickenpfad beträgt mehr als dreitausend Meilen",
  扭腰八百有馀程: "Wenn Sie Ihre Taille für mehr als 800 Jahre verdrehen",
  一日: "Einmal",
  在本洞吩咐四健将安排筵宴:
    "Weisen Sie die vier Generäle an, ein Bankett in dieser Höhle zu arrangieren",
  请六王赴饮: "Laden Sie die sechs Könige zum Trinken ein",
  杀牛宰马: "Töte Vieh und Pferde",
  祭天享地: "Opfer für Himmel und Erde",
  着众怪跳舞欢歌: "Tanzen und Singen mit allen Monstern",
  俱吃得酩酊大醉: "Alle betrunken",
  送六王出去: "Senden Sie die sechs Könige aus",
  却又赏劳大小头目: "Aber er belohnte die Führer aller Größen",
  在铁板桥边松阴之下: "Unter dem Kiefernschatten neben der Eisenbrücke",
  霎时间睡着: "Sofort schlafen",
  四健将领众围护: "Vier Helden führen die Belagerung an",
  不敢高声: "Wagen Sie es nicht, laut zu sprechen",
};

const tianwen_translation_map_fr = {
  你看这猴王: "Regardez ce roi de singe",
  分开水道: "Diviser la voie navigable",
  径回铁板桥头: "Retournez à la tête de pont de fer",
  撺将上去: "Monter",
  只见四个老猴: "Seulement quatre vieux singes",
  领着众猴: "Diriger les singes",
  都在桥边等候: "Tous en attente du pont",
  忽然见悟空跳出波外: "Soudain, Wukong a sauté de la vague",
  身上更无一点水湿: "Il n'y a pas d'humidité sur le corps",
  金灿灿的: "Doré",
  走上桥来: "Allez sur le pont",
  唬得众猴一齐跪下道:
    "Les singes avaient tellement peur qu'ils s'agenouillent et ont dit",
  大王: "Le roi",
  好华彩耶: "Très coloré",
  好华彩耶: "Très coloré",
  悟空满面春风: "Wukong est recouvert de brise de printemps",
  高登宝座: "Trône de Gordon",
  将铁棒竖在当中: "Mettez la tige de fer dedans",
  那些猴不知好歹: "Ces singes ne savent pas ce qui est bon",
  都来拿那宝贝: "Venez obtenir ce trésor",
  却便似蜻蜓撼铁树: "Mais c'est comme une libellule tremblant un arbre de fer",
  分毫也不能禁动: "Je ne peux pas l'interdire du tout",
  一个个咬指伸舌道:
    "Un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un par un, un, un par un, un par un un, un par un, un par un",
  爷爷呀: "Grand-père",
  这般重: "Si lourd",
  亏你怎的拿来也: "Pourquoi l'avez-vous apporté?",
  悟空近前: "Wukong approche",
  舒开手一把挝起: "Lâchez vos mains",
  对众笑道: "Sourire à tout le monde",
  物各有主: "Chaque chose a son propre maître",
  这宝贝镇于海藏中: "Ce trésor est dans le trésor marin",
  也不知几千百年: "Je ne sais pas combien de milliers d'années",
  可可的今岁放光: "Le cacao brille cette année",
  龙王只认做是块黑铁:
    "Le Dragon King ne considère que c'est un morceau de fer noir",
  又唤做天河镇底神珍:
    "Aussi appelé le dieu des trésors célestes au fond de la ville de Tianhe",
  那厮每都扛抬不动: "Ce mec ne le soulève jamais",
  请我亲去拿之: "S'il vous plaît demandez-moi de l'obtenir en personne",
  那时此宝有二丈多长:
    "À ce moment-là, ce trésor mesurait plus de deux pieds de long",
  斗来粗细: "L'épaisseur du seau",
  被我挝他一把: "Je lui ai donné un coup de main",
  意思嫌大: "C'est très significatif",
  他就小了许多: "Il est beaucoup plus petit",
  再教小些: "Apprenez-le un peu plus petit",
  他又小了许多: "Il est encore beaucoup plus jeune",
  再教小些: "Apprenez-le un peu plus petit",
  他又小了许多: "Il est encore beaucoup plus jeune",
  急对天光看处: "Regardez le ciel léger de toute urgence",
  上有一行字: "Il y a une ligne de mots dessus",
  乃如意金箍棒: "Naruyi Golden Hoop",
  一万三千五百斤: "Dix mille trois mille cinq cents kilogrammes",
  你都站开: "Tu es debout",
  等我再叫他变一变着: "Je vais lui dire de changer",
  他将那宝贝颠在手中: "Il a mis le bébé dans sa main",
  叫: "Appel",
  小小小: "Petit",
  即时就小做一个绣花针儿相似:
    "Faites simplement une aiguille de broderie en temps réel.",
  可以揌在耳朵里面藏下: "Peut être caché dans vos oreilles",
  众猴骇然: "Les singes ont été choqués",
  叫道: "Appel",
  大王: "Le roi",
  还拿出来耍耍: "Et retirez-le pour jouer",
  猴王真个去耳朵里拿出: "Le roi de singe l'a vraiment sorti de son oreille",
  托放掌上叫: "Mettez-le sur votre paume et appelez",
  大大大: "Grand",
  即又大做斗来粗细: "C'est un grand succès pour faire l'épaisseur",
  二丈长短: "Deux pieds de long",
  他弄到欢喜处: "Il a un endroit heureux",
  跳上桥: "Sauter sur le pont",
  走出洞外: "Sortir de la grotte",
  将宝贝攥在手中: "Tenez le bébé dans votre main",
  做一个法天象地的神通: "Être un pouvoir magique pour faire le monde",
  把腰一躬: "Inclinez votre taille",
  叫声长: "Long cri",
  他就长的高万丈: "Il est si grand",
  头如泰山: "Tête comme le mont Tai",
  腰如峻岭: "La taille est comme une escarpe",
  眼如闪电: "Les yeux comme la foudre",
  口似血盆: "La bouche est comme un bassin sanglant",
  牙如剑戟: "Des dents comme une épée",
  手中那棒: "Ce bâton en main",
  上抵三十三天: "Trente-trois jours",
  下至十八层地狱: "Jusqu'au dix-huitième niveau de l'enfer",
  把些虎豹狼虫: "Mettez des insectes de tigre, de léopard, de loup",
  满山群怪: "Monstres partout sur la montagne",
  七十二洞妖王: "Soixante-douze rois de démon cave",
  都唬得磕头礼拜: "Tous ont tellement peur qu'ils Kowtow à adorer",
  战兢兢魄散魂飞: "Voler avec peur",
  霎时收了法像: "J'ai immédiatement collecté l'image magique",
  将宝贝还变做个绣花针儿: "Transformez votre bébé en une aiguille de broderie",
  藏在耳内: "Caché dans les oreilles",
  复归洞府: "Retour à la Cave House",
  慌得那各洞妖王: "Les rois démons des grottes étaient tellement paniqués",
  都来参贺: "Venez féliciter",
  此时遂大开旗鼓: "À ce moment, les drapeaux et les tambours ont été ouverts",
  响振铜锣: "Le gong est vibré",
  广设珍馐百味: "Configurez une large gamme de délicieux aliments",
  满斟椰液萄浆: "Verser de la liqueur de noix de coco",
  与众饮宴多时: "Avoir beaucoup de temps pour avoir un banquet",
  却又依前教演: "Mais il a joué selon l'enseignement précédent",
  猴王将那四个老猴封为健将:
    "Le roi de singe a nommé les quatre vieux singes comme généraux forts",
  将两个赤尻马猴唤做马流二元帅:
    "Appelez les deux singes de cheval rouge pour être le deuxième maréchal des chevaux et Liushu",
  两个通背猿猴唤做崩芭二将军:
    "Deux singes à l'arrière sont appelés les deux généraux de Bengba",
  将那安营下寨: "Armure dans le village",
  赏罚诸事: "Récompenses et punitions",
  都付与四键将维持: "Les quatre clés seront maintenues",
  他放下心: "Il se sent soulagé",
  日逐腾云驾雾: "Le soleil se précipite vers les nuages",
  遨游四海: "Voyager à travers le monde",
  行乐千山: "Marcher dans les milliers de montagnes",
  施武艺: "Shi wuyi",
  遍访英豪: "Visiter les Britanniques",
  弄神通: "Profitez des pouvoirs surnaturels",
  广交贤友: "Faire des amis",
  此时又会了个七弟兄: "À ce moment-là, j'ai rencontré sept autres frère",
  乃牛魔王: "Le roi du démon taureau",
  蛟魔王: "Dragon Demon King",
  鹏魔王: "Le roi démon",
  狮驼王: "Roi de chameau de lion",
  猕猴王: "Le roi macaque",
  犭禺狨王: "Roi du sage",
  连自家美猴王七个: "Même les sept rois de singe dans le mien",
  日逐讲文论武: "Parler de la littérature et des arts martiaux tous les jours",
  走斝传觞: "Marcher dans le passé",
  弦歌吹舞: "Cordes et danses",
  朝去暮回: "Retourner le matin",
  无般儿不乐: "Rien de heureux",
  把那个万里之遥: "Mettez-vous loin",
  只当庭闱之路: "Juste sur la route vers la cour",
  所谓点头径过三千里:
    "Le soi-disant chemin de hochement de tête est à plus de trois mille milles",
  扭腰八百有馀程: "Tordre votre taille pendant plus de 800 ans",
  一日: "Un jour",
  在本洞吩咐四健将安排筵宴:
    "Demandez aux quatre généraux d'organiser un banquet dans cette grotte",
  请六王赴饮: "Invitez les six rois à boire",
  杀牛宰马: "Tuer du bétail et des chevaux",
  祭天享地: "Sacrifice au ciel et à la terre",
  着众怪跳舞欢歌: "Danser et chanter avec tous les monstres",
  俱吃得酩酊大醉: "Tout ivre",
  送六王出去: "Envoyer les six rois",
  却又赏劳大小头目: "Mais il a récompensé les dirigeants de toutes tailles",
  在铁板桥边松阴之下: "À l'ombre de la pin à côté du pont de fer",
  霎时间睡着: "Dormir en un instant",
  四健将领众围护: "Quatre héros mènent le siège",
  不敢高声: "N'ose pas parler fort",
};



const synth = window.speechSynthesis;
let utterance = null;

// 状态跟踪
const charStates = {};

// 页面加载完成后初始化
document.addEventListener("DOMContentLoaded", function () {
  renderPoem();
});

// 渲染诗歌
function renderPoem() {
  const poemContainer = document.getElementById("poemContainer");
  const lines = poemText.split("\n");

  lines.forEach((line) => {
    const lineDiv = document.createElement("div");
    lineDiv.className = "poem-line";

    // 处理每个字符
    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      // 跳过空格
      if (char.trim() === "") {
        const spaceSpan = document.createElement("span");
        spaceSpan.textContent = " ";
        lineDiv.appendChild(spaceSpan);
        continue;
      }

      // 创建字符容器
      const charContainer = document.createElement("div");
      charContainer.className = "char-container";

      // 创建字符显示
      const charSpan = document.createElement("span");
      charSpan.className = "char";
      charSpan.textContent = char;

      // 创建拼音显示
      const pinyinSpan = document.createElement("span");
      pinyinSpan.className = "pinyin";

      // 创建翻译显示
      const transSpan = document.createElement("span");
      transSpan.className = "translation";

      // 添加到容器
      charContainer.appendChild(pinyinSpan);
      charContainer.appendChild(charSpan);
      charContainer.appendChild(transSpan);

      // 添加点击事件
      charContainer.addEventListener("click", () =>
        handleCharClick(char, pinyinSpan, transSpan)
      );

      // 添加到行
      lineDiv.appendChild(charContainer);
    }

    // 添加行控制按钮
    const controlsDiv = document.createElement("div");
    controlsDiv.className = "line-controls";

    const readBtn = document.createElement("button");
    readBtn.textContent = "朗读";
    readBtn.addEventListener("click", () => readLine(line));

    const transBtn = document.createElement("button");
    transBtn.textContent = "翻译";
    transBtn.addEventListener("click", () => showLineTranslation(line));

    controlsDiv.appendChild(readBtn);
    controlsDiv.appendChild(transBtn);
    lineDiv.appendChild(controlsDiv);

    // 添加到容器
    poemContainer.appendChild(lineDiv);
  });
}

// 处理字符点击
function handleCharClick(char, pinyinSpan, transSpan) {
  const charId = `${char}-${pinyinSpan.id}`; // 创建唯一标识

  // 初始化状态
  if (!charStates[charId]) {
    charStates[charId] = 0;
  }

  // 更新状态
  charStates[charId]++;
  if (charStates[charId] > 3) {
    charStates[charId] = 1;
  }

  // 根据状态执行操作
  switch (charStates[charId]) {
    case 1: // 朗读字符
      readChar(char);
      updateStatus(`朗读字符: ${char}`);
      break;
    case 2: // 显示拼音
      showPinyin(char, pinyinSpan);
      updateStatus(`显示拼音: ${char}`);
      break;
    case 3: // 显示翻译
      showTranslation(char, transSpan);
      updateStatus(`显示翻译: ${char}`);
      break;
  }
}

// 显示拼音
function showPinyin(char, pinyinSpan) {
  // 这里应该调用拼音库，简化处理

  const py = pinyinMap[char] || "?";
  pinyinSpan.textContent = py;
  pinyinSpan.style.display = "block";

  // 3秒后自动隐藏
  setTimeout(() => {
    pinyinSpan.style.display = "none";
    // 重置状态以便下次点击
    const charId = `${char}-${pinyinSpan.id}`;
    charStates[charId] = 0;
  }, 8000);
}

// 朗读字符
function readChar(char) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(char);
  utterance.lang = "zh-CN";
  utterance.rate = 0.7; // 设置为正常速度的70%
  synth.speak(utterance);
}

// 显示翻译
function showTranslation(char, transSpan) {
  const lang = document.getElementById("languageSelect").value;

  const translationCard = document.getElementById("translationCard");

  const translateMap = {
    de: translations_de[char] || "Keine Übersetzung",
    fr: translations_fr[char] || "Pas de traduction",
    en: translations_en[char] || "No translation",
  };
  const translate = translateMap[lang];
  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">汉字：</div>
    <div class="info-content">${char}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translate}</div>
  </div>
`;

  translationCard.style.display = "block";

  const charId = `${char}-${transSpan.id}`;
  charStates[charId] = 0;
}

function closeTranslationCard() {
  const translationCard = document.getElementById("translationCard");
  translationCard.style.display = "none";
}

// 朗读整行
function readLine(line) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(line);
  utterance.lang = "zh-CN";
  utterance.rate = 0.6; // 设置为正常速度的60%，更慢一些
  synth.speak(utterance);

  updateStatus(`朗读: ${line}`);
}

function showLineTranslation(line) {
  const lang = document.getElementById("languageSelect").value;
  const translatedMap = {
    de: tianwen_translation_map_de,
    fr: tianwen_translation_map_fr,
    en: tianwen_translation_map_en,
  };
  const translatedLine =
    translatedMap[lang]?.[line] || "（keine Übersetzung gefunden）";
  const translationCard = document.getElementById("translationCard");

  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">原文：</div>
    <div class="info-content">${line}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translatedLine}</div>
  </div>
`;

  translationCard.style.display = "block";

  updateStatus(`显示翻译: ${line.substring(0, 15)}...`);
}

// 更新状态栏
function updateStatus(message) {
  document.getElementById("statusBar").textContent = message;
}
