const translationCard = document.getElementById("translationCard");
// 诗歌文本c
const poemText = `却表启那个高天上圣大慈仁者玉皇大天尊玄穹高上帝
一日
驾坐金阙云宫灵霄宝殿
聚集文武仙卿早朝之际
忽有邱弘济真人启奏道
万岁
通明殿外
有东海龙王敖广进表
听天尊宣诏
玉皇传旨
着宣来
敖广宣至灵霄殿下
礼拜毕
旁有引奏仙童
接上表文
玉皇从头看过
表曰
水元下界东胜神洲东海小龙臣敖广启奏大天圣主玄穹高上帝君
近因花果山生
水帘洞住妖仙孙悟空者
欺虐小龙
强坐水宅
索兵器
施法施威
要披挂
骋凶骋势
惊伤水族
唬走龟鼍
南海龙战战兢兢
西海龙凄凄惨惨
北海龙缩首归降
臣敖广舒身下拜
献神珍之铁棒
凤翅之金冠
与那锁子甲
步云履
以礼送出
他仍弄武艺
显神通
但云聒噪
聒噪
果然无敌
甚为难制
臣今启奏
伏望圣裁
恳乞天兵
收此妖孽
庶使海岳清宁
下元安泰
奉奏
圣帝览毕
传旨
着龙神回海
朕即遣将擒拿
老龙王顿首谢去
下面又有葛仙翁天师启奏道
万岁
有冥司秦广王赍奉幽冥教主地藏王菩萨表文进上
旁有传言玉女
接上表文
玉皇亦从头看过
表曰
幽冥境界
乃地之阴司
天有神而地有鬼
阴阳转轮
禽有生而兽有死
反复雌雄
生生化化
孕女成男
此自然之数
不能易也
今有花果山水廉洞天产妖猴孙悟空
逞强行凶
不服拘唤
弄神通
打绝九幽鬼使
恃势力
惊伤十代慈王
大闹罗森
强销名号
致使猴属之类无拘
猕猴之畜多寿
寂灭轮回
各无生死
贫僧具表
冒渎天威
伏乞调遣神兵
收降此妖
整理阴阳
永安地府
谨奏
玉皇览毕
传旨
着冥君回归地府
朕即遣将擒拿
秦广王亦顿首谢去
大天尊宣众文武仙卿
问曰
这妖猴是几年生育
何代出生
却就这般有道
一言未已
班中闪出千里眼
顺风耳道
这猴乃三百年前天产石猴
当时不以为然
不知这几年在何方修炼成仙
降龙伏虎
强销死籍也
玉帝道
那路神将下界收伏
言未已
班中闪出太白长庚星
俯首启奏道
上圣三界中
凡有九窍者
皆可修仙
奈此猴乃天地育成之体
日月孕就之身
他也顶天履地
服露餐霞
今既修成仙道
有降龙伏虎之能
与人何以异哉
臣启陛下
可念生化之慈恩
降一道招安圣旨
把他宣来上届
授他一个大小官职
与他籍名在箓
拘束此间
若受天命
后再升赏
若违天命
就此擒拿
一则不动众劳师
二则收仙有道也
玉帝闻言甚喜
道
依卿所奏
即着文曲星官修诏
着太白金星招安`;

const pinyinMap = {
  却: "què",
  表: "biǎo",
  启: "qǐ",
  那: "nà",
  个: "gè",
  高: "gāo",
  天: "tiān",
  上: "shàng",
  圣: "shèng",
  大: "dà",
  慈: "cí",
  仁: "rén",
  者: "zhě",
  玉: "yù",
  皇: "huáng",
  尊: "zūn",
  玄: "xuán",
  穹: "qióng",
  帝: "dì",
  一: "yī",
  日: "rì",
  驾: "jià",
  坐: "zuò",
  金: "jīn",
  阙: "què",
  云: "yún",
  宫: "gōng",
  灵: "líng",
  霄: "xiāo",
  宝: "bǎo",
  殿: "diàn",
  聚: "jù",
  集: "jí",
  文: "wén",
  武: "wǔ",
  仙: "xiān",
  卿: "qīng",
  早: "zǎo",
  朝: "cháo",
  之: "zhī",
  际: "jì",
  忽: "hū",
  有: "yǒu",
  邱: "qiū",
  弘: "hóng",
  济: "jì",
  真: "zhēn",
  人: "rén",
  奏: "zòu",
  道: "dào",
  万: "wàn",
  岁: "suì",
  通: "tōng",
  明: "míng",
  外: "wài",
  东: "dōng",
  海: "hǎi",
  龙: "lóng",
  王: "wáng",
  敖: "áo",
  广: "guǎng",
  进: "jìn",
  听: "tīng",
  宣: "xuān",
  诏: "zhào",
  传: "chuán",
  旨: "zhǐ",
  着: "zhe",
  来: "lái",
  至: "zhì",
  下: "xià",
  礼: "lǐ",
  拜: "bài",
  毕: "bì",
  旁: "páng",
  引: "yǐn",
  童: "tóng",
  接: "jiē",
  从: "cóng",
  头: "tóu",
  看: "kàn",
  过: "guò",
  曰: "yuē",
  水: "shuǐ",
  元: "yuán",
  界: "jiè",
  胜: "shèng",
  神: "shén",
  洲: "zhōu",
  小: "xiǎo",
  臣: "chén",
  主: "zhǔ",
  君: "jūn",
  近: "jìn",
  因: "yīn",
  花: "huā",
  果: "guǒ",
  山: "shān",
  生: "shēng",
  帘: "lián",
  洞: "dòng",
  住: "zhù",
  妖: "yāo",
  孙: "sūn",
  悟: "wù",
  空: "kōng",
  欺: "qī",
  虐: "nüè",
  强: "qiáng",
  宅: "zhái",
  索: "suǒ",
  兵: "bīng",
  器: "qì",
  施: "shī",
  法: "fǎ",
  威: "wēi",
  要: "yào",
  披: "pī",
  挂: "guà",
  骋: "chěng",
  凶: "xiōng",
  势: "shì",
  惊: "jīng",
  伤: "shāng",
  族: "zú",
  唬: "hǔ",
  走: "zǒu",
  龟: "guī",
  鼍: "tuó",
  南: "nán",
  战: "zhàn",
  兢: "jīng",
  西: "xī",
  凄: "qī",
  惨: "cǎn",
  北: "běi",
  缩: "suō",
  首: "shǒu",
  归: "guī",
  降: "xiáng",
  舒: "shū",
  身: "shēn",
  献: "xiàn",
  珍: "zhēn",
  铁: "tiě",
  棒: "bàng",
  凤: "fèng",
  翅: "chì",
  冠: "guān",
  与: "yǔ",
  锁: "suǒ",
  子: "zi",
  甲: "jiǎ",
  步: "bù",
  履: "lǚ",
  以: "yǐ",
  送: "sòng",
  出: "chū",
  他: "tā",
  仍: "réng",
  弄: "nòng",
  艺: "yì",
  显: "xiǎn",
  但: "dàn",
  聒: "guā",
  噪: "zào",
  然: "rán",
  无: "wú",
  敌: "dí",
  甚: "shèn",
  为: "wéi",
  难: "nán",
  制: "zhì",
  今: "jīn",
  伏: "fú",
  望: "wàng",
  裁: "cái",
  恳: "kěn",
  乞: "qǐ",
  收: "shōu",
  此: "cǐ",
  孽: "niè",
  庶: "shù",
  使: "shǐ",
  岳: "yuè",
  清: "qīng",
  宁: "níng",
  安: "ān",
  泰: "tài",
  奉: "fèng",
  览: "lǎn",
  回: "huí",
  朕: "zhèn",
  即: "jí",
  遣: "qiǎn",
  将: "jiāng",
  擒: "qín",
  拿: "ná",
  老: "lǎo",
  顿: "dùn",
  谢: "xiè",
  去: "qù",
  面: "miàn",
  又: "yòu",
  葛: "gé",
  翁: "wēng",
  师: "shī",
  冥: "míng",
  司: "sī",
  秦: "qín",
  赍: "jī",
  幽: "yōu",
  教: "jiào",
  地: "dì",
  藏: "zàng",
  菩: "pú",
  萨: "sà",
  言: "yán",
  女: "nǚ",
  亦: "yì",
  境: "jìng",
  乃: "nǎi",
  阴: "yīn",
  而: "ér",
  鬼: "guǐ",
  阳: "yáng",
  转: "zhuàn",
  轮: "lún",
  禽: "qín",
  兽: "shòu",
  死: "sǐ",
  反: "fǎn",
  复: "fù",
  雌: "cí",
  雄: "xióng",
  化: "huà",
  孕: "yùn",
  成: "chéng",
  男: "nán",
  自: "zì",
  数: "shù",
  不: "bù",
  能: "néng",
  易: "yì",
  也: "yě",
  廉: "lián",
  产: "chǎn",
  猴: "hóu",
  逞: "chěng",
  行: "xíng",
  服: "fú",
  拘: "jū",
  唤: "huàn",
  打: "dǎ",
  绝: "jué",
  九: "jiǔ",
  恃: "shì",
  力: "lì",
  十: "shí",
  代: "dài",
  闹: "nào",
  罗: "luó",
  森: "sēn",
  销: "xiāo",
  名: "míng",
  号: "hào",
  致: "zhì",
  属: "shǔ",
  类: "lèi",
  猕: "mí",
  畜: "chù",
  多: "duō",
  寿: "shòu",
  寂: "jì",
  灭: "miè",
  各: "gè",
  贫: "pín",
  僧: "sēng",
  具: "jù",
  冒: "mào",
  渎: "dú",
  调: "tiáo",
  整: "zhěng",
  理: "lǐ",
  永: "yǒng",
  府: "fǔ",
  谨: "jǐn",
  众: "zhòng",
  问: "wèn",
  这: "zhè",
  是: "shì",
  几: "jǐ",
  年: "nián",
  育: "yù",
  何: "hé",
  就: "jiù",
  般: "bān",
  未: "wèi",
  已: "yǐ",
  班: "bān",
  中: "zhōng",
  闪: "shǎn",
  千: "qiān",
  里: "lǐ",
  眼: "yǎn",
  顺: "shùn",
  风: "fēng",
  耳: "ěr",
  三: "sān",
  百: "bǎi",
  前: "qián",
  石: "shí",
  当: "dāng",
  时: "shí",
  知: "zhī",
  在: "zài",
  方: "fāng",
  修: "xiū",
  炼: "liàn",
  虎: "hǔ",
  籍: "jí",
  路: "lù",
  太: "tài",
  白: "bái",
  长: "cháng",
  庚: "gēng",
  星: "xīng",
  俯: "fǔ",
  凡: "fán",
  窍: "qiào",
  皆: "jiē",
  可: "kě",
  奈: "nài",
  体: "tǐ",
  月: "yuè",
  顶: "dǐng",
  露: "lù",
  餐: "cān",
  霞: "xiá",
  既: "jì",
  异: "yì",
  哉: "zāi",
  陛: "bì",
  念: "niàn",
  恩: "ēn",
  招: "zhāo",
  把: "bǎ",
  届: "jiè",
  授: "shòu",
  官: "guān",
  职: "zhí",
  箓: "lù",
  束: "shù",
  间: "jiān",
  若: "ruò",
  受: "shòu",
  命: "mìng",
  后: "hòu",
  再: "zài",
  升: "shēng",
  赏: "shǎng",
  违: "wéi",
  则: "zé",
  动: "dòng",
  劳: "láo",
  二: "èr",
  闻: "wén",
  喜: "xǐ",
  依: "yī",
  所: "suǒ",
  曲: "qū",
};

const translations_en = {
  却: "but",
  表: "surface",
  启: "start",
  那: "That",
  个: "indivual",
  高: "high",
  天: "sky",
  上: "superior",
  圣: "Saint",
  大: "big",
  慈: "Ci",
  仁: "Benevolence",
  者: "Those",
  玉: "Jade",
  皇: "Emperor",
  尊: "Honor",
  玄: "mysterious",
  穹: "Dome",
  帝: "emperor",
  一: "one",
  日: "day",
  驾: "drive",
  坐: "sit",
  金: "gold",
  阙: "Que",
  云: "cloud",
  宫: "palace",
  灵: "spirit",
  霄: "Sky",
  宝: "precious",
  殿: "temple",
  聚: "Gather",
  集: "set",
  文: "arts",
  武: "Wu",
  仙: "Fairy",
  卿: "You",
  早: "morning",
  朝: "towards",
  之: "Of",
  际: "International",
  忽: "suddenly",
  有: "have",
  邱: "Qiu",
  弘: "Hong",
  济: "Ji",
  真: "real",
  人: "people",
  奏: "Play",
  道: "road",
  万: "Ten thousand",
  岁: "age",
  通: "Pass",
  明: "bright",
  外: "outside",
  东: "East",
  海: "ocean",
  龙: "dragon",
  王: "king",
  敖: "Ao",
  广: "wide",
  进: "Enter",
  听: "listen",
  宣: "Promotion",
  诏: "Imperial",
  传: "pass",
  旨: "purpose",
  着: "Put",
  来: "Come",
  至: "to",
  下: "Down",
  礼: "present",
  拜: "bye",
  毕: "complete",
  旁: "beside",
  引: "lead",
  童: "child",
  接: "catch",
  从: "from",
  头: "head",
  看: "look",
  过: "Pass",
  曰: "say",
  水: "water",
  元: "Yuan",
  界: "boundary",
  胜: "Win",
  神: "god",
  洲: "Continent",
  小: "Small",
  臣: "minister",
  主: "host",
  君: "Jun",
  近: "close",
  因: "because",
  花: "flower",
  果: "fruit",
  山: "Mountain",
  生: "born",
  帘: "curtain",
  洞: "Hole",
  住: "live",
  妖: "Demon",
  孙: "Sun",
  悟: "Enlightenment",
  空: "null",
  欺: "bully",
  虐: "Abusive",
  强: "powerful",
  宅: "Home",
  索: "Search",
  兵: "Soldier",
  器: "Device",
  施: "Shi",
  法: "Law",
  威: "Viagra",
  要: "want",
  披: "路",
  挂: "hang",
  骋: "Ai",
  凶: "fierce",
  势: "Stability",
  惊: "shock",
  伤: "hurt",
  族: "Family",
  唬: "fool",
  走: "Walk",
  龟: "Turtle",
  鼍: "turtle",
  南: "South",
  战: "war",
  兢: "Virginity",
  西: "West",
  凄: "sad",
  惨: "miserable",
  北: "north",
  缩: "Shrink",
  首: "head",
  归: "Go home",
  降: "drop",
  舒: "Sweet",
  身: "body",
  献: "offer",
  珍: "Jen",
  铁: "iron",
  棒: "Great",
  凤: "phoenix",
  翅: "wing",
  冠: "crown",
  与: "and",
  锁: "Lock",
  子: "son",
  甲: "First",
  步: "step",
  履: "shoe",
  以: "by",
  送: "deliver",
  出: "out",
  他: "he",
  仍: "still",
  弄: "alley",
  艺: "art",
  显: "Show",
  但: "but",
  聒: "Hollow",
  噪: "noise",
  然: "Of course",
  无: "none",
  敌: "enemy",
  甚: "very",
  为: "for",
  难: "Disaster",
  制: "system",
  今: "now",
  伏: "Fu",
  望: "see",
  裁: "Cut",
  恳: "Hope",
  乞: "beg",
  收: "receive",
  此: "this",
  孽: "evil",
  庶: "Silent",
  使: "make",
  岳: "Yue",
  清: "clear",
  宁: "rather",
  安: "install",
  泰: "Thai",
  奉: "Feng",
  览: "View",
  回: "Back",
  朕: "I",
  即: "Right now",
  遣: "Send",
  将: "Will",
  擒: "capture",
  拿: "take",
  老: "old",
  顿: "Dun",
  谢: "Thanks",
  去: "go",
  面: "noodle",
  又: "again",
  葛: "Germa",
  翁: "Yeon",
  师: "division",
  冥: "deep",
  司: "manage",
  秦: "Qin",
  赍: "With",
  幽: "quiet",
  教: "teach",
  地: "land",
  藏: "Tibetan",
  菩: "Bodhisattva",
  萨: "Sa",
  言: "Word",
  女: "female",
  亦: "as well as",
  境: "territory",
  乃: "So",
  阴: "Negative",
  而: "and",
  鬼: "ghost",
  阳: "Positive",
  转: "change",
  轮: "wheel",
  禽: "birds",
  兽: "beast",
  死: "die",
  反: "opposite",
  复: "complex",
  雌: "female",
  雄: "male",
  化: "change",
  孕: "pregnant",
  成: "become",
  男: "male",
  自: "since",
  数: "number",
  不: "No",
  能: "able",
  易: "easy",
  也: "also",
  廉: "inexpensive",
  产: "Produce",
  猴: "monkey",
  逞: "Satisfied",
  行: "OK",
  服: "Clothes",
  拘: "arrest",
  唤: "Call",
  打: "beat",
  绝: "Absolute",
  九: "Nine",
  恃: "rely",
  力: "force",
  十: "ten",
  代: "generation",
  闹: "Furious",
  罗: "Luo",
  森: "南",
  销: "pin",
  名: "name",
  号: "Number",
  致: "To",
  属: "Generic",
  类: "kind",
  猕: "macaque",
  畜: "livestock",
  多: "many",
  寿: "life",
  寂: "lonely",
  灭: "Extinguish",
  各: "each",
  贫: "poor",
  僧: "monk",
  具: "Tool",
  冒: "Born",
  渎: "ditch",
  调: "Adjust",
  整: "all",
  理: "reason",
  永: "forever",
  府: "House",
  谨: "Be cautious",
  众: "All",
  问: "ask",
  这: "this",
  是: "yes",
  几: "Several",
  年: "Year",
  育: "Education",
  何: "what",
  就: "At once",
  般: "Normal",
  未: "not yet",
  已: "already",
  班: "class",
  中: "middle",
  闪: "flash",
  千: "thousand",
  里: "inside",
  眼: "Eye",
  顺: "Sure",
  风: "wind",
  耳: "Ear",
  三: "three",
  百: "Hundred",
  前: "forward",
  石: "stone",
  当: "when",
  时: "hour",
  知: "Know",
  在: "exist",
  方: "square",
  修: "build",
  炼: "Refining",
  虎: "Tiger",
  籍: "membership",
  路: "road",
  太: "too",
  白: "white",
  长: "long",
  庚: "Geng",
  星: "star",
  俯: "Descend",
  凡: "Any",
  窍: "Tips",
  皆: "all",
  可: "Can",
  奈: "Nye",
  体: "body",
  月: "moon",
  顶: "top",
  露: "dew",
  餐: "meal",
  霞: "Xia",
  既: "now that",
  异: "different",
  哉: "Yes",
  陛: "Your",
  念: "read",
  恩: "kindness",
  招: "trick",
  把: "Bundle",
  届: "Chapter",
  授: "Grant",
  官: "official",
  职: "Job",
  箓: "Talisman",
  束: "bundle",
  间: "between",
  若: "like",
  受: "by",
  命: "life",
  后: "back",
  再: "Again",
  升: "Lift",
  赏: "reward",
  违: "Violation",
  则: "but",
  动: "move",
  劳: "labor",
  二: "two",
  闻: "smell",
  喜: "happiness",
  依: "according to",
  所: "Place",
  曲: "song",
};

const translations_de = {
  却: "Aber",
  表: "Oberfläche",
  启: "Start",
  那: "Das",
  个: "indival",
  高: "hoch",
  天: "Himmel",
  上: "Vorgesetzter",
  圣: "Heilige",
  大: "groß",
  慈: "CI",
  仁: "Wohlwollen",
  者: "Diese",
  玉: "Jade",
  皇: "Kaiser",
  尊: "Ehre",
  玄: "mysteriös",
  穹: "Kuppel",
  帝: "Kaiser",
  一: "eins",
  日: "Tag",
  驾: "fahren",
  坐: "sitzen",
  金: "Gold",
  阙: "Que",
  云: "Wolke",
  宫: "Palast",
  灵: "Geist",
  霄: "Himmel",
  宝: "wertvoll",
  殿: "Tempel",
  聚: "Versammeln",
  集: "Satz",
  文: "Künste",
  武: "Wu",
  仙: "Fee",
  卿: "Du",
  早: "Morgen",
  朝: "in Richtung",
  之: "Von",
  际: "International",
  忽: "plötzlich",
  有: "haben",
  邱: "Qiu",
  弘: "Hong",
  济: "Ji",
  真: "real",
  人: "Menschen",
  奏: "Spielen",
  道: "Straße",
  万: "Zehntausend",
  岁: "Alter",
  通: "Passieren",
  明: "hell",
  外: "draußen",
  东: "Ost",
  海: "Ozean",
  龙: "Drachen",
  王: "König",
  敖: "Ao",
  广: "breit",
  进: "Eingeben",
  听: "Hören",
  宣: "Förderung",
  诏: "Kaiserlich",
  传: "passieren",
  旨: "Zweck",
  着: "Setzen",
  来: "Kommen",
  至: "Zu",
  下: "Runter",
  礼: "gegenwärtig",
  拜: "Tschüss",
  毕: "vollständig",
  旁: "neben",
  引: "führen",
  童: "Kind",
  接: "fangen",
  从: "aus",
  头: "Kopf",
  看: "sehen",
  过: "Passieren",
  曰: "sagen",
  水: "Wasser",
  元: "Yuan",
  界: "Grenze",
  胜: "Gewinnen",
  神: "Gott",
  洲: "Kontinent",
  小: "Klein",
  臣: "Minister",
  主: "Gastgeber",
  君: "Jun",
  近: "schließen",
  因: "Weil",
  花: "Blume",
  果: "Obst",
  山: "Berg",
  生: "geboren",
  帘: "Vorhang",
  洞: "Loch",
  住: "live",
  妖: "Dämon",
  孙: "Sonne",
  悟: "Aufklärung",
  空: "NULL",
  欺: "schikanieren",
  虐: "Missbräuchlich",
  强: "kraftvoll",
  宅: "Heim",
  索: "Suchen",
  兵: "Soldat",
  器: "Gerät",
  施: "Shi",
  法: "Gesetz",
  威: "Viagra",
  要: "wollen",
  披: "路",
  挂: "aufhängen",
  骋: "Rollen",
  凶: "erbittert",
  势: "Stabilität",
  惊: "Schock",
  伤: "verletzt",
  族: "Familie",
  唬: "Narr",
  走: "Gehen",
  龟: "Schildkröte",
  鼍: "Schildkröte",
  南: "Süden",
  战: "Krieg",
  兢: "Jungfräulichkeit",
  西: "West",
  凄: "traurig",
  惨: "miserabel",
  北: "Norden",
  缩: "Schrumpfen",
  首: "Kopf",
  归: "Nach Hause gehen",
  降: "fallen",
  舒: "Süß",
  身: "Körper",
  献: "Angebot",
  珍: "Jen",
  铁: "Eisen",
  棒: "Großartig",
  凤: "Phönix",
  翅: "Flügel",
  冠: "Krone",
  与: "Und",
  锁: "Sperren",
  子: "Sohn",
  甲: "Erste",
  步: "Schritt",
  履: "Schuh",
  以: "von",
  送: "liefern",
  出: "aus",
  他: "Er",
  仍: "Trotzdem",
  弄: "Gasse",
  艺: "Kunst",
  显: "Zeigen",
  但: "Aber",
  聒: "Hohl",
  噪: "Lärm",
  然: "Natürlich",
  无: "keiner",
  敌: "Feind",
  甚: "sehr",
  为: "für",
  难: "Katastrophe",
  制: "System",
  今: "Jetzt",
  伏: "Fu",
  望: "sehen",
  裁: "Schneiden",
  恳: "Hoffnung",
  乞: "bitten",
  收: "erhalten",
  此: "Das",
  孽: "teuflisch",
  庶: "Still",
  使: "machen",
  岳: "Yue",
  清: "klar",
  宁: "eher",
  安: "installieren",
  泰: "Thai",
  奉: "Feng",
  览: "Sicht",
  回: "Zurück",
  朕: "ICH",
  即: "Im Augenblick",
  遣: "Schicken",
  将: "Wille",
  擒: "erfassen",
  拿: "nehmen",
  老: "alt",
  顿: "Dun",
  谢: "Danke",
  去: "gehen",
  面: "Nudel",
  又: "wieder",
  葛: "Germa",
  翁: "Yeon",
  师: "Division",
  冥: "tief",
  司: "verwalten",
  秦: "Qin",
  赍: "Mit",
  幽: "ruhig",
  教: "unterrichten",
  地: "Land",
  藏: "Tibetaner",
  菩: "Bodhisattva",
  萨: "Sa",
  言: "Wort",
  女: "weiblich",
  亦: "sowie",
  境: "Gebiet",
  乃: "Also",
  阴: "Negativ",
  而: "Und",
  鬼: "Geist",
  阳: "Positiv",
  转: "ändern",
  轮: "Rad",
  禽: "Vögel",
  兽: "Tier",
  死: "sterben",
  反: "Gegenteil",
  复: "Komplex",
  雌: "weiblich",
  雄: "männlich",
  化: "ändern",
  孕: "schwanger",
  成: "werden",
  男: "männlich",
  自: "seit",
  数: "Nummer",
  不: "NEIN",
  能: "fähig",
  易: "einfach",
  也: "Auch",
  廉: "kostengünstig",
  产: "Produzieren",
  猴: "Affe",
  逞: "Befriedigt",
  行: "OK",
  服: "Kleidung",
  拘: "verhaften",
  唤: "Anruf",
  打: "schlagen",
  绝: "Absolute",
  九: "Neun",
  恃: "verlassen",
  力: "Gewalt",
  十: "zehn",
  代: "Generation",
  闹: "Wütend",
  罗: "Luo",
  森: "南",
  销: "Stift",
  名: "Name",
  号: "Nummer",
  致: "Zu",
  属: "Generisches",
  类: "Art",
  猕: "Makaken",
  畜: "Vieh",
  多: "viele",
  寿: "Leben",
  寂: "einsam",
  灭: "Löschen",
  各: "jede",
  贫: "arm",
  僧: "Mönch",
  具: "Werkzeug",
  冒: "Geboren",
  渎: "Graben",
  调: "Anpassen",
  整: "alle",
  理: "Grund",
  永: "für immer",
  府: "Haus",
  谨: "Vorsichtig sein",
  众: "Alle",
  问: "fragen",
  这: "Das",
  是: "Ja",
  几: "Mehrere",
  年: "Jahr",
  育: "Ausbildung",
  何: "Was",
  就: "Auf einmal",
  般: "Normal",
  未: "Noch nicht",
  已: "bereits",
  班: "Klasse",
  中: "Mitte",
  闪: "Blitz",
  千: "tausend",
  里: "innen",
  眼: "Auge",
  顺: "Sicher",
  风: "Wind",
  耳: "Ohr",
  三: "drei",
  百: "Hundert",
  前: "nach vorne",
  石: "Stein",
  当: "Wann",
  时: "Stunde",
  知: "Wissen",
  在: "existieren",
  方: "Quadrat",
  修: "bauen",
  炼: "Verfeinerung",
  虎: "Tiger",
  籍: "Mitgliedschaft",
  路: "Straße",
  太: "zu",
  白: "Weiß",
  长: "lang",
  庚: "Geng",
  星: "Stern",
  俯: "Absteigen",
  凡: "Beliebig",
  窍: "Tipps",
  皆: "alle",
  可: "Kann",
  奈: "Nye",
  体: "Körper",
  月: "Mond",
  顶: "Spitze",
  露: "Tau",
  餐: "Mahlzeit",
  霞: "Xia",
  既: "Nun das",
  异: "anders",
  哉: "Ja",
  陛: "Dein",
  念: "lesen",
  恩: "Freundlichkeit",
  招: "Trick",
  把: "Bündeln",
  届: "Kapitel",
  授: "Gewähren",
  官: "offiziell",
  职: "Arbeit",
  箓: "Talisman",
  束: "bündeln",
  间: "zwischen",
  若: "wie",
  受: "von",
  命: "Leben",
  后: "zurück",
  再: "Wieder",
  升: "Aufzug",
  赏: "belohnen",
  违: "Verstoß",
  则: "Aber",
  动: "bewegen",
  劳: "Arbeit",
  二: "zwei",
  闻: "Geruch",
  喜: "Glück",
  依: "entsprechend",
  所: "Ort",
  曲: "Lied",
};

const translations_fr = {
  却: "mais",
  表: "surface",
  启: "commencer",
  那: "Que",
  个: "autonome",
  高: "haut",
  天: "ciel",
  上: "supérieur",
  圣: "Saint",
  大: "grand",
  慈: "CI",
  仁: "Bienveillance",
  者: "Ceux",
  玉: "Jade",
  皇: "Empereur",
  尊: "Honneur",
  玄: "mystérieux",
  穹: "Dôme",
  帝: "empereur",
  一: "un",
  日: "jour",
  驾: "conduire",
  坐: "s'asseoir",
  金: "or",
  阙: "Que ce soit",
  云: "nuage",
  宫: "palais",
  灵: "esprit",
  霄: "Ciel",
  宝: "précieux",
  殿: "temple",
  聚: "Rassembler",
  集: "ensemble",
  文: "arts",
  武: "Wu",
  仙: "Fée",
  卿: "Toi",
  早: "matin",
  朝: "vers",
  之: "De",
  际: "International",
  忽: "soudainement",
  有: "avoir",
  邱: "Qiu",
  弘: "Hong",
  济: "Ji",
  真: "réel",
  人: "personnes",
  奏: "Jouer",
  道: "route",
  万: "Dix mille",
  岁: "âge",
  通: "Passer",
  明: "brillant",
  外: "dehors",
  东: "Est",
  海: "océan",
  龙: "dragon",
  王: "roi",
  敖: "AO",
  广: "large",
  进: "Entrer",
  听: "écouter",
  宣: "Promotion",
  诏: "Impérial",
  传: "passer",
  旨: "but",
  着: "Mettre",
  来: "Viens",
  至: "à",
  下: "Vers le bas",
  礼: "présent",
  拜: "au revoir",
  毕: "complet",
  旁: "à côté de",
  引: "plomb",
  童: "enfant",
  接: "attraper",
  从: "depuis",
  头: "tête",
  看: "regarder",
  过: "Passer",
  曰: "dire",
  水: "eau",
  元: "Yuan",
  界: "limite",
  胜: "Gagner",
  神: "Dieu",
  洲: "Continent",
  小: "Petit",
  臣: "ministre",
  主: "hôte",
  君: "Juin",
  近: "fermer",
  因: "parce que",
  花: "fleur",
  果: "fruit",
  山: "Montagne",
  生: "né",
  帘: "rideau",
  洞: "Trou",
  住: "en direct",
  妖: "Démon",
  孙: "Soleil",
  悟: "Éclaircissement",
  空: "nul",
  欺: "intimidateur",
  虐: "Injurieux",
  强: "puissant",
  宅: "Maison",
  索: "Recherche",
  兵: "Soldat",
  器: "Appareil",
  施: "Shi",
  法: "Loi",
  威: "Viagra",
  要: "vouloir",
  披: "路",
  挂: "accrocher",
  骋: "Rouler",
  凶: "féroce",
  势: "Stabilité",
  惊: "choc",
  伤: "blesser",
  族: "Famille",
  唬: "idiot",
  走: "Marcher",
  龟: "tortue",
  鼍: "tortue",
  南: "Sud",
  战: "guerre",
  兢: "Virginité",
  西: "Ouest",
  凄: "triste",
  惨: "misérable",
  北: "nord",
  缩: "Rétrécir",
  首: "tête",
  归: "Rentrer chez eux",
  降: "baisse",
  舒: "Doux",
  身: "corps",
  献: "offre",
  珍: "Jen",
  铁: "fer",
  棒: "Super",
  凤: "phénix",
  翅: "aile",
  冠: "couronne",
  与: "et",
  锁: "Verrouillage",
  子: "fils",
  甲: "D'abord",
  步: "étape",
  履: "chaussure",
  以: "par",
  送: "livrer",
  出: "dehors",
  他: "il",
  仍: "toujours",
  弄: "ruelle",
  艺: "art",
  显: "Montrer",
  但: "mais",
  聒: "Creux",
  噪: "bruit",
  然: "Bien sûr",
  无: "aucun",
  敌: "ennemi",
  甚: "très",
  为: "pour",
  难: "Catastrophe",
  制: "système",
  今: "maintenant",
  伏: "Fu",
  望: "voir",
  裁: "Couper",
  恳: "Espoir",
  乞: "mendier",
  收: "recevoir",
  此: "ce",
  孽: "mal",
  庶: "Silencieux",
  使: "faire",
  岳: "Yue",
  清: "clair",
  宁: "plutôt",
  安: "installer",
  泰: "thaïlandais",
  奉: "Feng",
  览: "Voir",
  回: "Dos",
  朕: "je",
  即: "Tout de suite",
  遣: "Envoyer",
  将: "Volonté",
  擒: "capturer",
  拿: "prendre",
  老: "vieux",
  顿: "Dun",
  谢: "Merci",
  去: "aller",
  面: "nouille",
  又: "encore",
  葛: "Germa",
  翁: "Yeon",
  师: "division",
  冥: "profond",
  司: "gérer",
  秦: "Qin",
  赍: "Avec",
  幽: "calme",
  教: "enseigner",
  地: "atterrir",
  藏: "Tibétain",
  菩: "Bodhisattva",
  萨: "SA",
  言: "Mot",
  女: "femelle",
  亦: "ainsi que",
  境: "territoire",
  乃: "Donc",
  阴: "Négatif",
  而: "et",
  鬼: "fantôme",
  阳: "Positif",
  转: "changement",
  轮: "roue",
  禽: "oiseaux",
  兽: "bête",
  死: "mourir",
  反: "opposé",
  复: "complexe",
  雌: "femelle",
  雄: "mâle",
  化: "changement",
  孕: "enceinte",
  成: "devenir",
  男: "mâle",
  自: "depuis",
  数: "nombre",
  不: "Non",
  能: "capable",
  易: "facile",
  也: "aussi",
  廉: "peu coûteux",
  产: "Produire",
  猴: "singe",
  逞: "Satisfait",
  行: "D'ACCORD",
  服: "Vêtements",
  拘: "arrêter",
  唤: "Appel",
  打: "battre",
  绝: "Absolu",
  九: "Neuf",
  恃: "compter sur",
  力: "forcer",
  十: "dix",
  代: "génération",
  闹: "Furieux",
  罗: "Luo",
  森: "南",
  销: "épingle",
  名: "nom",
  号: "Nombre",
  致: "À",
  属: "Générique",
  类: "gentil",
  猕: "macaque",
  畜: "bétail",
  多: "beaucoup",
  寿: "vie",
  寂: "solitaire",
  灭: "Éteindre",
  各: "chaque",
  贫: "pauvre",
  僧: "moine",
  具: "Outil",
  冒: "Né",
  渎: "fossé",
  调: "Ajuster",
  整: "tous",
  理: "raison",
  永: "pour toujours",
  府: "Maison",
  谨: "Être prudent",
  众: "Tous",
  问: "demander",
  这: "ce",
  是: "Oui",
  几: "Plusieurs",
  年: "Année",
  育: "Éducation",
  何: "quoi",
  就: "Immédiatement",
  般: "Normale",
  未: "pas encore",
  已: "déjà",
  班: "classe",
  中: "milieu",
  闪: "éclair",
  千: "mille",
  里: "à l'intérieur",
  眼: "Œil",
  顺: "Bien sûr",
  风: "vent",
  耳: "Oreille",
  三: "trois",
  百: "Cent",
  前: "avant",
  石: "pierre",
  当: "quand",
  时: "heure",
  知: "Savoir",
  在: "exister",
  方: "carré",
  修: "construire",
  炼: "Raffinage",
  虎: "Tigre",
  籍: "adhésion",
  路: "route",
  太: "aussi",
  白: "blanc",
  长: "long",
  庚: "Geng",
  星: "étoile",
  俯: "Descendre",
  凡: "N'importe lequel",
  窍: "Conseils",
  皆: "tous",
  可: "Peut",
  奈: "Nye",
  体: "corps",
  月: "lune",
  顶: "haut",
  露: "rosée",
  餐: "repas",
  霞: "Xia",
  既: "maintenant que",
  异: "différent",
  哉: "Oui",
  陛: "Ton",
  念: "lire",
  恩: "gentillesse",
  招: "astuce",
  把: "Paquet",
  届: "Chapitre",
  授: "Accorder",
  官: "officiel",
  职: "Emploi",
  箓: "Talisman",
  束: "paquet",
  间: "entre",
  若: "comme",
  受: "par",
  命: "vie",
  后: "dos",
  再: "Encore",
  升: "Ascenseur",
  赏: "récompense",
  违: "Violation",
  则: "mais",
  动: "se déplacer",
  劳: "travail",
  二: "deux",
  闻: "odeur",
  喜: "bonheur",
  依: "selon",
  所: "Lieu",
  曲: "chanson",
};

const tianwen_translation_map_en = {
  却表启那个高天上圣大慈仁者玉皇大天尊玄穹高上帝:
    "But it expresses the great saint, great compassionate and kind Jade Emperor, the Great Heavenly Lord, Xuanqiong,",
  一日: "One day",
  驾坐金阙云宫灵霄宝殿:
    "Driving in the Jinque Yun Palace Lingxiao Treasure Hall",
  聚集文武仙卿早朝之际:
    "Gathering the morning court of the civil and military immortals",
  忽有邱弘济真人启奏道: "Suddenly, Qiu Hongji's real person started the speech",
  万岁: "Long live",
  通明殿外: "Outside the Tongming Hall",
  有东海龙王敖广进表:
    "The East China Sea Dragon King Ao Guang has entered the report",
  听天尊宣诏: "Listen to the decree of the Heavenly Lord",
  玉皇传旨: "The Jade Emperor's Imperial",
  着宣来: "Let's go",
  敖广宣至灵霄殿下: "Ao Guangxuan arrived at His Highness Lingxiao",
  礼拜毕: "After the week",
  旁有引奏仙童: "There is a fairy boy next to it",
  接上表文: "Continue with the above table",
  玉皇从头看过: "Jade Emperor has seen it from the beginning",
  表曰: "The",
  水元下界东胜神洲东海小龙臣敖广启奏大天圣主玄穹高上帝君:
    "The Shuiyuan Lower Realm Dongsheng Shenzhou East Sea Little Dragon Minister Ao Guang made a speech to the Great Heavenly Holy Lord Xuanqiong Gaodi Lord",
  近因花果山生: "Recent cause of flower fruit mountain",
  水帘洞住妖仙孙悟空者:
    "The demon immortal Sun Wukong is in the water curtain cave",
  欺虐小龙: "Bully the dragon",
  强坐水宅: "Strongly sit in a water house",
  索兵器: "Recruiting weapons",
  施法施威: "Cast spells and powers",
  要披挂: "Want to be hung",
  骋凶骋势: "A vicious roaming",
  惊伤水族: "Shocked aquarium",
  唬走龟鼍: "Bluff away the turtle",
  南海龙战战兢兢: "The South China Sea Dragon is trembling with fear",
  西海龙凄凄惨惨: "The West Sea Dragon is miserable",
  北海龙缩首归降: "The North Sea Dragon Retreats",
  臣敖广舒身下拜: "Ao Guangshu bowed under him",
  献神珍之铁棒: "Offering the Iron Stick of the Divine Treasure",
  凤翅之金冠: "Phoenix Wings Golden Crown",
  与那锁子甲: "With that chain armor",
  步云履: "Bu Yunlu",
  以礼送出: "Gift with gifts",
  他仍弄武艺: "He still works in martial arts",
  显神通: "Showing magical powers",
  但云聒噪: "But the clouds are noisy",
  聒噪: "Noisy",
  果然无敌: "Sure enough, invincible",
  甚为难制: "Very difficult to control",
  臣今启奏: "I'm going to report now",
  伏望圣裁: "Hope Saint",
  恳乞天兵: "Beg for the Heavenly Soldier",
  收此妖孽: "Take this monster",
  庶使海岳清宁: "To make the sea and the mountain calm",
  下元安泰: "Xiayuan Antai",
  奉奏: "Comment",
  圣帝览毕: "The Holy Emperor has read",
  传旨: "deliver an imperial order",
  着龙神回海: "Go back to the sea with dragon god",
  朕即遣将擒拿: "I will send the general to capture it",
  老龙王顿首谢去: "The old dragon king bowed his head and thanked him",
  下面又有葛仙翁天师启奏道:
    "Below is the recitation of the Heavenly Master Ge Xianweng",
  万岁: "Long live",
  有冥司秦广王赍奉幽冥教主地藏王菩萨表文进上:
    "A king of Qin Guang of the Underworld brought a message to the Bodhisattva Ksitigarbha Bodhisattva of the Underworld",
  旁有传言玉女: "There is a rumor next to the jade girl",
  接上表文: "Continue with the above table",
  玉皇亦从头看过: "The Jade Emperor also looked at it from the beginning",
  表曰: "The",
  幽冥境界: "Netherworld",
  乃地之阴司: "It is the Yin Si of the Earth",
  天有神而地有鬼: "There are gods in heaven and ghosts in earth",
  阴阳转轮: "Yin-Yang Wheel",
  禽有生而兽有死: "Birds are born and beasts are dead",
  反复雌雄: "Repeated male and female",
  生生化化: "Biochemical",
  孕女成男: "Pregnant women become male",
  此自然之数: "This natural number",
  不能易也: "Not easy",
  今有花果山水廉洞天产妖猴孙悟空:
    "There are now flowers, fruits, mountains, rivers, Liandong, and the demon monkeys produced by Sun Wukong",
  逞强行凶: "Being arrogant",
  不服拘唤: "Not accepting",
  弄神通: "Enjoy supernatural powers",
  打绝九幽鬼使: "Fight the Nine Nether Ghosts",
  恃势力: "Rely on power",
  惊伤十代慈王: "Shocked and hurt the ten generations of Ci Wang",
  大闹罗森: "Rosen",
  强销名号: "Strong sale name",
  致使猴属之类无拘: "Made the monkey and other unrestrained",
  猕猴之畜多寿: "Macaques live a long life",
  寂灭轮回: "Nirvana",
  各无生死: "No life or death",
  贫僧具表: "I am a monk's table",
  冒渎天威: "Mao Du Tianwei",
  伏乞调遣神兵: "Fuqi dispatches the magical soldiers",
  收降此妖: "Stop this monster",
  整理阴阳: "Organize Yin and Yang",
  永安地府: "Yong'an Underground",
  谨奏: "Be careful",
  玉皇览毕: "Jade Emperor View",
  传旨: "deliver an imperial order",
  着冥君回归地府: "Return to the Underworld with the King",
  朕即遣将擒拿: "I will send the general to capture it",
  秦广王亦顿首谢去: "King Qin Guang also bowed his head and left",
  大天尊宣众文武仙卿:
    "The Great Heavenly Lord Xuan of the Civil and Military Immortals",
  问曰: "Asked",
  这妖猴是几年生育: "How many years has this monster been born",
  何代出生: "When was born",
  却就这般有道: "But it's just so true",
  一言未已: "Not a word",
  班中闪出千里眼: "A thousand miles of eyes flashed in the class",
  顺风耳道: "Shunwind ear canal",
  这猴乃三百年前天产石猴:
    "This monkey was born three hundred years ago in the sky.",
  当时不以为然: "Didn't think so at that time",
  不知这几年在何方修炼成仙:
    "I don't know where to become an immortal in the past few years",
  降龙伏虎: "Subduing dragons and subduing tigers",
  强销死籍也: "Forced death",
  玉帝道: "Jade Emperor's Way",
  那路神将下界收伏:
    "The gods of the road are coming down to the realm and conquer them",
  言未已: "Not finished speaking",
  班中闪出太白长庚星: "Taibai Chang Geng Star flashed in the class",
  俯首启奏道: "Depressed to start the track",
  上圣三界中: "In the Three Realms of the Supreme Holy",
  凡有九窍者: "Anyone with nine orifices",
  皆可修仙: "All can cultivate immortals",
  奈此猴乃天地育成之体: "But this monkey is the body of heaven and earth",
  日月孕就之身: "The body of the sun and moon pregnancy",
  他也顶天履地: "He also walks to the sky and the earth",
  服露餐霞: "Take a meal with a sausage",
  今既修成仙道: "Now, I have cultivated the path of immortality",
  有降龙伏虎之能: "Have the ability to subdue dragons and tigers",
  与人何以异哉: "How different from others",
  臣启陛下: "Your Majesty",
  可念生化之慈恩: "Can you think of the kindness of life and transformation",
  降一道招安圣旨: "An imperial edict",
  把他宣来上届: "Promote him to the last session",
  授他一个大小官职: "Give him a large and small official position",
  与他籍名在箓: "With other names",
  拘束此间: "Restrict this",
  若受天命: "If you are destined to heaven",
  后再升赏: "Rewards later",
  若违天命: "If you violate the will of heaven",
  就此擒拿: "Capture it",
  一则不动众劳师: "One way to do nothing to do",
  二则收仙有道也: "Second, there is a way to collect immortals",
  玉帝闻言甚喜: "The Jade Emperor was very happy when he heard this",
  道: "road",
  依卿所奏: "According to your report",
  即着文曲星官修诏: "Immediately wrote the Wenqu Star Official's Imperial",
  着太白金星招安: "Too Bai Venus Star to attract help",
};

const tianwen_translation_map_de = {
  却表启那个高天上圣大慈仁者玉皇大天尊玄穹高上帝:
    "Aber es drückt den großen Heiligen, großen mitfühlenden und freundlichen Jade -Kaiser, den großen himmlischen Herrn, Xuanqiong, aus",
  一日: "Einmal",
  驾坐金阙云宫灵霄宝殿: "Fahren im Jinque Yun Palace Lingxiao Treasure Hall",
  聚集文武仙卿早朝之际:
    "Sammeln des Morgengerichts des zivilen und militärischen Unsterblichen",
  忽有邱弘济真人启奏道: "Plötzlich begann Qiu Hongjis wahre Person die Rede",
  万岁: "Es lebe",
  通明殿外: "Außerhalb der Sträuchenhalle",
  有东海龙王敖广进表:
    "Der Ostchinesische Drachenkönig Ao Guang hat in den Bericht eingetragen",
  听天尊宣诏: "Hören Sie auf das Dekret des himmlischen Herrn",
  玉皇传旨: "Der kaiserliche Jade Kaiser",
  着宣来: "Lass uns gehen",
  敖广宣至灵霄殿下: "Ao Guangxuan kam bei seiner Hoheit Lingxiao an",
  礼拜毕: "Nach der Woche",
  旁有引奏仙童: "Es gibt einen Märchenjunge daneben",
  接上表文: "Fahren Sie mit der obigen Tabelle fort",
  玉皇从头看过: "Jade Kaiser hat es von Anfang an gesehen",
  表曰: "Der",
  水元下界东胜神洲东海小龙臣敖广启奏大天圣主玄穹高上帝君:
    "Der Shuiyuan Lower Realm Dongsheng Shenzhou Ostsee Der kleine Drachenminister Ao Guang hielt eine Rede vor dem großen himmlischen heiligen Herrn Xuanqiong Gaodi Lord",
  近因花果山生: "Jüngste Ursache für Blumenfruchtberg",
  水帘洞住妖仙孙悟空者:
    "Der dämone unsterbliche Sonne Wukong befindet sich in der Wasservorhanghöhle",
  欺虐小龙: "Mobber den Drachen",
  强坐水宅: "Setzen Sie stark in einem Wasserhaus",
  索兵器: "Waffen rekrutieren",
  施法施威: "Zauber und Kräfte werfen",
  要披挂: "Will aufgehängt werden",
  骋凶骋势: "Ein bösartiges Durchstreik",
  惊伤水族: "Schockiertes Aquarium",
  唬走龟鼍: "Bluff die Schildkröte wegbluffen",
  南海龙战战兢兢: "Der Drache des Südchinesischen Meeres zittert vor Angst",
  西海龙凄凄惨惨: "Der Westmeerdrache ist unglücklich",
  北海龙缩首归降: "Die Nordsee -Drachen räumen",
  臣敖广舒身下拜: "Ao Guangshu verbeugte sich unter ihm",
  献神珍之铁棒: "Bieten Sie den Eisenstab des göttlichen Schatzes an",
  凤翅之金冠: "Phoenix Wings Golden Crown",
  与那锁子甲: "Mit dieser Kettenpanzerung",
  步云履: "Bu yunlu",
  以礼送出: "Geschenk mit Geschenken",
  他仍弄武艺: "Er arbeitet immer noch in Kampfkunst",
  显神通: "Magische Kräfte zeigen",
  但云聒噪: "Aber die Wolken sind laut",
  聒噪: "Laut",
  果然无敌: "Sicher genug, unbesiegbar",
  甚为难制: "Sehr schwer zu kontrollieren",
  臣今启奏: "Ich werde jetzt melden",
  伏望圣裁: "Hoffnung Saint",
  恳乞天兵: "Biete um den himmlischen Soldaten",
  收此妖孽: "Nehmen Sie dieses Monster",
  庶使海岳清宁: "Das Meer und den Berg ruhig machen",
  下元安泰: "XIAYUAN ANTAI",
  奉奏: "Kommentar",
  圣帝览毕: "Der Heilige Kaiser hat gelesen",
  传旨: "Liefern Sie eine imperiale Ordnung",
  着龙神回海: "Gehen Sie mit Drachengott zurück zum Meer",
  朕即遣将擒拿: "Ich werde den General schicken, um ihn zu erfassen",
  老龙王顿首谢去: "Der alte Drachenkönig senkte den Kopf und dankte ihm",
  下面又有葛仙翁天师启奏道:
    "Unten ist die Rezitation des himmlischen Meisters Ge Xianweng",
  万岁: "Es lebe",
  有冥司秦广王赍奉幽冥教主地藏王菩萨表文进上:
    "Ein König von Qin Guang von der Unterwelt brachte die Bodhisattva Ksiitigarbha Bodhisattva der Unterwelt ein",
  旁有传言玉女: "Neben dem Jade -Mädchen gibt es ein Gerücht",
  接上表文: "Fahren Sie mit der obigen Tabelle fort",
  玉皇亦从头看过: "Der Jade -Kaiser sah es sich auch von Anfang an an",
  表曰: "Der",
  幽冥境界: "Netherworld",
  乃地之阴司: "Es ist der Yin Si der Erde",
  天有神而地有鬼: "Es gibt Götter im Himmel und Geister auf der Erde",
  阴阳转轮: "Yin-Yang-Rad",
  禽有生而兽有死: "Vögel werden geboren und Bestien sind tot",
  反复雌雄: "Wiederholte männliche und weibliche",
  生生化化: "Biochemisch",
  孕女成男: "Schwangere werden männlich",
  此自然之数: "Diese natürliche Zahl",
  不能易也: "Nicht einfach",
  今有花果山水廉洞天产妖猴孙悟空:
    "Es gibt jetzt Blumen, Früchte, Berge, Flüsse, Liandong und die von Sun Wukong produzierten Dämonenaffen",
  逞强行凶: "Arrogant sein",
  不服拘唤: "Nicht akzeptieren",
  弄神通: "Genießen Sie übernatürliche Kräfte",
  打绝九幽鬼使: "Bekämpfen Sie die neun Untergeister",
  恃势力: "Sich auf Macht verlassen",
  惊伤十代慈王: "Schockiert und verletzte die zehn Generationen von CI Wang",
  大闹罗森: "Rosen",
  强销名号: "Starker Verkaufsname",
  致使猴属之类无拘: "Machte den Affen und andere ungezügelte",
  猕猴之畜多寿: "Makaken führen ein langes Leben",
  寂灭轮回: "Nirwana",
  各无生死: "Kein Leben oder Tod",
  贫僧具表: "Ich bin ein Mönchstisch",
  冒渎天威: "Mao du Tianwei",
  伏乞调遣神兵: "Fuqi schickt die magischen Soldaten",
  收降此妖: "Stoppen Sie dieses Monster",
  整理阴阳: "Organisieren Yin und Yang",
  永安地府: "Yong'an unterirdisch",
  谨奏: "Seien Sie vorsichtig",
  玉皇览毕: "Jade Kaiseransicht",
  传旨: "Liefern Sie eine imperiale Ordnung",
  着冥君回归地府: "Kehre mit dem König in die Unterwelt zurück",
  朕即遣将擒拿: "Ich werde den General schicken, um ihn zu erfassen",
  秦广王亦顿首谢去:
    "König Qin Guang beugte sich ebenfalls mit dem Kopf und ging",
  大天尊宣众文武仙卿:
    "Der große himmlische Herr Xuan des zivilen und militärischen Unsterblichen",
  问曰: "Gefragt",
  这妖猴是几年生育: "Wie viele Jahre wurde dieses Monster geboren?",
  何代出生: "Wann wurde geboren",
  却就这般有道: "Aber es ist einfach so wahr",
  一言未已: "Kein Wort",
  班中闪出千里眼: "In der Klasse blitzten tausend Meilen von Augen auf",
  顺风耳道: "Müdschind -Gehörgang",
  这猴乃三百年前天产石猴:
    "Dieser Affe wurde vor dreihundert Jahren am Himmel geboren.",
  当时不以为然: "Ich habe das damals nicht gedacht",
  不知这几年在何方修炼成仙:
    "Ich weiß nicht, wo ich in den letzten Jahren ein Unsterbliches werden soll",
  降龙伏虎: "Drachen und Subdoing -Tiger unterwerfen",
  强销死籍也: "Erzwungener Tod",
  玉帝道: "Jade Kaiser Weg",
  那路神将下界收伏: "Die Straßengötter kommen zum Reich und erobern sie",
  言未已: "Nicht fertig mit dem Sprechen",
  班中闪出太白长庚星: "Taibai Chang Geng Star blitzte in der Klasse auf",
  俯首启奏道: "Depressiv, um die Strecke zu starten",
  上圣三界中: "In den drei Bereichen des höchsten Heiligen",
  凡有九窍者: "Jeder mit neun Öffnungen",
  皆可修仙: "Alle können Unsterbliche kultivieren",
  奈此猴乃天地育成之体:
    "Aber dieser Affe ist der Körper des Himmels und der Erde",
  日月孕就之身: "Der Körper der Sonne und der Mondschwangerschaft",
  他也顶天履地: "Er geht auch zum Himmel und die Erde",
  服露餐霞: "Nehmen Sie eine Mahlzeit mit einer Wurst",
  今既修成仙道: "Jetzt habe ich den Weg der Unsterblichkeit kultiviert",
  有降龙伏虎之能: "Die Fähigkeit haben, Drachen und Tiger zu unterwerfen",
  与人何以异哉: "Wie anders von anderen",
  臣启陛下: "Eure Majestät",
  可念生化之慈恩:
    "Können Sie sich die Freundlichkeit des Lebens und der Transformation vorstellen?",
  降一道招安圣旨: "Ein kaiserliches Edikt",
  把他宣来上届: "Befördere ihn in die letzte Sitzung",
  授他一个大小官职: "Geben Sie ihm eine große und kleine offizielle Position",
  与他籍名在箓: "Mit anderen Namen",
  拘束此间: "Beschränken dies",
  若受天命: "Wenn Sie zum Himmel bestimmt sind",
  后再升赏: "Belohnungen später",
  若违天命: "Wenn Sie den Willen des Himmels verletzen",
  就此擒拿: "Erfassen Sie es",
  一则不动众劳师: "Eine Möglichkeit, nichts zu tun zu tun",
  二则收仙有道也: "Zweitens gibt es eine Möglichkeit, Unsterbliche zu sammeln",
  玉帝闻言甚喜: "Der Jade -Kaiser war sehr glücklich, als er das hörte",
  道: "Straße",
  依卿所奏: "Laut Ihrem Bericht",
  即着文曲星官修诏: "Schrieb sofort den Imperial des Wenqu Star -Beamten",
  着太白金星招安: "Zu bai venus star, um Hilfe anzulocken",
};

const tianwen_translation_map_fr = {
  却表启那个高天上圣大慈仁者玉皇大天尊玄穹高上帝:
    "Mais il exprime le grand saint, grand compassion et bon empereur de jade, le grand Seigneur céleste, Xuanqiong,",
  一日: "Un jour",
  驾坐金阙云宫灵霄宝殿:
    "Conduire dans la salle de trésor Lingxiao Jinque Yun Palace",
  聚集文武仙卿早朝之际:
    "Rassembler la cour du matin des immortels civils et militaires",
  忽有邱弘济真人启奏道:
    "Soudain, la vraie personne de Qiu Hongji a commencé le discours",
  万岁: "Vivre en vie",
  通明殿外: "À l'extérieur du Tongming Hall",
  有东海龙王敖广进表:
    "Le roi du dragon de la mer de la Chine orientale Ao Guang est entré dans le rapport",
  听天尊宣诏: "Écoutez le décret du Seigneur céleste",
  玉皇传旨: "L'impérial de l'empereur Jade",
  着宣来: "Allons-y",
  敖广宣至灵霄殿下: "Ao Guangxuan est arrivé à son Altesse Lingxiao",
  礼拜毕: "Après la semaine",
  旁有引奏仙童: "Il y a un fée-garçon à côté",
  接上表文: "Continuez avec la table ci-dessus",
  玉皇从头看过: "Jade Emperor l'a vu depuis le début",
  表曰: "Le",
  水元下界东胜神洲东海小龙臣敖广启奏大天圣主玄穹高上帝君:
    "Le royaume inférieur du huiyuan Dongsheng Shenzhou East Sea Little Dragon Ministre Ao Guang a fait un discours au Grand Saint-Sainte-Seigneur céleste Xuanqiong Gaodi Seigneur",
  近因花果山生: "Cause récente de Flower Fruit Mountain",
  水帘洞住妖仙孙悟空者:
    "Le démon immortel Sun Wukong est dans la grotte du rideau d'eau",
  欺虐小龙: "Intimider le dragon",
  强坐水宅: "S'asseoir fortement dans une maison d'eau",
  索兵器: "Recruter des armes",
  施法施威: "Lancer des sorts et des pouvoirs",
  要披挂: "Veux être accroché",
  骋凶骋势: "Un itinéraire vicieux",
  惊伤水族: "Aquarium choqué",
  唬走龟鼍: "Bluff loin de la tortue",
  南海龙战战兢兢: "Le dragon de la mer de Chine méridionable tremble de peur",
  西海龙凄凄惨惨: "Le dragon de la mer Ouest est misérable",
  北海龙缩首归降: "Le dragon de la mer du Nord se retrouve",
  臣敖广舒身下拜: "Ao Guangshu s'est incliné sous lui",
  献神珍之铁棒: "Offrir le bâton de fer du trésor divin",
  凤翅之金冠: "Phoenix Wings Golden Crown",
  与那锁子甲: "Avec cette armure de chaîne",
  步云履: "Bu yunlu",
  以礼送出: "Cadeau avec des cadeaux",
  他仍弄武艺: "Il travaille toujours dans les arts martiaux",
  显神通: "Montrant des pouvoirs magiques",
  但云聒噪: "Mais les nuages ​​sont bruyants",
  聒噪: "Bruyant",
  果然无敌: "Effectivement, invincible",
  甚为难制: "Très difficile à contrôler",
  臣今启奏: "Je vais signaler maintenant",
  伏望圣裁: "Hope Saint",
  恳乞天兵: "Boule pour le soldat céleste",
  收此妖孽: "Prendre ce monstre",
  庶使海岳清宁: "Pour rendre la mer et la montagne calme",
  下元安泰: "Xiayuan antai",
  奉奏: "Commentaire",
  圣帝览毕: "Le saint empereur a lu",
  传旨: "livrer une commande impériale",
  着龙神回海: "Retournez à la mer avec Dieu Dragon",
  朕即遣将擒拿: "J'enverrai le général pour le capturer",
  老龙王顿首谢去: "Le vieux roi de dragon inclina la tête et le remercia",
  下面又有葛仙翁天师启奏道:
    "Vous trouverez ci-dessous la récitation du maître céleste Ge Xianweng",
  万岁: "Vivre en vie",
  有冥司秦广王赍奉幽冥教主地藏王菩萨表文进上:
    "Un roi de Qin Guang des enfers a transmis un message au Bodhisattva Ksitigarbha Bodhisattva des enfers",
  旁有传言玉女: "Il y a une rumeur à côté de la fille jade",
  接上表文: "Continuez avec la table ci-dessus",
  玉皇亦从头看过: "L'empereur de jade l'a également regardé depuis le début",
  表曰: "Le",
  幽冥境界: "Netherworld",
  乃地之阴司: "C'est le yin si de la terre",
  天有神而地有鬼: "Il y a des dieux dans le ciel et des fantômes sur terre",
  阴阳转轮: "Roue yin-yang",
  禽有生而兽有死: "Les oiseaux sont nés et les bêtes sont mortes",
  反复雌雄: "Homme et femme répété",
  生生化化: "Biochimique",
  孕女成男: "Les femmes enceintes deviennent des hommes",
  此自然之数: "Ce nombre naturel",
  不能易也: "Pas facile",
  今有花果山水廉洞天产妖猴孙悟空:
    "Il y a maintenant des fleurs, des fruits, des montagnes, des rivières, du liandong et des singes démon produits par Sun Wukong",
  逞强行凶: "Être arrogant",
  不服拘唤: "Ne pas accepter",
  弄神通: "Profitez des pouvoirs surnaturels",
  打绝九幽鬼使: "Combattre les neuf fantômes de Nine",
  恃势力: "Compter sur le pouvoir",
  惊伤十代慈王: "Choqué et blessé les dix générations de CI Wang",
  大闹罗森: "Rosen",
  强销名号: "Nom de vente solide",
  致使猴属之类无拘: "Fait le singe et autres sans restriction",
  猕猴之畜多寿: "Les macaques vivent une longue vie",
  寂灭轮回: "Nirvana",
  各无生死: "Pas de vie ni de mort",
  贫僧具表: "Je suis une table de moine",
  冒渎天威: "Mao du Tianwei",
  伏乞调遣神兵: "Fuqi envoie les soldats magiques",
  收降此妖: "Arrêtez ce monstre",
  整理阴阳: "Organisez le yin et le yang",
  永安地府: "Yong'an Underground",
  谨奏: "Sois prudent",
  玉皇览毕: "Vue de l'empereur de jade",
  传旨: "livrer une commande impériale",
  着冥君回归地府: "Retour aux enfers avec le roi",
  朕即遣将擒拿: "J'enverrai le général pour le capturer",
  秦广王亦顿首谢去: "Le roi Qin Guang baissa également la tête et est parti",
  大天尊宣众文武仙卿:
    "Le grand seigneur céleste Xuan des immortels civils et militaires",
  问曰: "Demandé",
  这妖猴是几年生育: "Combien d'années ce monstre est-il né",
  何代出生: "Quand est né",
  却就这般有道: "Mais c'est tellement vrai",
  一言未已: "Pas un mot",
  班中闪出千里眼: "Mille milles d'yeux ont flâné dans la classe",
  顺风耳道: "Canal de l'oreille Shunwind",
  这猴乃三百年前天产石猴:
    "Ce singe est né il y a trois cents ans dans le ciel.",
  当时不以为然: "Je ne le pensais pas à ce moment-là",
  不知这几年在何方修炼成仙:
    "Je ne sais pas où devenir immortel ces dernières années",
  降龙伏虎: "Sous-didUing Dragons et Sous-didUing Tigers",
  强销死籍也: "Mort forcée",
  玉帝道: "La voie de Jade Emperor",
  那路神将下界收伏:
    "Les dieux de la route viennent dans le royaume et les conquérir",
  言未已: "Pas fini de parler",
  班中闪出太白长庚星: "La star de Taibai Chang Geng a flashé dans la classe",
  俯首启奏道: "Déprimé pour démarrer la piste",
  上圣三界中: "Dans les trois royaumes du Saint suprême",
  凡有九窍者: "Toute personne avec neuf orifices",
  皆可修仙: "Tous peuvent cultiver les immortels",
  奈此猴乃天地育成之体: "Mais ce singe est le corps du ciel et de la terre",
  日月孕就之身: "Le corps du soleil et de la grossesse de la lune",
  他也顶天履地: "Il marche également vers le ciel et la terre",
  服露餐霞: "Prendre un repas avec une saucisse",
  今既修成仙道: "Maintenant, j'ai cultivé le chemin de l'immortalité",
  有降龙伏虎之能: "Avoir la capacité de maîtriser les dragons et les tigres",
  与人何以异哉: "Dans quelle mesure les autres",
  臣启陛下: "Votre Majesté",
  可念生化之慈恩:
    "Pouvez-vous penser à la gentillesse de la vie et de la transformation",
  降一道招安圣旨: "Un édit impérial",
  把他宣来上届: "Le promouvoir à la dernière session",
  授他一个大小官职: "Donnez-lui une grande et petite position officielle",
  与他籍名在箓: "Avec d'autres noms",
  拘束此间: "Restreindre cela",
  若受天命: "Si vous êtes destiné au paradis",
  后再升赏: "Récompenses plus tard",
  若违天命: "Si vous violez la volonté du ciel",
  就此擒拿: "Le capturer",
  一则不动众劳师: "Une façon de ne rien faire à faire",
  二则收仙有道也: "Deuxièmement, il existe un moyen de collecter les immortels",
  玉帝闻言甚喜: "L'empereur de jade était très heureux quand il a entendu cela",
  道: "route",
  依卿所奏: "Selon votre rapport",
  即着文曲星官修诏:
    "A immédiatement écrit l'impérial du fonctionnaire de Wenqu Star",
  着太白金星招安: "Trop bai Vénus Star pour attirer l'aide",
};



const synth = window.speechSynthesis;
let utterance = null;

// 状态跟踪
const charStates = {};

// 页面加载完成后初始化
document.addEventListener("DOMContentLoaded", function () {
  renderPoem();
});

// 渲染诗歌
function renderPoem() {
  const poemContainer = document.getElementById("poemContainer");
  const lines = poemText.split("\n");

  lines.forEach((line) => {
    const lineDiv = document.createElement("div");
    lineDiv.className = "poem-line";

    // 处理每个字符
    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      // 跳过空格
      if (char.trim() === "") {
        const spaceSpan = document.createElement("span");
        spaceSpan.textContent = " ";
        lineDiv.appendChild(spaceSpan);
        continue;
      }

      // 创建字符容器
      const charContainer = document.createElement("div");
      charContainer.className = "char-container";

      // 创建字符显示
      const charSpan = document.createElement("span");
      charSpan.className = "char";
      charSpan.textContent = char;

      // 创建拼音显示
      const pinyinSpan = document.createElement("span");
      pinyinSpan.className = "pinyin";

      // 创建翻译显示
      const transSpan = document.createElement("span");
      transSpan.className = "translation";

      // 添加到容器
      charContainer.appendChild(pinyinSpan);
      charContainer.appendChild(charSpan);
      charContainer.appendChild(transSpan);

      // 添加点击事件
      charContainer.addEventListener("click", () =>
        handleCharClick(char, pinyinSpan, transSpan)
      );

      // 添加到行
      lineDiv.appendChild(charContainer);
    }

    // 添加行控制按钮
    const controlsDiv = document.createElement("div");
    controlsDiv.className = "line-controls";

    const readBtn = document.createElement("button");
    readBtn.textContent = "朗读";
    readBtn.addEventListener("click", () => readLine(line));

    const transBtn = document.createElement("button");
    transBtn.textContent = "翻译";
    transBtn.addEventListener("click", () => showLineTranslation(line));

    controlsDiv.appendChild(readBtn);
    controlsDiv.appendChild(transBtn);
    lineDiv.appendChild(controlsDiv);

    // 添加到容器
    poemContainer.appendChild(lineDiv);
  });
}

// 处理字符点击
function handleCharClick(char, pinyinSpan, transSpan) {
  const charId = `${char}-${pinyinSpan.id}`; // 创建唯一标识

  // 初始化状态
  if (!charStates[charId]) {
    charStates[charId] = 0;
  }

  // 更新状态
  charStates[charId]++;
  if (charStates[charId] > 3) {
    charStates[charId] = 1;
  }

  // 根据状态执行操作
  switch (charStates[charId]) {
    case 1: // 朗读字符
      readChar(char);
      updateStatus(`朗读字符: ${char}`);
      break;
    case 2: // 显示拼音
      showPinyin(char, pinyinSpan);
      updateStatus(`显示拼音: ${char}`);
      break;
    case 3: // 显示翻译
      showTranslation(char, transSpan);
      updateStatus(`显示翻译: ${char}`);
      break;
  }
}

// 显示拼音
function showPinyin(char, pinyinSpan) {
  // 这里应该调用拼音库，简化处理

  const py = pinyinMap[char] || "?";
  pinyinSpan.textContent = py;
  pinyinSpan.style.display = "block";

  // 3秒后自动隐藏
  setTimeout(() => {
    pinyinSpan.style.display = "none";
    // 重置状态以便下次点击
    const charId = `${char}-${pinyinSpan.id}`;
    charStates[charId] = 0;
  }, 8000);
}

// 朗读字符
function readChar(char) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(char);
  utterance.lang = "zh-CN";
  utterance.rate = 0.7; // 设置为正常速度的70%
  synth.speak(utterance);
}

// 显示翻译
function showTranslation(char, transSpan) {
  const lang = document.getElementById("languageSelect").value;

  const translationCard = document.getElementById("translationCard");

  const translateMap = {
    de: translations_de[char] || "Keine Übersetzung",
    fr: translations_fr[char] || "Pas de traduction",
    en: translations_en[char] || "No translation",
  };
  const translate = translateMap[lang];
  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">汉字：</div>
    <div class="info-content">${char}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translate}</div>
  </div>
`;

  translationCard.style.display = "block";

  const charId = `${char}-${transSpan.id}`;
  charStates[charId] = 0;
}

function closeTranslationCard() {
  const translationCard = document.getElementById("translationCard");
  translationCard.style.display = "none";
}

// 朗读整行
function readLine(line) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(line);
  utterance.lang = "zh-CN";
  utterance.rate = 0.6; // 设置为正常速度的60%，更慢一些
  synth.speak(utterance);

  updateStatus(`朗读: ${line}`);
}

function showLineTranslation(line) {
  const lang = document.getElementById("languageSelect").value;
  const translatedMap = {
    de: tianwen_translation_map_de,
    fr: tianwen_translation_map_fr,
    en: tianwen_translation_map_en,
  };
  const translatedLine =
    translatedMap[lang]?.[line] || "（keine Übersetzung gefunden）";
  const translationCard = document.getElementById("translationCard");

  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">原文：</div>
    <div class="info-content">${line}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translatedLine}</div>
  </div>
`;

  translationCard.style.display = "block";

  updateStatus(`显示翻译: ${line.substring(0, 15)}...`);
}

// 更新状态栏
function updateStatus(message) {
  document.getElementById("statusBar").textContent = message;
}
