const translationCard = document.getElementById("translationCard");
// 诗歌文本c
const poemText = `登岸偏访多时
忽见一座高山秀丽
林麓幽深
他也不怕狼虫
不惧虎豹
登山顶上观
正观看间
忽闻得林深之处
有人言语
急忙趋步
穿入林中
侧耳而听
原来是歌唱之声
歌
观棋柯烂
伐木丁丁
云边谷口徐行
卖薪沽酒
狂笑自陶情
苍迳秋高
对月枕松根
一觉天明
认旧林
登崖过岭
持斧断枯
收来成一担
行歌市上
易米三升
更无些子争竞
时价平平
不会机谋巧算
没荣辱
恬淡延生
相逢处
非仙即道
静坐讲黄庭
美猴王听得此言
满心欢喜道
神仙原来藏在这里
急忙跳入里面
仔细再看
乃是一个樵子
在那里举斧砍
猴王近前叫道
老神仙
弟子起手
那樵汉慌忙丢了斧
转身答礼道
不当人
不当人
我拙汉衣食不全
怎敢当神仙二字
猴王道
你不是神仙
如何说出神仙的话来
樵夫道
我说甚么神仙话
猴王道
我才来至林边
只听的你说
相逢处非仙即道
静坐讲黄庭
黄庭乃道德真言
非神仙而何
樵夫笑道
实不瞒你说
这个词名做满庭芳
乃一神仙教我的
那神仙与我舍下相邻
他见我家事劳苦
日常烦恼
教我遇烦恼时
即把这词儿念念
一则散心
二则解困
我才有些不足处思虑
故此念念
不期被你听了
猴王道
你家既与神仙相邻
何不从他修行
学得个不老之方
却不是好
樵夫道
我一生命苦
自幼蒙父母养育至八九岁
才知人事
不幸父丧
母亲居孀
再无兄弟姊妹
只我一人
没奈何
早晚侍奉
如今母老
一发不敢抛离
却又田园荒芜
衣食不足
只得斫两束柴薪
挑向市尘之间
货几文钱
籴几升米
自炊自造
安排些茶饭
供养老母
所以不能修行
猴王道
据你说起来
乃是一个行孝的君子
向后必有好处
但望你指与我那神仙住处
却好拜访去也
樵夫道
不远
不远
此山叫做灵台方寸山
山中有座斜月三星洞
那洞中有一个神仙
称名须菩提祖师
那祖师出去的徒弟
也不计其数
见今还有三四十人从他修行
你顺那条小路儿
向南行七八里远近
即是他家了
猴王用手扯住樵夫道
老兄
你便同我去去
若还得了好处
决不忘你指引之恩
樵夫道
你这汉子
甚不通变
我方才这般与你说了
你还不省
假若我与你去了
却不误了我的生意
老母何人奉养
我要斫柴
你自去
自去
`;
const pinyinMap = {
  登: "dēng",
  岸: "àn",
  偏: "piān",
  访: "fǎng",
  多: "duō",
  时: "shí",
  忽: "hū",
  见: "jiàn",
  一: "yī",
  座: "zuò",
  高: "gāo",
  山: "shān",
  秀: "xiù",
  丽: "lì",
  林: "lín",
  麓: "lù",
  幽: "yōu",
  深: "shēn",
  他: "tā",
  也: "yě",
  不: "bù",
  怕: "pà",
  狼: "láng",
  虫: "chóng",
  惧: "jù",
  虎: "hǔ",
  豹: "bào",
  顶: "dǐng",
  上: "shàng",
  观: "guān",
  正: "zhèng",
  看: "kàn",
  间: "jiān",
  闻: "wén",
  得: "dé",
  之: "zhī",
  处: "chù",
  有: "yǒu",
  人: "rén",
  言: "yán",
  语: "yǔ",
  急: "jí",
  忙: "máng",
  趋: "qū",
  步: "bù",
  穿: "chuān",
  入: "rù",
  中: "zhōng",
  侧: "cè",
  耳: "ěr",
  而: "ér",
  听: "tīng",
  原: "yuán",
  来: "lái",
  是: "shì",
  歌: "gē",
  唱: "chàng",
  声: "shēng",
  棋: "qí",
  柯: "kē",
  烂: "làn",
  伐: "fá",
  木: "mù",
  丁: "dīng",
  云: "yún",
  边: "biān",
  谷: "gǔ",
  口: "kǒu",
  徐: "xú",
  行: "xíng",
  卖: "mài",
  薪: "xīn",
  沽: "gū",
  酒: "jiǔ",
  狂: "kuáng",
  笑: "xiào",
  自: "zì",
  陶: "táo",
  情: "qíng",
  苍: "cāng",
  迳: "jìng",
  秋: "qiū",
  对: "duì",
  月: "yuè",
  枕: "zhěn",
  松: "sōng",
  根: "gēn",
  觉: "jué",
  天: "tiān",
  明: "míng",
  认: "rèn",
  旧: "jiù",
  崖: "yá",
  过: "guò",
  岭: "lǐng",
  持: "chí",
  斧: "fǔ",
  断: "duàn",
  枯: "kū",
  收: "shōu",
  成: "chéng",
  担: "dān",
  市: "shì",
  易: "yì",
  米: "mǐ",
  三: "sān",
  升: "shēng",
  更: "gèng",
  无: "wú",
  些: "xiē",
  子: "zi",
  争: "zhēng",
  竞: "jìng",
  价: "jià",
  平: "píng",
  会: "huì",
  机: "jī",
  谋: "móu",
  巧: "qiǎo",
  算: "suàn",
  没: "méi",
  荣: "róng",
  辱: "rǔ",
  恬: "tián",
  淡: "dàn",
  延: "yán",
  生: "shēng",
  相: "xiāng",
  逢: "féng",
  非: "fēi",
  仙: "xiān",
  即: "jí",
  道: "dào",
  静: "jìng",
  坐: "zuò",
  讲: "jiǎng",
  黄: "huáng",
  庭: "tíng",
  美: "měi",
  猴: "hóu",
  王: "wáng",
  此: "cǐ",
  满: "mǎn",
  心: "xīn",
  欢: "huān",
  喜: "xǐ",
  神: "shén",
  藏: "cáng",
  在: "zài",
  这: "zhè",
  里: "lǐ",
  跳: "tiào",
  面: "miàn",
  仔: "zǐ",
  细: "xì",
  再: "zài",
  乃: "nǎi",
  个: "gè",
  樵: "qiáo",
  那: "nà",
  举: "jǔ",
  砍: "kǎn",
  近: "jìn",
  前: "qián",
  叫: "jiào",
  老: "lǎo",
  弟: "dì",
  起: "qǐ",
  手: "shǒu",
  汉: "hàn",
  慌: "huāng",
  丢: "diū",
  了: "le",
  转: "zhuǎn",
  身: "shēn",
  答: "dá",
  礼: "lǐ",
  当: "dāng",
  我: "wǒ",
  拙: "zhuō",
  衣: "yī",
  食: "shí",
  全: "quán",
  怎: "zěn",
  敢: "gǎn",
  二: "èr",
  字: "zì",
  你: "nǐ",
  如: "rú",
  何: "hé",
  说: "shuō",
  出: "chū",
  的: "de",
  话: "huà",
  夫: "fū",
  甚: "shén",
  么: "me",
  才: "cái",
  至: "zhì",
  只: "zhǐ",
  德: "dé",
  真: "zhēn",
  实: "shí",
  瞒: "mán",
  词: "cí",
  名: "míng",
  做: "zuò",
  芳: "fāng",
  教: "jiào",
  与: "yǔ",
  舍: "shě",
  下: "xià",
  邻: "lín",
  家: "jiā",
  事: "shì",
  劳: "láo",
  苦: "kǔ",
  日: "rì",
  常: "cháng",
  烦: "fán",
  恼: "nǎo",
  遇: "yù",
  把: "bǎ",
  儿: "ér",
  念: "niàn",
  则: "zé",
  散: "sàn",
  解: "jiě",
  困: "kùn",
  足: "zú",
  思: "sī",
  虑: "lǜ",
  故: "gù",
  期: "qī",
  被: "bèi",
  既: "jì",
  从: "cóng",
  修: "xiū",
  学: "xué",
  方: "fāng",
  却: "què",
  好: "hǎo",
  命: "mìng",
  幼: "yòu",
  蒙: "méng",
  父: "fù",
  母: "mǔ",
  养: "yǎng",
  育: "yù",
  八: "bā",
  九: "jiǔ",
  岁: "suì",
  知: "zhī",
  幸: "xìng",
  丧: "sàng",
  亲: "qīn",
  居: "jū",
  孀: "shuāng",
  兄: "xiōng",
  姊: "zǐ",
  妹: "mèi",
  奈: "nài",
  早: "zǎo",
  晚: "wǎn",
  侍: "shì",
  奉: "fèng",
  今: "jīn",
  发: "fā",
  抛: "pāo",
  离: "lí",
  又: "yòu",
  田: "tián",
  园: "yuán",
  荒: "huāng",
  芜: "wú",
  斫: "zhuó",
  两: "liǎng",
  束: "shù",
  柴: "chái",
  挑: "tiāo",
  向: "xiàng",
  尘: "chén",
  货: "huò",
  几: "jǐ",
  文: "wén",
  钱: "qián",
  籴: "dí",
  炊: "chuī",
  造: "zào",
  安: "ān",
  排: "pái",
  茶: "chá",
  饭: "fàn",
  供: "gōng",
  所: "suǒ",
  以: "yǐ",
  能: "néng",
  据: "jù",
  孝: "xiào",
  君: "jūn",
  后: "hòu",
  必: "bì",
  但: "dàn",
  望: "wàng",
  指: "zhǐ",
  住: "zhù",
  拜: "bài",
  去: "qù",
  远: "yuǎn",
  灵: "líng",
  台: "tái",
  寸: "cùn",
  斜: "xié",
  星: "xīng",
  洞: "dòng",
  称: "chēng",
  须: "xū",
  菩: "pú",
  提: "tí",
  祖: "zǔ",
  师: "shī",
  徒: "tú",
  计: "jì",
  其: "qí",
  数: "shù",
  还: "hái",
  四: "sì",
  十: "shí",
  顺: "shùn",
  条: "tiáo",
  小: "xiǎo",
  路: "lù",
  南: "nán",
  七: "qī",
  用: "yòng",
  扯: "chě",
  便: "biàn",
  同: "tóng",
  若: "ruò",
  决: "jué",
  忘: "wàng",
  引: "yǐn",
  恩: "ēn",
  通: "tōng",
  变: "biàn",
  般: "bān",
  省: "shěng",
  假: "jiǎ",
  误: "wù",
  意: "yì",
  要: "yào",
};

const translations_de = {
  登: "Login",
  岸: "Ufer",
  偏: "Negativ",
  访: "besuchen",
  多: "viele",
  时: "Stunde",
  忽: "plötzlich",
  见: "Sehen",
  一: "eins",
  座: "Sitz",
  高: "hoch",
  山: "Berg",
  秀: "zeigen",
  丽: "Korea",
  林: "Wald",
  麓: "Lu",
  幽: "ruhig",
  深: "tief",
  他: "Er",
  也: "Auch",
  不: "NEIN",
  怕: "Besorgt",
  狼: "Wolf",
  虫: "Insekt",
  惧: "Furcht",
  虎: "Tiger",
  豹: "Leopard",
  顶: "Spitze",
  上: "Vorgesetzter",
  观: "Sicht",
  正: "Nur",
  看: "sehen",
  间: "zwischen",
  闻: "Geruch",
  得: "müssen",
  之: "Von",
  处: "Wo",
  有: "haben",
  人: "Menschen",
  言: "Wort",
  语: "Sprache",
  急: "dringend",
  忙: "beschäftigt",
  趋: "Trend",
  步: "Schritt",
  穿: "tragen",
  入: "eingeben",
  中: "Mitte",
  侧: "Seite",
  耳: "Ohr",
  而: "Und",
  听: "Hören",
  原: "Original",
  来: "Kommen",
  是: "Ja",
  歌: "Lied",
  唱: "Singen",
  声: "Stimme",
  棋: "Schach",
  柯: "Ke",
  烂: "faul",
  伐: "Schneiden",
  木: "Holz",
  丁: "Mann",
  云: "Wolke",
  边: "Seite",
  谷: "Schlucht",
  口: "Mund",
  徐: "Xu",
  行: "OK",
  卖: "Verkaufen",
  薪: "Gehalt",
  沽: "verkaufen",
  酒: "Alkohol",
  狂: "verrückt",
  笑: "lachen",
  自: "seit",
  陶: "Keramik",
  情: "Zuneigung",
  苍: "CANG",
  迳: "Direkt",
  秋: "Herbst",
  对: "Rechts",
  月: "Mond",
  枕: "Kissen",
  松: "lose",
  根: "Wurzel",
  觉: "Schlafen",
  天: "Himmel",
  明: "hell",
  认: "erkennen",
  旧: "alt",
  崖: "Cliff",
  过: "Passieren",
  岭: "Grat",
  持: "halten",
  斧: "Axt",
  断: "Brechen",
  枯: "Verdorren",
  收: "erhalten",
  成: "werden",
  担: "Laden",
  市: "Stadt",
  易: "einfach",
  米: "Reis",
  三: "drei",
  升: "Aufzug",
  更: "Sogar",
  无: "keiner",
  些: "manche",
  子: "Sohn",
  争: "Kämpfen",
  竞: "Wettbewerb",
  价: "Preis",
  平: "Wohnung",
  会: "treffen",
  机: "Maschine",
  谋: "suchen",
  巧: "geschickt",
  算: "Berechnen",
  没: "ohne",
  荣: "Ehre",
  辱: "Schande",
  恬: "Tsing",
  淡: "Licht",
  延: "Verzögerung",
  生: "geboren",
  相: "Gegenseitig",
  逢: "Jeder",
  非: "NEIN",
  仙: "Fee",
  即: "Im Augenblick",
  道: "Straße",
  静: "ruhig",
  坐: "sitzen",
  讲: "sprechen",
  黄: "Gelb",
  庭: "Gericht",
  美: "Schön",
  猴: "Affe",
  王: "König",
  此: "Das",
  满: "Voll",
  心: "Herz",
  欢: "freudig",
  喜: "Glück",
  神: "Gott",
  藏: "Tibetaner",
  在: "existieren",
  这: "Das",
  里: "innen",
  跳: "Springen",
  面: "Nudel",
  仔: "jung",
  细: "dünn",
  再: "Wieder",
  乃: "Also",
  个: "indival",
  樵: "Brennholz",
  那: "Das",
  举: "Aufzug",
  砍: "schneiden",
  近: "schließen",
  前: "nach vorne",
  叫: "Anruf",
  老: "alt",
  弟: "jüngerer Bruder",
  起: "erheben",
  手: "Hand",
  汉: "chinesisch",
  慌: "Panik",
  丢: "verlassen",
  了: "Es ist",
  转: "ändern",
  身: "Körper",
  答: "Antwort",
  礼: "gegenwärtig",
  当: "Wann",
  我: "ICH",
  拙: "unbeholfen",
  衣: "Kleidung",
  食: "Essen",
  全: "Vollständig",
  怎: "Wie",
  敢: "wagen",
  二: "zwei",
  字: "Charakter",
  你: "Du",
  如: "wie",
  何: "Was",
  说: "erklären",
  出: "aus",
  的: "von",
  话: "sprechen",
  夫: "Ehemann",
  甚: "sehr",
  么: "Ist es",
  才: "Talent",
  至: "Zu",
  只: "Nur",
  德: "De",
  真: "real",
  实: "Wirklichkeit",
  瞒: "verbergen",
  词: "Wort",
  名: "Name",
  做: "Tun",
  芳: "Fang",
  教: "unterrichten",
  与: "Und",
  舍: "Aufgeben",
  下: "Runter",
  邻: "benachbart",
  家: "Heim",
  事: "Ding",
  劳: "Arbeit",
  苦: "bitter",
  日: "Tag",
  常: "oft",
  烦: "sich kümmern",
  恼: "wütend",
  遇: "Treffen",
  把: "Bündeln",
  儿: "Sohn",
  念: "lesen",
  则: "Aber",
  散: "Verstreut",
  解: "lösen",
  困: "Schläfrig",
  足: "Fuß",
  思: "denken",
  虑: "halten",
  故: "daher",
  期: "Erwarten",
  被: "Decke",
  既: "Nun das",
  从: "aus",
  修: "bauen",
  学: "Studie",
  方: "Quadrat",
  却: "Aber",
  好: "Gut",
  命: "Leben",
  幼: "jung",
  蒙: "mongolisch",
  父: "Vater",
  母: "Mutter",
  养: "halten",
  育: "Ausbildung",
  八: "acht",
  九: "Neun",
  岁: "Alter",
  知: "Wissen",
  幸: "glücklich",
  丧: "Beerdigung",
  亲: "relativ",
  居: "Residenz",
  孀: "Witwe",
  兄: "Bruder",
  姊: "Schwester",
  妹: "Schwester",
  奈: "Nye",
  早: "Morgen",
  晚: "Nacht",
  侍: "Sitzen",
  奉: "Feng",
  今: "Jetzt",
  发: "Haar",
  抛: "werfen",
  离: "Verlassen",
  又: "wieder",
  田: "Feld",
  园: "Garten",
  荒: "Mangel",
  芜: "Wu",
  斫: "hacken",
  两: "zwei",
  束: "bündeln",
  柴: "Brennholz",
  挑: "wählen",
  向: "In Richtung",
  尘: "Staub",
  货: "Waren",
  几: "Mehrere",
  文: "Künste",
  钱: "Geld",
  籴: "Abrechnung",
  炊: "Kochen",
  造: "machen",
  安: "installieren",
  排: "Reihe",
  茶: "Tee",
  饭: "Mahlzeit",
  供: "für",
  所: "Ort",
  以: "von",
  能: "fähig",
  据: "entsprechend",
  孝: "Filiale Frömmigkeit",
  君: "Jun",
  后: "zurück",
  必: "muss",
  但: "Aber",
  望: "sehen",
  指: "beziehen sich auf",
  住: "live",
  拜: "Tschüss",
  去: "gehen",
  远: "Weit",
  灵: "Geist",
  台: "Turm",
  寸: "Zoll",
  斜: "Neigung",
  星: "Stern",
  洞: "Loch",
  称: "sagen",
  须: "Muss",
  菩: "Bodhisattva",
  提: "tragen",
  祖: "Vorfahr",
  师: "Division",
  徒: "nur",
  计: "zählen",
  其: "Das",
  数: "Nummer",
  还: "zurückkehren",
  四: "Vier",
  十: "zehn",
  顺: "Sicher",
  条: "Streifen",
  小: "Klein",
  路: "Straße",
  南: "Süden",
  七: "Sieben",
  用: "verwenden",
  扯: "ziehen",
  便: "Hoffnung",
  同: "Dasselbe",
  若: "wie",
  决: "Entscheidung",
  忘: "vergessen",
  引: "führen",
  恩: "Freundlichkeit",
  通: "Passieren",
  变: "Ändern",
  般: "Normal",
  省: "Provinz",
  假: "Gefälscht",
  误: "Fehler",
  意: "Bedeutung",
  要: "wollen",
};

const translations_fr = {
  登: "Se connecter",
  岸: "rive",
  偏: "Négatif",
  访: "visite",
  多: "beaucoup",
  时: "heure",
  忽: "soudainement",
  见: "Voir",
  一: "un",
  座: "siège",
  高: "haut",
  山: "Montagne",
  秀: "montrer",
  丽: "Corée",
  林: "Forêt",
  麓: "Lu",
  幽: "calme",
  深: "profond",
  他: "il",
  也: "aussi",
  不: "Non",
  怕: "Effrayé",
  狼: "Loup",
  虫: "insecte",
  惧: "peur",
  虎: "Tigre",
  豹: "Léopard",
  顶: "haut",
  上: "supérieur",
  观: "Voir",
  正: "juste",
  看: "regarder",
  间: "entre",
  闻: "odeur",
  得: "devoir",
  之: "De",
  处: "Où",
  有: "avoir",
  人: "personnes",
  言: "Mot",
  语: "langue",
  急: "urgent",
  忙: "occupé",
  趋: "S'orienter",
  步: "étape",
  穿: "porter",
  入: "entrer",
  中: "milieu",
  侧: "côté",
  耳: "Oreille",
  而: "et",
  听: "écouter",
  原: "Original",
  来: "Viens",
  是: "Oui",
  歌: "Chanson",
  唱: "Chanter",
  声: "Voix",
  棋: "échecs",
  柯: "Ke",
  烂: "pourri",
  伐: "Couper",
  木: "Bois",
  丁: "Homme",
  云: "nuage",
  边: "côté",
  谷: "vallée",
  口: "bouche",
  徐: "Xu",
  行: "D'ACCORD",
  卖: "Vendre",
  薪: "salaire",
  沽: "vendre",
  酒: "alcool",
  狂: "fou",
  笑: "rire",
  自: "depuis",
  陶: "poterie",
  情: "Affection",
  苍: "Châssis",
  迳: "Direct",
  秋: "Automne",
  对: "droite",
  月: "lune",
  枕: "oreiller",
  松: "lâche",
  根: "racine",
  觉: "Dormir",
  天: "ciel",
  明: "brillant",
  认: "reconnaître",
  旧: "vieux",
  崖: "Falaise",
  过: "Passer",
  岭: "crête",
  持: "prise",
  斧: "hache",
  断: "Casser",
  枯: "Flétrir",
  收: "recevoir",
  成: "devenir",
  担: "Charger",
  市: "ville",
  易: "facile",
  米: "riz",
  三: "trois",
  升: "Ascenseur",
  更: "Même",
  无: "aucun",
  些: "quelques",
  子: "fils",
  争: "Combattre",
  竞: "Concours",
  价: "prix",
  平: "plat",
  会: "réunion",
  机: "machine",
  谋: "chercher",
  巧: "habile",
  算: "Calculer",
  没: "sans",
  荣: "Honneur",
  辱: "disgrâce",
  恬: "Tsing",
  淡: "lumière",
  延: "Retard",
  生: "né",
  相: "Mutuellement",
  逢: "Chaque",
  非: "Non",
  仙: "Fée",
  即: "Tout de suite",
  道: "route",
  静: "calme",
  坐: "s'asseoir",
  讲: "parler",
  黄: "jaune",
  庭: "tribunal",
  美: "beau",
  猴: "singe",
  王: "roi",
  此: "ce",
  满: "Complet",
  心: "Cœur",
  欢: "joyeux",
  喜: "bonheur",
  神: "Dieu",
  藏: "Tibétain",
  在: "exister",
  这: "ce",
  里: "à l'intérieur",
  跳: "Saut",
  面: "nouille",
  仔: "jeune",
  细: "mince",
  再: "Encore",
  乃: "Donc",
  个: "autonome",
  樵: "bois de chauffage",
  那: "Que",
  举: "Ascenseur",
  砍: "couper",
  近: "fermer",
  前: "avant",
  叫: "Appel",
  老: "vieux",
  弟: "jeune frère",
  起: "augmenter",
  手: "main",
  汉: "Chinois",
  慌: "Panique",
  丢: "partir",
  了: "C'est",
  转: "changement",
  身: "corps",
  答: "répondre",
  礼: "présent",
  当: "quand",
  我: "je",
  拙: "maladroit",
  衣: "Vêtements",
  食: "Nourriture",
  全: "Complet",
  怎: "Comment",
  敢: "oser",
  二: "deux",
  字: "Personnage",
  你: "toi",
  如: "comme",
  何: "quoi",
  说: "expliquer",
  出: "dehors",
  的: "de",
  话: "parler",
  夫: "mari",
  甚: "très",
  么: "Est-ce",
  才: "talent",
  至: "à",
  只: "Seulement",
  德: "De",
  真: "réel",
  实: "Réalité",
  瞒: "cacher",
  词: "mot",
  名: "nom",
  做: "Faire",
  芳: "Croc",
  教: "enseigner",
  与: "et",
  舍: "Abandonner",
  下: "Vers le bas",
  邻: "adjacent",
  家: "Maison",
  事: "chose",
  劳: "travail",
  苦: "amer",
  日: "jour",
  常: "souvent",
  烦: "déranger",
  恼: "en colère",
  遇: "Rencontrer",
  把: "Paquet",
  儿: "Fils",
  念: "lire",
  则: "mais",
  散: "Dispersé",
  解: "délier",
  困: "Somnolent",
  足: "pied",
  思: "pense",
  虑: "considérer",
  故: "Donc",
  期: "Attendre",
  被: "édredon",
  既: "maintenant que",
  从: "depuis",
  修: "construire",
  学: "étude",
  方: "carré",
  却: "mais",
  好: "bien",
  命: "vie",
  幼: "jeune",
  蒙: "mongol",
  父: "père",
  母: "mère",
  养: "garder",
  育: "Éducation",
  八: "huit",
  九: "Neuf",
  岁: "âge",
  知: "Savoir",
  幸: "heureux",
  丧: "funérailles",
  亲: "relatif",
  居: "Résidence",
  孀: "veuve",
  兄: "Frère",
  姊: "Sœur",
  妹: "sœur",
  奈: "Nye",
  早: "matin",
  晚: "Nuit",
  侍: "S'asseoir",
  奉: "Feng",
  今: "maintenant",
  发: "cheveux",
  抛: "lancer",
  离: "Partir",
  又: "encore",
  田: "champ",
  园: "jardin",
  荒: "pénurie",
  芜: "Wu",
  斫: "hacher",
  两: "deux",
  束: "paquet",
  柴: "bois de chauffage",
  挑: "prendre",
  向: "Vers",
  尘: "poussière",
  货: "marchandises",
  几: "Plusieurs",
  文: "arts",
  钱: "argent",
  籴: "Facturation",
  炊: "Cuisiner",
  造: "faire",
  安: "installer",
  排: "Rangée",
  茶: "Thé",
  饭: "repas",
  供: "pour",
  所: "Lieu",
  以: "par",
  能: "capable",
  据: "selon",
  孝: "piété filiale",
  君: "Juin",
  后: "dos",
  必: "doit",
  但: "mais",
  望: "voir",
  指: "se référer à",
  住: "en direct",
  拜: "au revoir",
  去: "aller",
  远: "Loin",
  灵: "esprit",
  台: "tour",
  寸: "pouce",
  斜: "inclinaison",
  星: "étoile",
  洞: "Trou",
  称: "dire",
  须: "Doit",
  菩: "Bodhisattva",
  提: "porter",
  祖: "Ancêtre",
  师: "division",
  徒: "seulement",
  计: "compter",
  其: "Que",
  数: "nombre",
  还: "retour",
  四: "Quatre",
  十: "dix",
  顺: "Bien sûr",
  条: "bande",
  小: "Petit",
  路: "route",
  南: "Sud",
  七: "Sept",
  用: "utiliser",
  扯: "tirer",
  便: "Espoir",
  同: "même",
  若: "comme",
  决: "Décision",
  忘: "oublier",
  引: "plomb",
  恩: "gentillesse",
  通: "Passer",
  变: "Changement",
  般: "Normale",
  省: "Province",
  假: "Faux",
  误: "erreur",
  意: "signification",
  要: "vouloir",
};

const translations_en = {
  登: "Login",
  岸: "shore",
  偏: "Negative",
  访: "visit",
  多: "many",
  时: "hour",
  忽: "suddenly",
  见: "See",
  一: "one",
  座: "seat",
  高: "high",
  山: "Mountain",
  秀: "show",
  丽: "Korea",
  林: "Forest",
  麓: "Lu",
  幽: "quiet",
  深: "deep",
  他: "he",
  也: "also",
  不: "No",
  怕: "Afraid",
  狼: "Wolf",
  虫: "insect",
  惧: "fear",
  虎: "Tiger",
  豹: "Leopard",
  顶: "top",
  上: "superior",
  观: "View",
  正: "just",
  看: "look",
  间: "between",
  闻: "smell",
  得: "have to",
  之: "Of",
  处: "Where",
  有: "have",
  人: "people",
  言: "Word",
  语: "language",
  急: "urgent",
  忙: "busy",
  趋: "Trend",
  步: "step",
  穿: "wear",
  入: "enter",
  中: "middle",
  侧: "side",
  耳: "Ear",
  而: "and",
  听: "listen",
  原: "Original",
  来: "Come",
  是: "yes",
  歌: "Song",
  唱: "Sing",
  声: "Voice",
  棋: "chess",
  柯: "Ke",
  烂: "rotten",
  伐: "Cut",
  木: "Wood",
  丁: "Man",
  云: "cloud",
  边: "side",
  谷: "valley",
  口: "mouth",
  徐: "Xu",
  行: "OK",
  卖: "Sell",
  薪: "salary",
  沽: "sell",
  酒: "liquor",
  狂: "mad",
  笑: "laugh",
  自: "since",
  陶: "pottery",
  情: "Affection",
  苍: "Cang",
  迳: "Direct",
  秋: "Autumn",
  对: "right",
  月: "moon",
  枕: "pillow",
  松: "loose",
  根: "root",
  觉: "Sleep",
  天: "sky",
  明: "bright",
  认: "recognize",
  旧: "old",
  崖: "Cliff",
  过: "Pass",
  岭: "ridge",
  持: "hold",
  斧: "ax",
  断: "Break",
  枯: "Wither",
  收: "receive",
  成: "become",
  担: "Load",
  市: "city",
  易: "easy",
  米: "rice",
  三: "three",
  升: "Lift",
  更: "Even",
  无: "none",
  些: "some",
  子: "son",
  争: "Contend",
  竞: "Competition",
  价: "price",
  平: "flat",
  会: "meeting",
  机: "machine",
  谋: "seek",
  巧: "skillful",
  算: "Calculate",
  没: "without",
  荣: "Honor",
  辱: "disgrace",
  恬: "Tsing",
  淡: "light",
  延: "Delay",
  生: "born",
  相: "Mutually",
  逢: "Every",
  非: "No",
  仙: "Fairy",
  即: "Right now",
  道: "road",
  静: "quiet",
  坐: "sit",
  讲: "speak",
  黄: "yellow",
  庭: "court",
  美: "beautiful",
  猴: "monkey",
  王: "king",
  此: "this",
  满: "Full",
  心: "Heart",
  欢: "joyous",
  喜: "happiness",
  神: "god",
  藏: "Tibetan",
  在: "exist",
  这: "this",
  里: "inside",
  跳: "Jump",
  面: "noodle",
  仔: "young",
  细: "thin",
  再: "Again",
  乃: "So",
  个: "indivual",
  樵: "firewood",
  那: "That",
  举: "Lift",
  砍: "cut",
  近: "close",
  前: "forward",
  叫: "Call",
  老: "old",
  弟: "younger brother",
  起: "rise",
  手: "hand",
  汉: "Chinese",
  慌: "Panic",
  丢: "leave",
  了: "It's",
  转: "change",
  身: "body",
  答: "answer",
  礼: "present",
  当: "when",
  我: "I",
  拙: "clumsy",
  衣: "Clothes",
  食: "Food",
  全: "Complete",
  怎: "How",
  敢: "dare",
  二: "two",
  字: "Character",
  你: "you",
  如: "like",
  何: "what",
  说: "explain",
  出: "out",
  的: "of",
  话: "talk",
  夫: "husband",
  甚: "very",
  么: "Is it",
  才: "talent",
  至: "to",
  只: "Only",
  德: "De",
  真: "real",
  实: "Reality",
  瞒: "conceal",
  词: "word",
  名: "name",
  做: "Do",
  芳: "Fang",
  教: "teach",
  与: "and",
  舍: "Abandon",
  下: "Down",
  邻: "adjacent",
  家: "Home",
  事: "thing",
  劳: "labor",
  苦: "bitter",
  日: "day",
  常: "often",
  烦: "bother",
  恼: "angry",
  遇: "Meet",
  把: "Bundle",
  儿: "Son",
  念: "read",
  则: "but",
  散: "Scattered",
  解: "untie",
  困: "Sleepy",
  足: "foot",
  思: "think",
  虑: "consider",
  故: "Therefore",
  期: "Expect",
  被: "quilt",
  既: "now that",
  从: "from",
  修: "build",
  学: "study",
  方: "square",
  却: "but",
  好: "good",
  命: "life",
  幼: "young",
  蒙: "Mongolian",
  父: "father",
  母: "mother",
  养: "keep",
  育: "Education",
  八: "eight",
  九: "Nine",
  岁: "age",
  知: "Know",
  幸: "fortunate",
  丧: "funeral",
  亲: "relative",
  居: "Residence",
  孀: "widow",
  兄: "Brother",
  姊: "Sister",
  妹: "sister",
  奈: "Nye",
  早: "morning",
  晚: "Night",
  侍: "Sit",
  奉: "Feng",
  今: "now",
  发: "hair",
  抛: "throw",
  离: "Leave",
  又: "again",
  田: "field",
  园: "garden",
  荒: "shortage",
  芜: "Wu",
  斫: "chop",
  两: "two",
  束: "bundle",
  柴: "firewood",
  挑: "pick",
  向: "Towards",
  尘: "dust",
  货: "goods",
  几: "Several",
  文: "arts",
  钱: "money",
  籴: "Billing",
  炊: "Cook",
  造: "make",
  安: "install",
  排: "Row",
  茶: "Tea",
  饭: "meal",
  供: "for",
  所: "Place",
  以: "by",
  能: "able",
  据: "according to",
  孝: "filial piety",
  君: "Jun",
  后: "back",
  必: "must",
  但: "but",
  望: "see",
  指: "refer to",
  住: "live",
  拜: "bye",
  去: "go",
  远: "Far",
  灵: "spirit",
  台: "tower",
  寸: "inch",
  斜: "incline",
  星: "star",
  洞: "Hole",
  称: "say",
  须: "Must",
  菩: "Bodhisattva",
  提: "carry",
  祖: "Ancestor",
  师: "division",
  徒: "only",
  计: "count",
  其: "That",
  数: "number",
  还: "return",
  四: "Four",
  十: "ten",
  顺: "Sure",
  条: "strip",
  小: "Small",
  路: "road",
  南: "South",
  七: "seven",
  用: "use",
  扯: "pull",
  便: "Hope",
  同: "same",
  若: "like",
  决: "Decision",
  忘: "forget",
  引: "lead",
  恩: "kindness",
  通: "Pass",
  变: "Change",
  般: "Normal",
  省: "Province",
  假: "Fake",
  误: "error",
  意: "meaning",
  要: "want",
};

const tianwen_translation_map_fr = {
  登岸偏访多时: "Longtemps pour atterrir",
  忽见一座高山秀丽: "Soudain, j'ai vu une belle montagne",
  林麓幽深: "La forêt est profonde",
  他也不怕狼虫: "Il n'a pas peur des insectes de loup non plus",
  不惧虎豹: "Pas peur des tigres et des léopards",
  登山顶上观: "Regardez depuis le sommet de la montagne",
  正观看间: "REGARDER",
  忽闻得林深之处: "Soudain, j'ai entendu la forêt profonde",
  有人言语: "Les paroles de quelqu'un",
  急忙趋步: "Parler à la hâte",
  穿入林中: "Passer dans la forêt",
  侧耳而听: "Écoutez avec vos oreilles",
  原来是歌唱之声: "Il s'avère que c'est le son du chant",
  歌: "Chanson",
  观棋柯烂: "Regarder les échecs est mauvais",
  伐木丁丁: "Couper des boîtes",
  云边谷口徐行: "Marcher lentement à l'entrée de la vallée par les nuages",
  卖薪沽酒: "Vendre du vin",
  狂笑自陶情: "Rire sauvagement amoureux",
  苍迳秋高: "L'automne est haut dans le ciel",
  对月枕松根: "Racines pinéales sur la lune",
  一觉天明: "Une aube soudaine",
  认旧林: "Reconnaître la vieille forêt",
  登崖过岭: "Grimper la falaise et traverser la crête",
  持斧断枯: "Tenez une hache et brisez",
  收来成一担: "Collectez-le dans un levier",
  行歌市上: "Sur le marché Xingge",
  易米三升: "Yimi trois litres",
  更无些子争竞: "Il n'y a pas de compétition",
  时价平平: "Le prix actuel est moyen",
  不会机谋巧算: "Impossible de faire des plans",
  没荣辱: "Pas d'honneur et de honte",
  恬淡延生: "Tranquillité et prolonger la vie",
  相逢处: "Où rencontrer",
  非仙即道: "Immortel ou Tao",
  静坐讲黄庭: "Assis dans la méditation et parler de Huang Ting",
  美猴王听得此言: "Le roi de singe a entendu ça",
  满心欢喜道: "Dit avec joie",
  神仙原来藏在这里: "Les dieux sont cachés ici",
  急忙跳入里面: "Sauter rapidement",
  仔细再看: "Regarder attentivement",
  乃是一个樵子: "C'est un bûcheron",
  在那里举斧砍: "Hacher là-bas avec une hache",
  猴王近前叫道: "Le roi de singe a crié",
  老神仙: "Vieux Dieu",
  弟子起手: "Le disciple commence",
  那樵汉慌忙丢了斧: "Le bûcheron a jeté à la hâte sa hache",
  转身答礼道: "Retourner et répondre au rituel",
  不当人: "Ne pas être un humain",
  不当人: "Ne pas être un humain",
  我拙汉衣食不全: "Mon mari n'est pas entièrement nourri et nourri.",
  怎敢当神仙二字: "Comment osez-vous être un Dieu",
  猴王道: "Le chemin du roi du singe",
  你不是神仙: "Tu n'es pas un dieu",
  如何说出神仙的话来: "Comment dire les dieux",
  樵夫道: "La voie de Woodman",
  我说甚么神仙话: "Quels mots de fée dois-je dire",
  猴王道: "Le chemin du roi du singe",
  我才来至林边: "Je viens d'arriver dans le libardage",
  只听的你说: "Je t'écoute juste",
  相逢处非仙即道: "Où nous nous rencontrons n'est ni immortel ni tao",
  静坐讲黄庭: "Assis dans la méditation et parler de Huang Ting",
  黄庭乃道德真言: "Huang Ting est la vérité morale",
  非神仙而何: "Ce qui n'est pas un Dieu",
  樵夫笑道: "Le bûcheron sourit",
  实不瞒你说: "Je vais te cacher",
  这个词名做满庭芳: "Le mot est appelé mantetingfang",
  乃一神仙教我的: "Il a été enseigné par un dieu",
  那神仙与我舍下相邻: "Le Dieu et moi nous sommes laissés côte à côte",
  他见我家事劳苦: "Il a vu ma famille travailler dur",
  日常烦恼: "Troubles quotidiens",
  教我遇烦恼时: "Apprenez-moi quand je rencontre des problèmes",
  即把这词儿念念: "C'est-à-dire prononcer ce mot",
  一则散心: "Un relaxant",
  二则解困: "Deux façons de résoudre le problème",
  我才有些不足处思虑: "Je pense à quelque chose de mal",
  故此念念: "Par conséquent, cette pensée",
  不期被你听了: "De façon inattendue, vous l'écoutez",
  猴王道: "Le chemin du roi du singe",
  你家既与神仙相邻: "Votre maison est adjacente aux dieux",
  何不从他修行: "Pourquoi ne pas pratiquer avec lui",
  学得个不老之方: "Apprendre un moyen de ne jamais vieillir",
  却不是好: "Mais pas bon",
  樵夫道: "La voie de Woodman",
  我一生命苦: "Ma vie est misérable",
  自幼蒙父母养育至八九岁:
    "Il a été élevé par ses parents jusqu'à l'âge de huit ou neuf ans",
  才知人事: "Ce n'est qu'alors que vous pouvez connaître les gens",
  不幸父丧: "Malheureusement, mon père est mort",
  母亲居孀: "La mère est veuve",
  再无兄弟姊妹: "Plus de frères et sœurs",
  只我一人: "Je suis le seul",
  没奈何: "Rien à faire",
  早晚侍奉: "Service du matin et du soir",
  如今母老: "Maintenant mère",
  一发不敢抛离: "N'ose pas partir",
  却又田园荒芜: "Mais c'est pastoral et déserté",
  衣食不足: "Nourriture et vêtements insuffisants",
  只得斫两束柴薪: "J'ai dû couper deux paquets de bois de chauffage",
  挑向市尘之间: "Choisissez entre la poussière de la ville",
  货几文钱: "Combien ça coûte",
  籴几升米: "Combien de litres de riz à acheter",
  自炊自造: "Indéfiniment et auto-fabriqué",
  安排些茶饭: "Organiser du thé et du riz",
  供养老母: "Prévoir des mères âgées",
  所以不能修行: "Donc tu ne peux pas pratiquer",
  猴王道: "Le chemin du roi du singe",
  据你说起来: "Comme tu dis",
  乃是一个行孝的君子: "C'est un gentleman filial",
  向后必有好处: "Il y aura des avantages à l'envers",
  但望你指与我那神仙住处:
    "Mais j'espère que vous pointerez vers l'endroit où les dieux vivent avec moi",
  却好拜访去也: "Mais c'est facile de visiter",
  樵夫道: "La voie de Woodman",
  不远: "Pas loin",
  不远: "Pas loin",
  此山叫做灵台方寸山: "Cette montagne s'appelle Lingtai Fangcun Mountain",
  山中有座斜月三星洞: "Il y a une grotte de lune inclinée dans les montagnes",
  那洞中有一个神仙: "Il y a un dieu dans cette grotte",
  称名须菩提祖师: "Nommez le nom du maître Subhuti",
  那祖师出去的徒弟: "Le disciple qui est sorti",
  也不计其数: "Pas de compte",
  见今还有三四十人从他修行:
    "Voyant qu'il y a encore trente ou quarante personnes qui s'entraînent de lui maintenant",
  你顺那条小路儿: "Vous suivez ce chemin",
  向南行七八里远近: "Allez vers le sud pendant sept ou huit miles",
  即是他家了: "C'est sa maison",
  猴王用手扯住樵夫道: "Le roi de singe a tiré le bûcheron avec ses mains",
  老兄: "Frère",
  你便同我去去: "Tu vas avec moi",
  若还得了好处: "S'il y a plus d'avantages",
  决不忘你指引之恩: "N'oubliez jamais vos conseils",
  樵夫道: "La voie de Woodman",
  你这汉子: "Toi mec",
  甚不通变: "Pas très modifiable",
  我方才这般与你说了: "Je t'ai dit ça tout à l'heure",
  你还不省: "Tu ne fais pas attention",
  假若我与你去了: "Si je suis allé avec toi",
  却不误了我的生意: "Mais ça n'a pas manqué mon entreprise",
  老母何人奉养: "Qui se soucie de ma mère?",
  我要斫柴: "Je veux hacher le bois de chauffage",
  你自去: "Tu vas seul",
  自去: "Aller seul",
};

const tianwen_translation_map_de = {
  登岸偏访多时: "Lange Zeit zu landen",
  忽见一座高山秀丽: "Plötzlich sah ich einen schönen Berg",
  林麓幽深: "Der Wald ist tief",
  他也不怕狼虫: "Er hat auch keine Angst vor Wolfsekten",
  不惧虎豹: "Keine Angst vor Tigern und Leoparden",
  登山顶上观: "Beobachten Sie von der Spitze des Berges",
  正观看间: "Raum beobachten",
  忽闻得林深之处: "Plötzlich hörte ich den tiefen Wald",
  有人言语: "Jemandes Worte",
  急忙趋步: "In Eile reden",
  穿入林中: "In den Wald übergehen",
  侧耳而听: "Hören Sie mit Ihren Ohren zu",
  原来是歌唱之声: "Es stellt sich heraus, dass es der Klang des Singens ist",
  歌: "Lied",
  观棋柯烂: "Schach zu beobachten ist schlecht",
  伐木丁丁: "Dosen schneiden",
  云边谷口徐行: "Langsam am Eingang des Tals durch die Wolken gehen",
  卖薪沽酒: "Wein verkaufen",
  狂笑自陶情: "Wild verliebt lachen",
  苍迳秋高: "Der Herbst ist hoch am Himmel",
  对月枕松根: "Wurzeln auf dem Mond",
  一觉天明: "Eine plötzliche Morgendämmerung",
  认旧林: "Erkenne den alten Wald",
  登崖过岭: "Klettern Sie die Klippe und überqueren den Kamm",
  持斧断枯: "Halten Sie eine Axt und zerbrechen Sie",
  收来成一担: "Sammle es in einen Hebel",
  行歌市上: "Auf dem Xingge -Markt",
  易米三升: "Yimi drei Liter",
  更无些子争竞: "Es gibt keinen Wettbewerb",
  时价平平: "Der aktuelle Preis ist durchschnittlich",
  不会机谋巧算: "Kann nicht Pläne machen",
  没荣辱: "Keine Ehre und Schande",
  恬淡延生: "Ruhe und Verlängerung des Lebens",
  相逢处: "Wo zu treffen",
  非仙即道: "Entweder unsterblich oder tao",
  静坐讲黄庭: "In Meditation sitzen und über Huang Ting sprechen",
  美猴王听得此言: "Der Affenkönig hörte das",
  满心欢喜道: "Sagte mit Freude",
  神仙原来藏在这里: "Die Götter sind hier versteckt",
  急忙跳入里面: "Schnell hineinspringen",
  仔细再看: "Schauen Sie sich genau an",
  乃是一个樵子: "Es ist ein Holzfäller",
  在那里举斧砍: "Dort mit einer Axt hacken",
  猴王近前叫道: "Der Affenkönig rief",
  老神仙: "Alter Gott",
  弟子起手: "Schüler beginnt",
  那樵汉慌忙丢了斧: "Das Holzfäller warf eilig seine Axt weg",
  转身答礼道: "Drehen Sie sich um und beantworten Sie das Ritual",
  不当人: "Kein Mensch sein",
  不当人: "Kein Mensch sein",
  我拙汉衣食不全: "Mein Mann ist nicht vollständig gefüttert und gefüttert.",
  怎敢当神仙二字: "Wie kannst du es wagen, ein Gott zu sein?",
  猴王道: "Der Weg des Affenkönigs",
  你不是神仙: "Du bist kein Gott",
  如何说出神仙的话来: "Wie sagt man die Götter",
  樵夫道: "Der Weg des Woodman",
  我说甚么神仙话: "Welche Märchenwörter sage ich",
  猴王道: "Der Weg des Affenkönigs",
  我才来至林边: "Ich bin gerade im Linken angekommen",
  只听的你说: "Ich höre dir nur zu",
  相逢处非仙即道: "Wo wir uns treffen, ist weder unsterblich noch tao",
  静坐讲黄庭: "In Meditation sitzen und über Huang Ting sprechen",
  黄庭乃道德真言: "Huang Ting ist die moralische Wahrheit",
  非神仙而何: "Was ist kein Gott",
  樵夫笑道: "Das Holzfäller lächelte",
  实不瞒你说: "Ich werde es vor dir verstecken",
  这个词名做满庭芳: "Das Wort heißt Mantingfang",
  乃一神仙教我的: "Es wurde von einem Gott gelehrt",
  那神仙与我舍下相邻: "Der Gott und ich haben uns nebeneinander gelassen",
  他见我家事劳苦: "Er sah meine Familie hart arbeiten",
  日常烦恼: "Tägliche Probleme",
  教我遇烦恼时: "Lehre mich, wenn ich auf Probleme stoße",
  即把这词儿念念: "Das heißt, spricht dieses Wort aus",
  一则散心: "Ein Entspannung",
  二则解困: "Zwei Möglichkeiten, das Problem zu lösen",
  我才有些不足处思虑: "Ich denke an etwas, das falsch ist",
  故此念念: "Deshalb dieser Gedanke",
  不期被你听了: "Unerwartet werden Sie es hören",
  猴王道: "Der Weg des Affenkönigs",
  你家既与神仙相邻: "Ihr Zuhause ist neben den Göttern neben",
  何不从他修行: "Warum nicht mit ihm üben?",
  学得个不老之方: "Einen Weg lernen, niemals alt zu werden",
  却不是好: "Aber nicht gut",
  樵夫道: "Der Weg des Woodman",
  我一生命苦: "Mein Leben ist elend",
  自幼蒙父母养育至八九岁:
    "Er wurde von seinen Eltern aufgewachsen, bis er acht oder neun Jahre alt war",
  才知人事: "Nur dann können Sie Leute kennen",
  不幸父丧: "Leider starb mein Vater",
  母亲居孀: "Mutter ist verwitwet",
  再无兄弟姊妹: "Keine Brüder und Schwestern mehr",
  只我一人: "Ich bin der einzige",
  没奈何: "Nichts zu tun",
  早晚侍奉: "Morgen- und Abendgottesdienst",
  如今母老: "Jetzt Mutter",
  一发不敢抛离: "Wagen Sie es nicht zu gehen, zu gehen",
  却又田园荒芜: "Aber es ist pastoral und verlassen",
  衣食不足: "Unzureichende Nahrung und Kleidung",
  只得斫两束柴薪: "Ich musste zwei Bündel Brennholz schneiden",
  挑向市尘之间: "Wählen Sie zwischen dem Staub der Stadt",
  货几文钱: "Wie viel kostet es",
  籴几升米: "Wie viele Liter Reis zu kaufen",
  自炊自造: "Selbstversorgung und selbstgemacht",
  安排些茶饭: "Arrangieren Sie etwas Tee und Reis",
  供养老母: "Für ältere Mütter sorgen",
  所以不能修行: "Sie können also nicht üben",
  猴王道: "Der Weg des Affenkönigs",
  据你说起来: "Wie du sagst",
  乃是一个行孝的君子: "Er ist ein kindlicher Gentleman",
  向后必有好处: "Es wird rückwärts Vorteile geben",
  但望你指与我那神仙住处:
    "Aber ich hoffe du verweist auf den Ort, an dem die Götter mit mir leben",
  却好拜访去也: "Aber es ist einfach zu besuchen",
  樵夫道: "Der Weg des Woodman",
  不远: "Nicht weit",
  不远: "Nicht weit",
  此山叫做灵台方寸山: "Dieser Berg heißt Lingtai Fangcun Mountain",
  山中有座斜月三星洞: "In den Bergen gibt es eine schräge Mondhöhle",
  那洞中有一个神仙: "Es gibt einen Gott in dieser Höhle",
  称名须菩提祖师: "Nennen Sie den Namen des Meisters Subhuti",
  那祖师出去的徒弟: "Der Jünger, der ausging",
  也不计其数: "Keine Zählung",
  见今还有三四十人从他修行:
    "Und sehen, dass es jetzt noch dreißig oder vierzig Menschen von ihm üben",
  你顺那条小路儿: "Sie folgen diesem Weg",
  向南行七八里远近: "Geh für sieben oder acht Meilen nach Süden",
  即是他家了: "Es ist sein Haus",
  猴王用手扯住樵夫道: "Der Affenkönig zog das Holzschnitzer mit seinen Händen",
  老兄: "Bruder",
  你便同我去去: "Du wirst mit mir gehen",
  若还得了好处: "Wenn es mehr Vorteile gibt",
  决不忘你指引之恩: "Vergessen Sie niemals Ihre Anleitung",
  樵夫道: "Der Weg des Woodman",
  你这汉子: "Ihr Typ",
  甚不通变: "Nicht sehr wechselhaft",
  我方才这般与你说了: "Ich habe dir das gerade gesagt",
  你还不省: "Du bist nicht aufpassen",
  假若我与你去了: "Wenn ich mit dir ging",
  却不误了我的生意: "Aber es vermisste mein Geschäft nicht",
  老母何人奉养: "Wen kümmert sich um meine Mutter?",
  我要斫柴: "Ich möchte Brennholz hacken",
  你自去: "Du gehst alleine",
  自去: "Geh alleine",
};

tianwen_translation_map_en = {
  登岸偏访多时: "Long time to land",
  忽见一座高山秀丽: "Suddenly I saw a beautiful mountain",
  林麓幽深: "The forest is deep",
  他也不怕狼虫: "He's not afraid of wolf insects either",
  不惧虎豹: "Not afraid of tigers and leopards",
  登山顶上观: "Watch from the top of the mountain",
  正观看间: "Watching room",
  忽闻得林深之处: "Suddenly I heard the deep forest",
  有人言语: "Someone's words",
  急忙趋步: "Talking in a hurry",
  穿入林中: "Passing into the forest",
  侧耳而听: "Listen with your ears",
  原来是歌唱之声: "It turns out to be the sound of singing",
  歌: "Song",
  观棋柯烂: "Watching chess is bad",
  伐木丁丁: "Cutting tins",
  云边谷口徐行: "Walking slowly at the entrance of the valley by the clouds",
  卖薪沽酒: "Selling wine",
  狂笑自陶情: "Laughing wildly in love",
  苍迳秋高: "The autumn is high in the sky",
  对月枕松根: "Pineal roots on the moon",
  一觉天明: "A sudden dawn",
  认旧林: "Recognize the old forest",
  登崖过岭: "Climbing the cliff and crossing the ridge",
  持斧断枯: "Hold an axe and break wither",
  收来成一担: "Collect it into a lever",
  行歌市上: "On the Xingge Market",
  易米三升: "Yimi three liters",
  更无些子争竞: "There is no competition",
  时价平平: "The current price is average",
  不会机谋巧算: "Can't make plans",
  没荣辱: "No honor and disgrace",
  恬淡延生: "Tranquility and prolong life",
  相逢处: "Where to meet",
  非仙即道: "Either immortal or Tao",
  静坐讲黄庭: "Sitting in meditation and talking about Huang Ting",
  美猴王听得此言: "The Monkey King heard this",
  满心欢喜道: "Said with joy",
  神仙原来藏在这里: "The gods are hidden here",
  急忙跳入里面: "Jump inside quickly",
  仔细再看: "Look carefully",
  乃是一个樵子: "It's a woodcutter",
  在那里举斧砍: "Chop there with an axe",
  猴王近前叫道: "The Monkey King shouted",
  老神仙: "Old God",
  弟子起手: "Disciple starts",
  那樵汉慌忙丢了斧: "The woodcutter hurriedly threw away his axe",
  转身答礼道: "Turn around and answer the ritual",
  不当人: "Not being a human",
  不当人: "Not being a human",
  我拙汉衣食不全: "My husband is not fully fed and fed.",
  怎敢当神仙二字: "How dare you be a god",
  猴王道: "The Monkey King's Way",
  你不是神仙: "You're not a god",
  如何说出神仙的话来: "How to say the gods",
  樵夫道: "The Woodman's Way",
  我说甚么神仙话: "What fairy words do I say",
  猴王道: "The Monkey King's Way",
  我才来至林边: "I've just arrived in Linbing",
  只听的你说: "I just listen to you",
  相逢处非仙即道: "Where we meet is neither immortal nor Tao",
  静坐讲黄庭: "Sitting in meditation and talking about Huang Ting",
  黄庭乃道德真言: "Huang Ting is the moral truth",
  非神仙而何: "What's not a god",
  樵夫笑道: "The woodcutter smiled",
  实不瞒你说: "I'm going to hide it from you",
  这个词名做满庭芳: "The word is called Mantingfang",
  乃一神仙教我的: "It was taught by a god",
  那神仙与我舍下相邻: "The god and I have left each other next to each other",
  他见我家事劳苦: "He saw my family work hard",
  日常烦恼: "Daily troubles",
  教我遇烦恼时: "Teach me when I encounter troubles",
  即把这词儿念念: "That is, pronounce this word",
  一则散心: "A relaxing",
  二则解困: "Two ways to solve the problem",
  我才有些不足处思虑: "I'm thinking about something wrong",
  故此念念: "Therefore, this thought",
  不期被你听了: "Unexpectedly you will listen to it",
  猴王道: "The Monkey King's Way",
  你家既与神仙相邻: "Your home is adjacent to the gods",
  何不从他修行: "Why not practice with him",
  学得个不老之方: "Learn a way to never grow old",
  却不是好: "But not good",
  樵夫道: "The Woodman's Way",
  我一生命苦: "My life is miserable",
  自幼蒙父母养育至八九岁:
    "He was raised by his parents until he was eight or nine years old",
  才知人事: "Only then can you know people",
  不幸父丧: "Unfortunately, my father died",
  母亲居孀: "Mother is widowed",
  再无兄弟姊妹: "No more brothers and sisters",
  只我一人: "I'm the only one",
  没奈何: "Nothing to do",
  早晚侍奉: "morning and evening service",
  如今母老: "Now mother",
  一发不敢抛离: "Don't dare to leave",
  却又田园荒芜: "But it's pastoral and deserted",
  衣食不足: "Insufficient food and clothing",
  只得斫两束柴薪: "I had to cut two bundles of firewood",
  挑向市尘之间: "Choose between the dust of the city",
  货几文钱: "How much does it cost",
  籴几升米: "How many liters of rice to buy",
  自炊自造: "Self-catering and self-made",
  安排些茶饭: "Arrange some tea and rice",
  供养老母: "Provide for elderly mothers",
  所以不能修行: "So you can't practice",
  猴王道: "The Monkey King's Way",
  据你说起来: "As you say",
  乃是一个行孝的君子: "He is a filial gentleman",
  向后必有好处: "There will be benefits backwards",
  但望你指与我那神仙住处:
    "But I hope you point to the place where the gods live with me",
  却好拜访去也: "But it's easy to visit",
  樵夫道: "The Woodman's Way",
  不远: "Not far",
  不远: "Not far",
  此山叫做灵台方寸山: "This mountain is called Lingtai Fangcun Mountain",
  山中有座斜月三星洞: "There is a slanting moon cave in the mountains",
  那洞中有一个神仙: "There is a god in that cave",
  称名须菩提祖师: "Name the name of the Master Subhuti",
  那祖师出去的徒弟: "The disciple who went out",
  也不计其数: "No count",
  见今还有三四十人从他修行:
    "Seeing that there are still thirty or forty people practicing from him now",
  你顺那条小路儿: "You follow that path",
  向南行七八里远近: "Go south for seven or eight miles",
  即是他家了: "It's his house",
  猴王用手扯住樵夫道: "The Monkey King pulled the woodcutter with his hands",
  老兄: "Brother",
  你便同我去去: "You'll go with me",
  若还得了好处: "If there are more benefits",
  决不忘你指引之恩: "Never forget your guidance",
  樵夫道: "The Woodman's Way",
  你这汉子: "You guy",
  甚不通变: "Not very changeable",
  我方才这般与你说了: "I've told you this just now",
  你还不省: "You're not careful",
  假若我与你去了: "If I went with you",
  却不误了我的生意: "But it didn't miss my business",
  老母何人奉养: "Who cares about my mother?",
  我要斫柴: "I want to chop firewood",
  你自去: "You go by yourself",
  自去: "Go by yourself",
};

// 初始化语音合成
const synth = window.speechSynthesis;
let utterance = null;

// 状态跟踪
const charStates = {};

// 页面加载完成后初始化
document.addEventListener("DOMContentLoaded", function () {
  renderPoem();
});

// 渲染诗歌
function renderPoem() {
  const poemContainer = document.getElementById("poemContainer");
  const lines = poemText.split("\n");

  lines.forEach((line) => {
    const lineDiv = document.createElement("div");
    lineDiv.className = "poem-line";

    // 处理每个字符
    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      // 跳过空格
      if (char.trim() === "") {
        const spaceSpan = document.createElement("span");
        spaceSpan.textContent = " ";
        lineDiv.appendChild(spaceSpan);
        continue;
      }

      // 创建字符容器
      const charContainer = document.createElement("div");
      charContainer.className = "char-container";

      // 创建字符显示
      const charSpan = document.createElement("span");
      charSpan.className = "char";
      charSpan.textContent = char;

      // 创建拼音显示
      const pinyinSpan = document.createElement("span");
      pinyinSpan.className = "pinyin";

      // 创建翻译显示
      const transSpan = document.createElement("span");
      transSpan.className = "translation";

      // 添加到容器
      charContainer.appendChild(pinyinSpan);
      charContainer.appendChild(charSpan);
      charContainer.appendChild(transSpan);

      // 添加点击事件
      charContainer.addEventListener("click", () =>
        handleCharClick(char, pinyinSpan, transSpan)
      );

      // 添加到行
      lineDiv.appendChild(charContainer);
    }

    // 添加行控制按钮
    const controlsDiv = document.createElement("div");
    controlsDiv.className = "line-controls";

    const readBtn = document.createElement("button");
    readBtn.textContent = "朗读";
    readBtn.addEventListener("click", () => readLine(line));

    const transBtn = document.createElement("button");
    transBtn.textContent = "翻译";
    transBtn.addEventListener("click", () => showLineTranslation(line));

    controlsDiv.appendChild(readBtn);
    controlsDiv.appendChild(transBtn);
    lineDiv.appendChild(controlsDiv);

    // 添加到容器
    poemContainer.appendChild(lineDiv);
  });
}

// 处理字符点击
function handleCharClick(char, pinyinSpan, transSpan) {
  const charId = `${char}-${pinyinSpan.id}`; // 创建唯一标识

  // 初始化状态
  if (!charStates[charId]) {
    charStates[charId] = 0;
  }

  // 更新状态
  charStates[charId]++;
  if (charStates[charId] > 3) {
    charStates[charId] = 1;
  }

  // 根据状态执行操作
  switch (charStates[charId]) {
    case 1: // 朗读字符
      readChar(char);
      updateStatus(`朗读字符: ${char}`);
      break;
    case 2: // 显示拼音
      showPinyin(char, pinyinSpan);
      updateStatus(`显示拼音: ${char}`);
      break;
    case 3: // 显示翻译
      showTranslation(char, transSpan);
      updateStatus(`显示翻译: ${char}`);
      break;
  }
}

// 显示拼音
function showPinyin(char, pinyinSpan) {
  // 这里应该调用拼音库，简化处理

  const py = pinyinMap[char] || "?";
  pinyinSpan.textContent = py;
  pinyinSpan.style.display = "block";

  // 3秒后自动隐藏
  setTimeout(() => {
    pinyinSpan.style.display = "none";
    // 重置状态以便下次点击
    const charId = `${char}-${pinyinSpan.id}`;
    charStates[charId] = 0;
  }, 8000);
}

// 朗读字符
function readChar(char) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(char);
  utterance.lang = "zh-CN";
  utterance.rate = 0.7; // 设置为正常速度的70%
  synth.speak(utterance);
}

// 显示翻译
function showTranslation(char, transSpan) {
  const lang = document.getElementById("languageSelect").value;

  const translationCard = document.getElementById("translationCard");

  const translateMap = {
    de: translations_de[char] || "Keine Übersetzung",
    fr: translations_fr[char] || "Pas de traduction",
    en: translations_en[char] || "No translation",
  };
  const translate = translateMap[lang];
  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">汉字：</div>
    <div class="info-content">${char}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translate}</div>
  </div>
`;

  translationCard.style.display = "block";

  const charId = `${char}-${transSpan.id}`;
  charStates[charId] = 0;
}

function closeTranslationCard() {
  const translationCard = document.getElementById("translationCard");
  translationCard.style.display = "none";
}

// 朗读整行
function readLine(line) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(line);
  utterance.lang = "zh-CN";
  utterance.rate = 0.6; // 设置为正常速度的60%，更慢一些
  synth.speak(utterance);

  updateStatus(`朗读: ${line}`);
}

function showLineTranslation(line) {
  const lang = document.getElementById("languageSelect").value;
  const translatedMap = {
    de: tianwen_translation_map_de,
    fr: tianwen_translation_map_fr,
    en: tianwen_translation_map_en,
  };
  const translatedLine =
    translatedMap[lang]?.[line] || "（keine Übersetzung gefunden）";
  const translationCard = document.getElementById("translationCard");

  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">原文：</div>
    <div class="info-content">${line}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translatedLine}</div>
  </div>
`;

  translationCard.style.display = "block";

  updateStatus(`显示翻译: ${line.substring(0, 15)}...`);
}

// 更新状态栏
function updateStatus(message) {
  document.getElementById("statusBar").textContent = message;
}
