const translationCard = document.getElementById("translationCard");
// 诗歌文本c
const poemText = `悟空见没奈何
只得拜辞
与众相别
祖师道
你这去
定生不良
凭你怎么惹祸行凶
却不许说是我的徒弟
你说出半个字来
我就知之
把你这猢狲剥皮锉骨
将神魂贬在九幽之处
教你万劫不得翻身
悟空道
决不敢提起师父一字
只说是我自家会的便罢
悟空谢了
即抽身
捻着诀
丢个连扯
纵起筋斗云
径回东海
那里消一个时辰
早看见花果山水帘洞
美猴王自知快乐
暗暗的自称道
去时凡骨凡胎重
得道身轻体亦轻
举世无人肯立志
立志修玄玄自明
当时过海波难进
今日来回甚易行
别语叮咛还在耳
何期顷刻见东溟
悟空按下云头
直至花果山
找路而走
忽听得鹤唳猿啼
鹤唳声冲霄汉外
猿啼悲切甚伤情
即开口叫道
孩儿们
我来了也
那崖下石坎边
花草中
树木里
若大若小之猴
跳出千千万万
把个美猴王围在当中
叩头叫道
大王
你好宽心
怎么一去许久
把我们俱闪在这里
望你诚如饥渴
近来被一妖魔在此欺虐
强要占我们水帘洞府
是我等舍死忘生
与他争斗
这些时
被那厮抢了我们家火
捉了许多子侄
教我们昼夜无眠
看守家业
幸得大王来了
大王若再年载不来
我等连山洞尽属他人矣
悟空闻说
心中大怒道
是什么妖魔
辄敢无状
你且细细说来
待我寻他报仇
众猴叩头
告上大王
那厮自称混世魔王
住居在直北下
悟空道
此间到他那里
有多少路程
众猴道
他来时云
去时雾
或风或雨
或电或雷
我等不知有多少路
悟空道
既如此
你们休怕
且自顽耍
等我寻他去来`;

const pinyinMap = {
  悟: "wù",
  空: "kōng",
  见: "jiàn",
  没: "mò",
  奈: "nài",
  何: "hé",
  只: "zhǐ",
  得: "de",
  拜: "bài",
  辞: "cí",
  与: "yǔ",
  众: "zhòng",
  相: "xiāng",
  别: "bié",
  祖: "zǔ",
  师: "shī",
  道: "dào",
  你: "nǐ",
  这: "zhè",
  去: "qù",
  定: "dìng",
  生: "shēng",
  不: "bù",
  良: "liáng",
  凭: "píng",
  怎: "zěn",
  么: "me",
  惹: "rě",
  祸: "huò",
  行: "xíng",
  凶: "xiōng",
  却: "què",
  许: "xǔ",
  说: "shuō",
  是: "shì",
  我: "wǒ",
  的: "de",
  徒: "tú",
  弟: "dì",
  出: "chū",
  半: "bàn",
  个: "gè",
  字: "zì",
  来: "lái",
  就: "jiù",
  知: "zhī",
  之: "zhī",
  把: "bǎ",
  猢: "hú",
  狲: "sūn",
  剥: "bāo",
  皮: "pí",
  锉: "cuò",
  骨: "gǔ",
  将: "jiāng",
  神: "shén",
  魂: "hún",
  贬: "biǎn",
  在: "zài",
  九: "jiǔ",
  幽: "yōu",
  处: "chù",
  教: "jiào",
  万: "wàn",
  劫: "jié",
  翻: "fān",
  身: "shēn",
  决: "jué",
  敢: "gǎn",
  提: "tí",
  起: "qǐ",
  父: "fù",
  一: "yī",
  自: "zì",
  家: "jiā",
  会: "huì",
  便: "biàn",
  罢: "bà",
  谢: "xiè",
  了: "le",
  即: "jí",
  抽: "chōu",
  捻: "niǎn",
  着: "zhe",
  诀: "jué",
  丢: "diū",
  连: "lián",
  扯: "chě",
  纵: "zòng",
  筋: "jīn",
  斗: "dǒu",
  云: "yún",
  径: "jìng",
  回: "huí",
  东: "dōng",
  海: "hǎi",
  那: "nà",
  里: "lǐ",
  消: "xiāo",
  时: "shí",
  辰: "chén",
  早: "zǎo",
  看: "kàn",
  花: "huā",
  果: "guǒ",
  山: "shān",
  水: "shuǐ",
  帘: "lián",
  洞: "dòng",
  美: "měi",
  猴: "hóu",
  王: "wáng",
  快: "kuài",
  乐: "lè",
  暗: "àn",
  称: "chēng",
  凡: "fán",
  胎: "tāi",
  重: "zhòng",
  轻: "qīng",
  体: "tǐ",
  亦: "yì",
  举: "jǔ",
  世: "shì",
  无: "wú",
  人: "rén",
  肯: "kěn",
  立: "lì",
  志: "zhì",
  修: "xiū",
  玄: "xuán",
  明: "míng",
  当: "dāng",
  过: "guò",
  波: "bō",
  难: "nán",
  进: "jìn",
  今: "jīn",
  日: "rì",
  甚: "shèn",
  易: "yì",
  语: "yǔ",
  叮: "dīng",
  咛: "níng",
  还: "hái",
  耳: "ěr",
  期: "qī",
  顷: "qǐng",
  刻: "kè",
  溟: "míng",
  按: "àn",
  下: "xià",
  头: "tou",
  直: "zhí",
  至: "zhì",
  找: "zhǎo",
  路: "lù",
  而: "ér",
  走: "zǒu",
  忽: "hū",
  听: "tīng",
  鹤: "hè",
  唳: "lì",
  猿: "yuán",
  啼: "tí",
  声: "shēng",
  冲: "chōng",
  霄: "xiāo",
  汉: "hàn",
  外: "wài",
  悲: "bēi",
  切: "qiè",
  伤: "shāng",
  情: "qíng",
  开: "kāi",
  口: "kǒu",
  叫: "jiào",
  孩: "hái",
  儿: "ér",
  们: "men",
  也: "yě",
  崖: "yá",
  石: "shí",
  坎: "kǎn",
  边: "biān",
  草: "cǎo",
  中: "zhōng",
  树: "shù",
  木: "mù",
  若: "ruò",
  大: "dà",
  小: "xiǎo",
  跳: "tiào",
  千: "qiān",
  围: "wéi",
  叩: "kòu",
  好: "hǎo",
  宽: "kuān",
  心: "xīn",
  久: "jiǔ",
  俱: "jù",
  闪: "shǎn",
  望: "wàng",
  诚: "chéng",
  如: "rú",
  饥: "jī",
  渴: "kě",
  近: "jìn",
  被: "bèi",
  妖: "yāo",
  魔: "mó",
  此: "cǐ",
  欺: "qī",
  虐: "nüè",
  强: "qiáng",
  要: "yào",
  占: "zhàn",
  府: "fǔ",
  等: "děng",
  舍: "shě",
  死: "sǐ",
  忘: "wàng",
  他: "tā",
  争: "zhēng",
  些: "xiē",
  厮: "sī",
  抢: "qiǎng",
  火: "huǒ",
  捉: "zhuō",
  多: "duō",
  子: "zi",
  侄: "zhí",
  昼: "zhòu",
  夜: "yè",
  眠: "mián",
  守: "shǒu",
  业: "yè",
  幸: "xìng",
  再: "zài",
  年: "nián",
  载: "zài",
  尽: "jǐn",
  属: "shǔ",
  矣: "yǐ",
  闻: "wén",
  怒: "nù",
  什: "shén",
  辄: "zhé",
  状: "zhuàng",
  且: "qiě",
  细: "xì",
  待: "dài",
  寻: "xún",
  报: "bào",
  仇: "chóu",
  告: "gào",
  上: "shàng",
  混: "hùn",
  住: "zhù",
  居: "jū",
  北: "běi",
  间: "jiān",
  到: "dào",
  有: "yǒu",
  少: "shǎo",
  程: "chéng",
  雾: "wù",
  或: "huò",
  风: "fēng",
  雨: "yǔ",
  电: "diàn",
  雷: "léi",
  既: "jì",
  休: "xiū",
  怕: "pà",
  顽: "wán",
  耍: "shuǎ",
};

const translations_en = {
  悟: "Enlightenment",
  空: "null",
  见: "See",
  没: "without",
  奈: "Nye",
  何: "what",
  只: "Only",
  得: "have to",
  拜: "bye",
  辞: "Quotation",
  与: "and",
  众: "All",
  相: "Mutually",
  别: "Don't",
  祖: "Ancestor",
  师: "division",
  道: "road",
  你: "you",
  这: "this",
  去: "go",
  定: "Certainly",
  生: "born",
  不: "No",
  良: "good",
  凭: "By",
  怎: "How",
  么: "Is it",
  惹: "provoke",
  祸: "disaster",
  行: "OK",
  凶: "fierce",
  却: "but",
  许: "May",
  说: "explain",
  是: "yes",
  我: "I",
  的: "of",
  徒: "only",
  弟: "younger brother",
  出: "out",
  半: "Half",
  个: "indivual",
  字: "Character",
  来: "Come",
  就: "At once",
  知: "Know",
  之: "Of",
  把: "Bundle",
  猢: "Money",
  狲: "可",
  剥: "peel",
  皮: "Skin",
  锉: "file",
  骨: "bone",
  将: "Will",
  神: "god",
  魂: "soul",
  贬: "derogatory",
  在: "exist",
  九: "Nine",
  幽: "quiet",
  处: "Where",
  教: "teach",
  万: "Ten thousand",
  劫: "Calamity",
  翻: "turn",
  身: "body",
  决: "Decision",
  敢: "dare",
  提: "carry",
  起: "rise",
  父: "father",
  一: "one",
  自: "since",
  家: "Home",
  会: "meeting",
  便: "Hope",
  罢: "stop",
  谢: "Thanks",
  了: "It's",
  即: "Right now",
  抽: "smoke",
  捻: "twist",
  着: "Put",
  诀: "Tips",
  丢: "leave",
  连: "even",
  扯: "pull",
  纵: "vertical",
  筋: "Tendons",
  斗: "fight",
  云: "cloud",
  径: "path",
  回: "Back",
  东: "East",
  海: "ocean",
  那: "That",
  里: "inside",
  消: "remove",
  时: "hour",
  辰: "Chen",
  早: "morning",
  看: "look",
  花: "flower",
  果: "fruit",
  山: "Mountain",
  水: "water",
  帘: "curtain",
  洞: "Hole",
  美: "beautiful",
  猴: "monkey",
  王: "king",
  快: "quick",
  乐: "happy",
  暗: "dark",
  称: "say",
  凡: "Any",
  胎: "fetal",
  重: "Heavy",
  轻: "light",
  体: "body",
  亦: "as well as",
  举: "Lift",
  世: "World",
  无: "none",
  人: "people",
  肯: "Ken",
  立: "stand",
  志: "Chronicle",
  修: "build",
  玄: "mysterious",
  明: "bright",
  当: "when",
  过: "Pass",
  波: "Wave",
  难: "Disaster",
  进: "Enter",
  今: "now",
  日: "day",
  甚: "very",
  易: "easy",
  语: "language",
  叮: "bite",
  咛: "Reminder",
  还: "return",
  耳: "Ear",
  期: "Expect",
  顷: "沪",
  刻: "carve",
  溟: "sea",
  按: "according to",
  下: "Down",
  头: "head",
  直: "straight",
  至: "to",
  找: "try to find",
  路: "road",
  而: "and",
  走: "Walk",
  忽: "suddenly",
  听: "listen",
  鹤: "crane",
  唳: "Trench",
  猿: "ape",
  啼: "cry",
  声: "Voice",
  冲: "rush",
  霄: "Sky",
  汉: "Chinese",
  外: "outside",
  悲: "sad",
  切: "cut",
  伤: "hurt",
  情: "Affection",
  开: "open",
  口: "mouth",
  叫: "Call",
  孩: "child",
  儿: "Son",
  们: "We",
  也: "also",
  崖: "Cliff",
  石: "stone",
  坎: "Kan",
  边: "side",
  草: "Grass",
  中: "middle",
  树: "Tree",
  木: "Wood",
  若: "like",
  大: "big",
  小: "Small",
  跳: "Jump",
  千: "thousand",
  围: "Surrounding",
  叩: "knock",
  好: "good",
  宽: "Width",
  心: "Heart",
  久: "Long",
  俱: "all",
  闪: "flash",
  望: "see",
  诚: "Sincere",
  如: "like",
  饥: "hungry",
  渴: "thirsty",
  近: "close",
  被: "quilt",
  妖: "Demon",
  魔: "magic",
  此: "this",
  欺: "bully",
  虐: "Abusive",
  强: "powerful",
  要: "want",
  占: "occupy",
  府: "House",
  等: "wait",
  舍: "Abandon",
  死: "die",
  忘: "forget",
  他: "he",
  争: "Contend",
  些: "some",
  厮: "Friend",
  抢: "Rob",
  火: "fire",
  捉: "catch",
  多: "many",
  子: "son",
  侄: "nephew",
  昼: "day",
  夜: "night",
  眠: "sleep",
  守: "Guard",
  业: "Industry",
  幸: "fortunate",
  再: "Again",
  年: "Year",
  载: "load",
  尽: "All",
  属: "Generic",
  矣: "It's OK",
  闻: "smell",
  怒: "anger",
  什: "Varied",
  辄: "Every",
  状: "shape",
  且: "and",
  细: "thin",
  待: "treat",
  寻: "Looking for",
  报: "Report",
  仇: "hatred",
  告: "tell",
  上: "superior",
  混: "mix",
  住: "live",
  居: "Residence",
  北: "north",
  间: "between",
  到: "arrive",
  有: "have",
  少: "few",
  程: "Procedure",
  雾: "fog",
  或: "or",
  风: "wind",
  雨: "rain",
  电: "electricity",
  雷: "thunder",
  既: "now that",
  休: "stop",
  怕: "Afraid",
  顽: "stubborn",
  耍: "Play",
};

const translations_de = {
  悟: "Aufklärung",
  空: "NULL",
  见: "Sehen",
  没: "ohne",
  奈: "Nye",
  何: "Was",
  只: "Nur",
  得: "müssen",
  拜: "Tschüss",
  辞: "Zitat",
  与: "Und",
  众: "Alle",
  相: "Gegenseitig",
  别: "Nicht",
  祖: "Vorfahr",
  师: "Division",
  道: "Straße",
  你: "Du",
  这: "Das",
  去: "gehen",
  定: "Sicherlich",
  生: "geboren",
  不: "NEIN",
  良: "Gut",
  凭: "Von",
  怎: "Wie",
  么: "Ist es",
  惹: "provozieren",
  祸: "Katastrophe",
  行: "OK",
  凶: "erbittert",
  却: "Aber",
  许: "Mai",
  说: "erklären",
  是: "Ja",
  我: "ICH",
  的: "von",
  徒: "nur",
  弟: "jüngerer Bruder",
  出: "aus",
  半: "Hälfte",
  个: "indival",
  字: "Charakter",
  来: "Kommen",
  就: "Auf einmal",
  知: "Wissen",
  之: "Von",
  把: "Bündeln",
  猢: "Geld",
  狲: "可",
  剥: "schälen",
  皮: "Haut",
  锉: "Datei",
  骨: "Knochen",
  将: "Wille",
  神: "Gott",
  魂: "Seele",
  贬: "abfällig",
  在: "existieren",
  九: "Neun",
  幽: "ruhig",
  处: "Wo",
  教: "unterrichten",
  万: "Zehntausend",
  劫: "Unglück",
  翻: "drehen",
  身: "Körper",
  决: "Entscheidung",
  敢: "wagen",
  提: "tragen",
  起: "erheben",
  父: "Vater",
  一: "eins",
  自: "seit",
  家: "Heim",
  会: "treffen",
  便: "Hoffnung",
  罢: "stoppen",
  谢: "Danke",
  了: "Es ist",
  即: "Im Augenblick",
  抽: "Rauch",
  捻: "Twist",
  着: "Setzen",
  诀: "Tipps",
  丢: "verlassen",
  连: "sogar",
  扯: "ziehen",
  纵: "Vertikale",
  筋: "Sehnen",
  斗: "kämpfen",
  云: "Wolke",
  径: "Weg",
  回: "Zurück",
  东: "Ost",
  海: "Ozean",
  那: "Das",
  里: "innen",
  消: "entfernen",
  时: "Stunde",
  辰: "Chen",
  早: "Morgen",
  看: "sehen",
  花: "Blume",
  果: "Obst",
  山: "Berg",
  水: "Wasser",
  帘: "Vorhang",
  洞: "Loch",
  美: "Schön",
  猴: "Affe",
  王: "König",
  快: "schnell",
  乐: "Glücklich",
  暗: "dunkel",
  称: "sagen",
  凡: "Beliebig",
  胎: "fetal",
  重: "Schwer",
  轻: "Licht",
  体: "Körper",
  亦: "sowie",
  举: "Aufzug",
  世: "Welt",
  无: "keiner",
  人: "Menschen",
  肯: "Ken",
  立: "Stand",
  志: "Chronik",
  修: "bauen",
  玄: "mysteriös",
  明: "hell",
  当: "Wann",
  过: "Passieren",
  波: "Welle",
  难: "Katastrophe",
  进: "Eingeben",
  今: "Jetzt",
  日: "Tag",
  甚: "sehr",
  易: "einfach",
  语: "Sprache",
  叮: "beißen",
  咛: "Erinnerung",
  还: "zurückkehren",
  耳: "Ohr",
  期: "Erwarten",
  顷: "沪",
  刻: "schnitzen",
  溟: "Meer",
  按: "entsprechend",
  下: "Runter",
  头: "Kopf",
  直: "gerade",
  至: "Zu",
  找: "versuche zu finden",
  路: "Straße",
  而: "Und",
  走: "Gehen",
  忽: "plötzlich",
  听: "Hören",
  鹤: "Kran",
  唳: "Graben",
  猿: "Affe",
  啼: "weinen",
  声: "Stimme",
  冲: "eilen",
  霄: "Himmel",
  汉: "chinesisch",
  外: "draußen",
  悲: "traurig",
  切: "schneiden",
  伤: "verletzt",
  情: "Zuneigung",
  开: "offen",
  口: "Mund",
  叫: "Anruf",
  孩: "Kind",
  儿: "Sohn",
  们: "Wir",
  也: "Auch",
  崖: "Cliff",
  石: "Stein",
  坎: "Kan",
  边: "Seite",
  草: "Gras",
  中: "Mitte",
  树: "Baum",
  木: "Holz",
  若: "wie",
  大: "groß",
  小: "Klein",
  跳: "Springen",
  千: "tausend",
  围: "Umgeben",
  叩: "klopfen",
  好: "Gut",
  宽: "Breite",
  心: "Herz",
  久: "Lang",
  俱: "alle",
  闪: "Blitz",
  望: "sehen",
  诚: "Aufrichtig",
  如: "wie",
  饥: "hungrig",
  渴: "durstig",
  近: "schließen",
  被: "Decke",
  妖: "Dämon",
  魔: "Magie",
  此: "Das",
  欺: "schikanieren",
  虐: "Missbräuchlich",
  强: "kraftvoll",
  要: "wollen",
  占: "besetzen",
  府: "Haus",
  等: "Warten",
  舍: "Aufgeben",
  死: "sterben",
  忘: "vergessen",
  他: "Er",
  争: "Kämpfen",
  些: "manche",
  厮: "Freund",
  抢: "Rauben",
  火: "Feuer",
  捉: "fangen",
  多: "viele",
  子: "Sohn",
  侄: "Neffe",
  昼: "Tag",
  夜: "Nacht",
  眠: "schlafen",
  守: "Bewachen",
  业: "Industrie",
  幸: "glücklich",
  再: "Wieder",
  年: "Jahr",
  载: "laden",
  尽: "Alle",
  属: "Generisches",
  矣: "Es ist in Ordnung",
  闻: "Geruch",
  怒: "Wut",
  什: "Unterschiedlich",
  辄: "Jeder",
  状: "Form",
  且: "Und",
  细: "dünn",
  待: "behandeln",
  寻: "Auf der Suche nach",
  报: "Bericht",
  仇: "Hass",
  告: "erzählen",
  上: "Vorgesetzter",
  混: "mischen",
  住: "live",
  居: "Residenz",
  北: "Norden",
  间: "zwischen",
  到: "ankommen",
  有: "haben",
  少: "wenige",
  程: "Verfahren",
  雾: "Nebel",
  或: "oder",
  风: "Wind",
  雨: "Regen",
  电: "Strom",
  雷: "Donner",
  既: "Nun das",
  休: "stoppen",
  怕: "Besorgt",
  顽: "hartnäckig",
  耍: "Spielen",
};

const translations_fr = {
  悟: "Éclaircissement",
  空: "nul",
  见: "Voir",
  没: "sans",
  奈: "Nye",
  何: "quoi",
  只: "Seulement",
  得: "devoir",
  拜: "au revoir",
  辞: "Citation",
  与: "et",
  众: "Tous",
  相: "Mutuellement",
  别: "Ne le faites pas",
  祖: "Ancêtre",
  师: "division",
  道: "route",
  你: "toi",
  这: "ce",
  去: "aller",
  定: "Certainement",
  生: "né",
  不: "Non",
  良: "bien",
  凭: "Par",
  怎: "Comment",
  么: "Est-ce",
  惹: "provoquer",
  祸: "catastrophe",
  行: "D'ACCORD",
  凶: "féroce",
  却: "mais",
  许: "Peut",
  说: "expliquer",
  是: "Oui",
  我: "je",
  的: "de",
  徒: "seulement",
  弟: "jeune frère",
  出: "dehors",
  半: "Moitié",
  个: "autonome",
  字: "Personnage",
  来: "Viens",
  就: "Immédiatement",
  知: "Savoir",
  之: "De",
  把: "Paquet",
  猢: "Argent",
  狲: "可",
  剥: "peler",
  皮: "Peau",
  锉: "déposer",
  骨: "os",
  将: "Volonté",
  神: "Dieu",
  魂: "âme",
  贬: "désobligeant",
  在: "exister",
  九: "Neuf",
  幽: "calme",
  处: "Où",
  教: "enseigner",
  万: "Dix mille",
  劫: "Calamité",
  翻: "tourner",
  身: "corps",
  决: "Décision",
  敢: "oser",
  提: "porter",
  起: "augmenter",
  父: "père",
  一: "un",
  自: "depuis",
  家: "Maison",
  会: "réunion",
  便: "Espoir",
  罢: "arrêt",
  谢: "Merci",
  了: "C'est",
  即: "Tout de suite",
  抽: "fumée",
  捻: "torsion",
  着: "Mettre",
  诀: "Conseils",
  丢: "partir",
  连: "même",
  扯: "tirer",
  纵: "verticale",
  筋: "Tendons",
  斗: "lutte",
  云: "nuage",
  径: "chemin",
  回: "Dos",
  东: "Est",
  海: "océan",
  那: "Que",
  里: "à l'intérieur",
  消: "retirer",
  时: "heure",
  辰: "Chen",
  早: "matin",
  看: "regarder",
  花: "fleur",
  果: "fruit",
  山: "Montagne",
  水: "eau",
  帘: "rideau",
  洞: "Trou",
  美: "beau",
  猴: "singe",
  王: "roi",
  快: "rapide",
  乐: "heureux",
  暗: "sombre",
  称: "dire",
  凡: "N'importe lequel",
  胎: "fœtal",
  重: "Lourd",
  轻: "lumière",
  体: "corps",
  亦: "ainsi que",
  举: "Ascenseur",
  世: "Monde",
  无: "aucun",
  人: "personnes",
  肯: "Ken",
  立: "rester",
  志: "Chronique",
  修: "construire",
  玄: "mystérieux",
  明: "brillant",
  当: "quand",
  过: "Passer",
  波: "Vague",
  难: "Catastrophe",
  进: "Entrer",
  今: "maintenant",
  日: "jour",
  甚: "très",
  易: "facile",
  语: "langue",
  叮: "mordre",
  咛: "Rappel",
  还: "retour",
  耳: "Oreille",
  期: "Attendre",
  顷: "沪",
  刻: "tailler",
  溟: "mer",
  按: "selon",
  下: "Vers le bas",
  头: "tête",
  直: "droit",
  至: "à",
  找: "chercher",
  路: "route",
  而: "et",
  走: "Marcher",
  忽: "soudainement",
  听: "écouter",
  鹤: "grue",
  唳: "Tranchée",
  猿: "singe",
  啼: "pleurer",
  声: "Voix",
  冲: "se précipiter",
  霄: "Ciel",
  汉: "Chinois",
  外: "dehors",
  悲: "triste",
  切: "couper",
  伤: "blesser",
  情: "Affection",
  开: "ouvrir",
  口: "bouche",
  叫: "Appel",
  孩: "enfant",
  儿: "Fils",
  们: "Nous",
  也: "aussi",
  崖: "Falaise",
  石: "pierre",
  坎: "Kan",
  边: "côté",
  草: "Herbe",
  中: "milieu",
  树: "Arbre",
  木: "Bois",
  若: "comme",
  大: "grand",
  小: "Petit",
  跳: "Saut",
  千: "mille",
  围: "Environnant",
  叩: "frappe",
  好: "bien",
  宽: "Largeur",
  心: "Cœur",
  久: "Long",
  俱: "tous",
  闪: "éclair",
  望: "voir",
  诚: "Sincère",
  如: "comme",
  饥: "affamé",
  渴: "soif",
  近: "fermer",
  被: "édredon",
  妖: "Démon",
  魔: "magie",
  此: "ce",
  欺: "intimidateur",
  虐: "Injurieux",
  强: "puissant",
  要: "vouloir",
  占: "occuper",
  府: "Maison",
  等: "attendez",
  舍: "Abandonner",
  死: "mourir",
  忘: "oublier",
  他: "il",
  争: "Combattre",
  些: "quelques",
  厮: "Ami",
  抢: "Voler",
  火: "feu",
  捉: "attraper",
  多: "beaucoup",
  子: "fils",
  侄: "neveu",
  昼: "jour",
  夜: "nuit",
  眠: "dormir",
  守: "Garde",
  业: "Industrie",
  幸: "heureux",
  再: "Encore",
  年: "Année",
  载: "charger",
  尽: "Tous",
  属: "Générique",
  矣: "C'est bon",
  闻: "odeur",
  怒: "colère",
  什: "Varié",
  辄: "Chaque",
  状: "forme",
  且: "et",
  细: "mince",
  待: "traiter",
  寻: "À la recherche de",
  报: "Rapport",
  仇: "haine",
  告: "dire",
  上: "supérieur",
  混: "mélanger",
  住: "en direct",
  居: "Résidence",
  北: "nord",
  间: "entre",
  到: "arriver",
  有: "avoir",
  少: "peu",
  程: "Procédure",
  雾: "brouillard",
  或: "ou",
  风: "vent",
  雨: "pluie",
  电: "électricité",
  雷: "tonnerre",
  既: "maintenant que",
  休: "arrêt",
  怕: "Effrayé",
  顽: "têtu",
  耍: "Jouer",
};

const tianwen_translation_map_en = {
  悟空见没奈何: "Wukong saw nothing to do",
  只得拜辞: "Have to say goodbye",
  与众相别: "Farewell to others",
  祖师道: "The Patriarch's Way",
  你这去: "You're going here",
  定生不良: "Bad birth",
  凭你怎么惹祸行凶: "How do you cause trouble",
  却不许说是我的徒弟: "But you are not allowed to say that it is my apprentice",
  你说出半个字来: "You say half a word",
  我就知之: "I'll know",
  把你这猢狲剥皮锉骨: "Skin your money and file your bones",
  将神魂贬在九幽之处: "Demote the soul to the place of the Nine Netherworlds",
  教你万劫不得翻身: "I'll never turn around",
  悟空道: "Wukong Tao",
  决不敢提起师父一字: "Never mention the word Master",
  只说是我自家会的便罢: "Just say it's my own",
  悟空谢了: "Wukong thanks",
  即抽身: "Immediately pull out",
  捻着诀: "Twisting tips",
  丢个连扯: "Throw a lot",
  纵起筋斗云: "Somersault clouds",
  径回东海: "Go back to the East China Sea",
  那里消一个时辰: "There is an hour to go away",
  早看见花果山水帘洞: "I saw Huaguo Mountain and Water Curtain Cave",
  美猴王自知快乐: "The Monkey King knows happiness",
  暗暗的自称道: "Said secretly",
  去时凡骨凡胎重: "When I left the mortal bones and fetal weight",
  得道身轻体亦轻: "The body is light and the body is light",
  举世无人肯立志: "No one in the world is willing to make a decision",
  立志修玄玄自明: "Aspire to cultivate the mystery and self-understanding",
  当时过海波难进: "It was difficult to get through the sea waves at that time",
  今日来回甚易行: "It's very easy to go back and forth today",
  别语叮咛还在耳: "No words of advice are still in my ears",
  何期顷刻见东溟: "How could I see Dongming in an instant",
  悟空按下云头: "Wukong presses the cloud head",
  直至花果山: "Until Huaguo Mountain",
  找路而走: "Find a way",
  忽听得鹤唳猿啼: "Suddenly I heard the cry of a crane and ape",
  鹤唳声冲霄汉外: "The sound of a crane soars into the sky",
  猿啼悲切甚伤情: "The ape cry is so sad and sad",
  即开口叫道: "He immediately opened his mouth and shouted",
  孩儿们: "Children",
  我来了也: "I'm here too",
  那崖下石坎边: "The cliff is surrounded by stone ridge",
  花草中: "Among the flowers and plants",
  树木里: "In the trees",
  若大若小之猴: "A monkey that is big or small",
  跳出千千万万: "Bounce out of thousands",
  把个美猴王围在当中: "Put a monkey king in it",
  叩头叫道: "Kowtow and shout",
  大王: "The King",
  你好宽心: "You're so relaxed",
  怎么一去许久: "How to go for a long time",
  把我们俱闪在这里: "Let us all go here",
  望你诚如饥渴: "I hope you are as hungry as",
  近来被一妖魔在此欺虐: "Recently, a demon bullied here",
  强要占我们水帘洞府: "We must occupy our water curtain cave",
  是我等舍死忘生: "I'm waiting to die",
  与他争斗: "Fight with him",
  这些时: "These",
  被那厮抢了我们家火: "That guy robbed our fire",
  捉了许多子侄: "Captured many nephews",
  教我们昼夜无眠: "Teach us to sleepless day and night",
  看守家业: "Keeping the family business",
  幸得大王来了: "Fortunately, the king is here",
  大王若再年载不来: "If the king is not able to come again",
  我等连山洞尽属他人矣: "All the caves in Lianshan belong to others",
  悟空闻说: "Wukong heard",
  心中大怒道: "He said in his heart",
  是什么妖魔: "What kind of demon is it",
  辄敢无状: "Dare to be incompetent",
  你且细细说来: "Let's talk about it in detail",
  待我寻他报仇: "Wait for me to seek revenge",
  众猴叩头: "Monkeys kowtow",
  告上大王: "Take the king",
  那厮自称混世魔王: "That guy called himself the devil king of the world",
  住居在直北下: "Living in Zhibeixia",
  悟空道: "Wukong Tao",
  此间到他那里: "Go to him here",
  有多少路程: "How many journeys are there",
  众猴道: "The monkeys",
  他来时云: "When he comes",
  去时雾: "Go to the fog",
  或风或雨: "Wind or rain",
  或电或雷: "Either lightning or lightning",
  我等不知有多少路: "I don't know how many roads there are",
  悟空道: "Wukong Tao",
  既如此: "That's true",
  你们休怕: "Don't be afraid",
  且自顽耍: "And play hard",
  等我寻他去来: "Wait for me to come and find him",
};

const tianwen_translation_map_de = {
  悟空见没奈何: "Wukong sah nichts zu tun",
  只得拜辞: "Sich verabschieden müssen",
  与众相别: "Abschied von anderen",
  祖师道: "Der Weg des Patriarchen",
  你这去: "Du gehst hierher",
  定生不良: "Schlechte Geburt",
  凭你怎么惹祸行凶: "Wie verursachen Sie Ärger?",
  却不许说是我的徒弟: "Aber Sie dürfen nicht sagen, dass es mein Lehrling ist",
  你说出半个字来: "Sie sagen ein halbes Wort",
  我就知之: "Ich werde es wissen",
  把你这猢狲剥皮锉骨: "Haut Ihr Geld häuten und Ihre Knochen einreichen",
  将神魂贬在九幽之处: "Degradieren die Seele an den Ort der neun Netherwelt",
  教你万劫不得翻身: "Ich werde mich nie umdrehen",
  悟空道: "Wukong Tao",
  决不敢提起师父一字: "Erwähnen Sie nie den Wort Master",
  只说是我自家会的便罢: "Sagen Sie einfach, es ist mein eigener",
  悟空谢了: "Wukong Danke",
  即抽身: "Sofort herausziehen",
  捻着诀: "Tipps verdrehen",
  丢个连扯: "Viel werfen",
  纵起筋斗云: "Somersault -Wolken",
  径回东海: "Geh zurück ins ostchinesische Meer",
  那里消一个时辰: "Es ist eine Stunde, um zu verschwinden",
  早看见花果山水帘洞: "Ich sah Huaguo -Berg- und Wasservorhanghöhle",
  美猴王自知快乐: "Der Affenkönig kennt das Glück",
  暗暗的自称道: "Sagte heimlich",
  去时凡骨凡胎重:
    "Als ich die sterblichen Knochen und das Fötusgewicht verließ",
  得道身轻体亦轻: "Der Körper ist leicht und der Körper ist leicht",
  举世无人肯立志:
    "Niemand auf der Welt ist bereit, eine Entscheidung zu treffen",
  立志修玄玄自明:
    "Streben danach, das Geheimnis und das Selbstverständnis zu kultivieren",
  当时过海波难进:
    "Es war schwierig, zu dieser Zeit durch die Meereswellen zu kommen",
  今日来回甚易行: "Es ist sehr einfach, heute hin und her zu gehen",
  别语叮咛还在耳: "Keine Ratschläge sind noch in meinen Ohren",
  何期顷刻见东溟: "Wie konnte ich in einem Augenblick Dongming sehen",
  悟空按下云头: "Wukong drückt den Wolkenkopf",
  直至花果山: "Bis Huaguo Berg",
  找路而走: "Einen Weg finden",
  忽听得鹤唳猿啼: "Plötzlich hörte ich den Schrei eines Kranes und Affen",
  鹤唳声冲霄汉外: "Das Geräusch eines Krans steigt in den Himmel",
  猿啼悲切甚伤情: "Der Affenschrei ist so traurig und traurig",
  即开口叫道: "Er öffnete sofort den Mund und schrie",
  孩儿们: "Kinder",
  我来了也: "Ich bin auch hier",
  那崖下石坎边: "Die Klippe ist von Stone Ridge umgeben",
  花草中: "Unter den Blumen und Pflanzen",
  树木里: "In den Bäumen",
  若大若小之猴: "Ein Affe, der groß oder klein ist",
  跳出千千万万: "Aus Tausenden abprallen",
  把个美猴王围在当中: "Setzen Sie einen Affenkönig hinein",
  叩头叫道: "Kowtow und schreien",
  大王: "Der König",
  你好宽心: "Du bist so entspannt",
  怎么一去许久: "Wie man lange geht",
  把我们俱闪在这里: "Lassen Sie uns alle hierher gehen",
  望你诚如饥渴: "Ich hoffe du bist so hungrig wie",
  近来被一妖魔在此欺虐: "Vor kurzem, hier ein Dämon gemobbt",
  强要占我们水帘洞府: "Wir müssen unsere Wasservorhanghöhle besetzen",
  是我等舍死忘生: "Ich warte darauf zu sterben",
  与他争斗: "Kämpfe mit ihm",
  这些时: "Diese",
  被那厮抢了我们家火: "Dieser Typ hat unser Feuer ausgeraubt",
  捉了许多子侄: "Erfasste viele Neffen",
  教我们昼夜无眠: "Lehre uns Tag und Nacht schlaflos",
  看守家业: "Das Familienunternehmen behalten",
  幸得大王来了: "Zum Glück ist der König hier",
  大王若再年载不来: "Wenn der König nicht wieder kommen kann",
  我等连山洞尽属他人矣: "Alle Höhlen in Lianshan gehören anderen an",
  悟空闻说: "Wukong hörte",
  心中大怒道: "Sagte er in seinem Herzen",
  是什么妖魔: "Was für ein Dämon ist es",
  辄敢无状: "Wagen es, inkompetent zu sein",
  你且细细说来: "Lassen Sie uns im Detail darüber sprechen",
  待我寻他报仇: "Warten Sie, bis ich Rache suche",
  众猴叩头: "Affen Kowtow",
  告上大王: "Nimm den König",
  那厮自称混世魔王: "Dieser Typ nannte sich den Teufelskönig der Welt",
  住居在直北下: "Leben in Zhibeixia",
  悟空道: "Wukong Tao",
  此间到他那里: "Geh hier zu ihm",
  有多少路程: "Wie viele Reisen gibt es",
  众猴道: "Die Affen",
  他来时云: "Wenn er kommt",
  去时雾: "In den Nebel gehen",
  或风或雨: "Wind oder Regen",
  或电或雷: "Entweder Blitz oder Blitz",
  我等不知有多少路: "Ich weiß nicht, wie viele Straßen es gibt",
  悟空道: "Wukong Tao",
  既如此: "Das stimmt",
  你们休怕: "Hab keine Angst",
  且自顽耍: "Und hart spielen",
  等我寻他去来: "Warten Sie, bis ich ihn findet und ihn finde",
};

const tianwen_translation_map_fr = {
  悟空见没奈何: "Wukong n'a rien vu à faire",
  只得拜辞: "Doivent dire au revoir",
  与众相别: "Adieu aux autres",
  祖师道: "La voie du patriarche",
  你这去: "Tu vas ici",
  定生不良: "Mauvaise naissance",
  凭你怎么惹祸行凶: "Comment causez-vous des problèmes",
  却不许说是我的徒弟: "Mais tu n'es pas autorisé à dire que c'est mon apprenti",
  你说出半个字来: "Tu dis à un demi-mot",
  我就知之: "Je saurai",
  把你这猢狲剥皮锉骨: "Écorchez votre argent et déposez vos os",
  将神魂贬在九幽之处: "Démarre l'âme à la place des neuf Netherworlds",
  教你万劫不得翻身: "Je ne me retournerai jamais",
  悟空道: "Wukong Tao",
  决不敢提起师父一字: "Ne mentionnez jamais le mot maître",
  只说是我自家会的便罢: "Dis juste que c'est le mien",
  悟空谢了: "Wukong merci",
  即抽身: "Tirez immédiatement",
  捻着诀: "Conseils de torsion",
  丢个连扯: "Jeter beaucoup",
  纵起筋斗云: "Nuages ​​de somersault",
  径回东海: "Retournez en mer de Chine orientale",
  那里消一个时辰: "Il y a une heure pour partir",
  早看见花果山水帘洞: "J'ai vu Huaguo Mountain and Water Curtain Cave",
  美猴王自知快乐: "Le roi de singe connaît le bonheur",
  暗暗的自称道: "Dit secrètement",
  去时凡骨凡胎重: "Quand j'ai laissé les os mortels et le poids fœtal",
  得道身轻体亦轻: "Le corps est léger et le corps est léger",
  举世无人肯立志: "Personne au monde n'est prêt à prendre une décision",
  立志修玄玄自明: "Aspirer à cultiver le mystère et la compréhension de soi",
  当时过海波难进:
    "C'était difficile de traverser les vagues de mer à ce moment-là",
  今日来回甚易行: "Il est très facile de faire des allers-retours aujourd'hui",
  别语叮咛还在耳: "Aucun conseil n'est encore dans mes oreilles",
  何期顷刻见东溟: "Comment pourrais-je voir le dongming en un instant",
  悟空按下云头: "Wukong appuie sur la tête du nuage",
  直至花果山: "Jusqu'à la montagne Huaguo",
  找路而走: "Trouver un moyen",
  忽听得鹤唳猿啼: "Soudain, j'ai entendu le cri d'une grue et d'un singe",
  鹤唳声冲霄汉外: "Le son d'une grue monte dans le ciel",
  猿啼悲切甚伤情: "Le cri de singe est si triste et triste",
  即开口叫道: "Il a immédiatement ouvert la bouche et a crié",
  孩儿们: "Enfants",
  我来了也: "Je suis là aussi",
  那崖下石坎边: "La falaise est entourée de Stone Ridge",
  花草中: "Parmi les fleurs et les plantes",
  树木里: "Dans les arbres",
  若大若小之猴: "Un singe grand ou petit",
  跳出千千万万: "Rebond sur des milliers",
  把个美猴王围在当中: "Mettez un roi de singe dedans",
  叩头叫道: "Kowtow et crie",
  大王: "Le roi",
  你好宽心: "Tu es tellement détendu",
  怎么一去许久: "Comment aller longtemps",
  把我们俱闪在这里: "Laissez-nous tous aller ici",
  望你诚如饥渴: "J'espère que vous avez aussi faim que",
  近来被一妖魔在此欺虐: "Récemment, un démon intimidé ici",
  强要占我们水帘洞府: "Nous devons occuper notre grotte de rideau d'eau",
  是我等舍死忘生: "J'attends de mourir",
  与他争斗: "Se battre avec lui",
  这些时: "Ces",
  被那厮抢了我们家火: "Ce gars a volé notre feu",
  捉了许多子侄: "Capturé de nombreux neveux",
  教我们昼夜无眠: "Apprenez-nous à faire du sommeil jour et nuit",
  看守家业: "Garder l'entreprise familiale",
  幸得大王来了: "Heureusement, le roi est là",
  大王若再年载不来: "Si le roi n'est pas en mesure de revenir",
  我等连山洞尽属他人矣:
    "Toutes les grottes de Lianshan appartiennent à d'autres",
  悟空闻说: "Wukong entendu",
  心中大怒道: "Il a dit dans son cœur",
  是什么妖魔: "Quel genre de démon est-il",
  辄敢无状: "Oser être incompétent",
  你且细细说来: "Parlons-en en détail",
  待我寻他报仇: "Attendez que je cherche à me venger",
  众猴叩头: "Singes",
  告上大王: "Prendre le roi",
  那厮自称混世魔王: "Ce gars s'appelait le diable roi du monde",
  住居在直北下: "Vivre à Zhibeixia",
  悟空道: "Wukong Tao",
  此间到他那里: "Aller vers lui ici",
  有多少路程: "Combien de voyages y a-t-il",
  众猴道: "Les singes",
  他来时云: "Quand il vient",
  去时雾: "Aller au brouillard",
  或风或雨: "Vent ou pluie",
  或电或雷: "Soit la foudre ou la foudre",
  我等不知有多少路: "Je ne sais pas combien de routes il y a",
  悟空道: "Wukong Tao",
  既如此: "C'est vrai",
  你们休怕: "N'ayez pas peur",
  且自顽耍: "Et jouer dur",
  等我寻他去来: "Attendez que je vienne le trouver",
};



const synth = window.speechSynthesis;
let utterance = null;

// 状态跟踪
const charStates = {};

// 页面加载完成后初始化
document.addEventListener("DOMContentLoaded", function () {
  renderPoem();
});

// 渲染诗歌
function renderPoem() {
  const poemContainer = document.getElementById("poemContainer");
  const lines = poemText.split("\n");

  lines.forEach((line) => {
    const lineDiv = document.createElement("div");
    lineDiv.className = "poem-line";

    // 处理每个字符
    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      // 跳过空格
      if (char.trim() === "") {
        const spaceSpan = document.createElement("span");
        spaceSpan.textContent = " ";
        lineDiv.appendChild(spaceSpan);
        continue;
      }

      // 创建字符容器
      const charContainer = document.createElement("div");
      charContainer.className = "char-container";

      // 创建字符显示
      const charSpan = document.createElement("span");
      charSpan.className = "char";
      charSpan.textContent = char;

      // 创建拼音显示
      const pinyinSpan = document.createElement("span");
      pinyinSpan.className = "pinyin";

      // 创建翻译显示
      const transSpan = document.createElement("span");
      transSpan.className = "translation";

      // 添加到容器
      charContainer.appendChild(pinyinSpan);
      charContainer.appendChild(charSpan);
      charContainer.appendChild(transSpan);

      // 添加点击事件
      charContainer.addEventListener("click", () =>
        handleCharClick(char, pinyinSpan, transSpan)
      );

      // 添加到行
      lineDiv.appendChild(charContainer);
    }

    // 添加行控制按钮
    const controlsDiv = document.createElement("div");
    controlsDiv.className = "line-controls";

    const readBtn = document.createElement("button");
    readBtn.textContent = "朗读";
    readBtn.addEventListener("click", () => readLine(line));

    const transBtn = document.createElement("button");
    transBtn.textContent = "翻译";
    transBtn.addEventListener("click", () => showLineTranslation(line));

    controlsDiv.appendChild(readBtn);
    controlsDiv.appendChild(transBtn);
    lineDiv.appendChild(controlsDiv);

    // 添加到容器
    poemContainer.appendChild(lineDiv);
  });
}

// 处理字符点击
function handleCharClick(char, pinyinSpan, transSpan) {
  const charId = `${char}-${pinyinSpan.id}`; // 创建唯一标识

  // 初始化状态
  if (!charStates[charId]) {
    charStates[charId] = 0;
  }

  // 更新状态
  charStates[charId]++;
  if (charStates[charId] > 3) {
    charStates[charId] = 1;
  }

  // 根据状态执行操作
  switch (charStates[charId]) {
    case 1: // 朗读字符
      readChar(char);
      updateStatus(`朗读字符: ${char}`);
      break;
    case 2: // 显示拼音
      showPinyin(char, pinyinSpan);
      updateStatus(`显示拼音: ${char}`);
      break;
    case 3: // 显示翻译
      showTranslation(char, transSpan);
      updateStatus(`显示翻译: ${char}`);
      break;
  }
}

// 显示拼音
function showPinyin(char, pinyinSpan) {
  // 这里应该调用拼音库，简化处理

  const py = pinyinMap[char] || "?";
  pinyinSpan.textContent = py;
  pinyinSpan.style.display = "block";

  // 3秒后自动隐藏
  setTimeout(() => {
    pinyinSpan.style.display = "none";
    // 重置状态以便下次点击
    const charId = `${char}-${pinyinSpan.id}`;
    charStates[charId] = 0;
  }, 8000);
}

// 朗读字符
function readChar(char) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(char);
  utterance.lang = "zh-CN";
  utterance.rate = 0.7; // 设置为正常速度的70%
  synth.speak(utterance);
}

// 显示翻译
function showTranslation(char, transSpan) {
  const lang = document.getElementById("languageSelect").value;

  const translationCard = document.getElementById("translationCard");

  const translateMap = {
    de: translations_de[char] || "Keine Übersetzung",
    fr: translations_fr[char] || "Pas de traduction",
    en: translations_en[char] || "No translation",
  };
  const translate = translateMap[lang];
  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">汉字：</div>
    <div class="info-content">${char}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translate}</div>
  </div>
`;

  translationCard.style.display = "block";

  const charId = `${char}-${transSpan.id}`;
  charStates[charId] = 0;
}

function closeTranslationCard() {
  const translationCard = document.getElementById("translationCard");
  translationCard.style.display = "none";
}

// 朗读整行
function readLine(line) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(line);
  utterance.lang = "zh-CN";
  utterance.rate = 0.6; // 设置为正常速度的60%，更慢一些
  synth.speak(utterance);

  updateStatus(`朗读: ${line}`);
}

function showLineTranslation(line) {
  const lang = document.getElementById("languageSelect").value;
  const translatedMap = {
    de: tianwen_translation_map_de,
    fr: tianwen_translation_map_fr,
    en: tianwen_translation_map_en,
  };
  const translatedLine =
    translatedMap[lang]?.[line] || "（keine Übersetzung gefunden）";
  const translationCard = document.getElementById("translationCard");

  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">原文：</div>
    <div class="info-content">${line}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translatedLine}</div>
  </div>
`;

  translationCard.style.display = "block";

  updateStatus(`显示翻译: ${line.substring(0, 15)}...`);
}

// 更新状态栏
function updateStatus(message) {
  document.getElementById("statusBar").textContent = message;
}
