const translationCard = document.getElementById("translationCard");
// 诗歌文本c
const poemText = `风起处
惊散了那傲来国君王
三街六市
都慌得关门闭户
无人敢走
悟空才按下云头
径闯入朝门里
直寻到兵器馆武库中
打开门扇
看时
那里面无数器械
刀枪剑戟斧钺毛镰鞭钯挝简弓弩叉矛
件件俱备
一见甚喜道
我一人能拿几何
还使个分身法搬将去罢
好猴王
即拔一把毫毛
入口嚼烂
喷将出去
念动咒语
叫声
变
变做千百个小猴
都乱搬乱抢
有力的拿五七件
力小的拿三二件
尽数搬个罄净
径踏云头
弄个摄法
唤转狂风
带领小猴
俱回本处
却说那花果山大小猴儿
正在那洞门外顽耍
忽听得风声响处
见半空中
丫丫叉叉
无边无岸的猴精
唬得都乱跑乱躲
少时
美猴王按落云头
收了云雾
将身一抖
收了毫毛
将兵器乱堆在山前
叫道
小的们
都来领兵器
众猴看时
只见悟空独立在平阳之地
俱跑来叩头问故
悟空将前使狂风
搬兵器
一应事说了一遍
众猴称谢毕
都去抢刀夺剑
挝斧争枪
扯弓扳弩
吆吆喝喝
耍了一日
次日
依旧排营
悟空会聚群猴
计有四万七千余口
早惊动满山怪兽
都是些狼虫虎豹麂獐狐理獾貉狮象狻猊猩猩熊鹿野豕山牛羚羊青兕狡儿神獒
各样妖王
共有七十二洞
都来参拜猴王为尊
每年献贡
四时点卯
也有随班操演的
也有随节征粮的
齐齐整整
把一座花果山造得似铁桶金城
各路妖王
又有进金鼓
进彩旗
进盔甲的
纷纷攘攘
日逐家习舞兴师`;

const pinyinMap = {
  风: "fēng",
  起: "qǐ",
  处: "chù",
  惊: "jīng",
  散: "sàn",
  了: "le",
  那: "nà",
  傲: "ào",
  来: "lái",
  国: "guó",
  君: "jūn",
  王: "wáng",
  三: "sān",
  街: "jiē",
  六: "liù",
  市: "shì",
  都: "dōu",
  慌: "huāng",
  得: "dé",
  关: "guān",
  门: "mén",
  闭: "bì",
  户: "hù",
  无: "wú",
  人: "rén",
  敢: "gǎn",
  走: "zǒu",
  悟: "wù",
  空: "kōng",
  才: "cái",
  按: "àn",
  下: "xià",
  云: "yún",
  头: "tóu",
  径: "jìng",
  闯: "chuǎng",
  入: "rù",
  朝: "cháo",
  里: "lǐ",
  直: "zhí",
  寻: "xún",
  到: "dào",
  兵: "bīng",
  器: "qì",
  馆: "guǎn",
  武: "wǔ",
  库: "kù",
  中: "zhōng",
  打: "dǎ",
  开: "kāi",
  扇: "shàn",
  看: "kàn",
  时: "shí",
  面: "miàn",
  数: "shù",
  械: "xiè",
  刀: "dāo",
  枪: "qiāng",
  剑: "jiàn",
  戟: "jǐ",
  斧: "fǔ",
  钺: "yuè",
  毛: "máo",
  镰: "lián",
  鞭: "biān",
  钯: "bǎ",
  挝: "wō",
  简: "jiǎn",
  弓: "gōng",
  弩: "nǔ",
  叉: "chā",
  矛: "máo",
  件: "jiàn",
  俱: "jù",
  备: "bèi",
  一: "yī",
  见: "jiàn",
  甚: "shèn",
  喜: "xǐ",
  道: "dào",
  我: "wǒ",
  能: "néng",
  拿: "ná",
  几: "jǐ",
  何: "hé",
  还: "hái",
  使: "shǐ",
  个: "gè",
  分: "fēn",
  身: "shēn",
  法: "fǎ",
  搬: "bān",
  将: "jiāng",
  去: "qù",
  罢: "bà",
  好: "hǎo",
  猴: "hóu",
  即: "jí",
  拔: "bá",
  把: "bǎ",
  毫: "háo",
  口: "kǒu",
  嚼: "jué",
  烂: "làn",
  喷: "pēn",
  出: "chū",
  念: "niàn",
  动: "dòng",
  咒: "zhòu",
  语: "yǔ",
  叫: "jiào",
  声: "shēng",
  变: "biàn",
  做: "zuò",
  千: "qiān",
  百: "bǎi",
  小: "xiǎo",
  乱: "luàn",
  抢: "qiǎng",
  有: "yǒu",
  力: "lì",
  的: "de",
  五: "wǔ",
  七: "qī",
  二: "èr",
  尽: "jǐn",
  罄: "qìng",
  净: "jìng",
  踏: "tà",
  弄: "nòng",
  摄: "shè",
  唤: "huàn",
  转: "zhuǎn",
  狂: "kuáng",
  带: "dài",
  领: "lǐng",
  回: "huí",
  本: "běn",
  却: "què",
  说: "shuō",
  花: "huā",
  果: "guǒ",
  山: "shān",
  大: "dà",
  儿: "ér",
  正: "zhèng",
  在: "zài",
  洞: "dòng",
  外: "wài",
  顽: "wán",
  耍: "shuǎ",
  忽: "hū",
  听: "tīng",
  响: "xiǎng",
  半: "bàn",
  丫: "yā",
  边: "biān",
  岸: "àn",
  精: "jīng",
  唬: "hǔ",
  跑: "pǎo",
  躲: "duǒ",
  少: "shǎo",
  美: "měi",
  落: "luò",
  收: "shōu",
  雾: "wù",
  抖: "dǒu",
  堆: "duī",
  前: "qián",
  们: "men",
  众: "zhòng",
  只: "zhǐ",
  独: "dú",
  立: "lì",
  平: "píng",
  阳: "yáng",
  之: "zhī",
  地: "dì",
  叩: "kòu",
  问: "wèn",
  故: "gù",
  应: "yīng",
  事: "shì",
  遍: "biàn",
  称: "chēng",
  谢: "xiè",
  毕: "bì",
  夺: "duó",
  争: "zhēng",
  扯: "chě",
  扳: "bān",
  吆: "yāo",
  喝: "hē",
  日: "rì",
  次: "cì",
  依: "yī",
  旧: "jiù",
  排: "pái",
  营: "yíng",
  会: "huì",
  聚: "jù",
  群: "qún",
  计: "jì",
  四: "sì",
  万: "wàn",
  余: "yú",
  早: "zǎo",
  满: "mǎn",
  怪: "guài",
  兽: "shòu",
  是: "shì",
  些: "xiē",
  狼: "láng",
  虫: "chóng",
  虎: "hǔ",
  豹: "bào",
  麂: "jǐ",
  獐: "zhāng",
  狐: "hú",
  理: "lǐ",
  獾: "huān",
  貉: "háo",
  狮: "shī",
  象: "xiàng",
  狻: "suān",
  猊: "ní",
  猩: "xīng",
  熊: "xióng",
  鹿: "lù",
  野: "yě",
  豕: "shǐ",
  牛: "niú",
  羚: "líng",
  羊: "yáng",
  青: "qīng",
  兕: "sì",
  狡: "jiǎo",
  神: "shén",
  獒: "áo",
  各: "gè",
  样: "yàng",
  妖: "yāo",
  共: "gòng",
  十: "shí",
  参: "cān",
  拜: "bài",
  为: "wèi",
  尊: "zūn",
  每: "měi",
  年: "nián",
  献: "xiàn",
  贡: "gòng",
  点: "diǎn",
  卯: "mǎo",
  也: "yě",
  随: "suí",
  班: "bān",
  操: "cāo",
  演: "yǎn",
  节: "jié",
  征: "zhēng",
  粮: "liáng",
  齐: "qí",
  整: "zhěng",
  座: "zuò",
  造: "zào",
  似: "shì",
  铁: "tiě",
  桶: "tǒng",
  金: "jīn",
  城: "chéng",
  路: "lù",
  又: "yòu",
  进: "jìn",
  鼓: "gǔ",
  彩: "cǎi",
  旗: "qí",
  盔: "kuī",
  甲: "jiǎ",
  纷: "fēn",
  攘: "rǎng",
  逐: "zhú",
  家: "jiā",
  习: "xí",
  舞: "wǔ",
  兴: "xīng",
  师: "shī",
};

const translations_en = {
  风: "wind",
  起: "rise",
  处: "Where",
  惊: "shock",
  散: "Scattered",
  了: "It's",
  那: "That",
  傲: "proud",
  来: "Come",
  国: "country",
  君: "Jun",
  王: "king",
  三: "three",
  街: "street",
  六: "six",
  市: "city",
  都: "All",
  慌: "Panic",
  得: "have to",
  关: "close",
  门: "Door",
  闭: "close",
  户: "household",
  无: "none",
  人: "people",
  敢: "dare",
  走: "Walk",
  悟: "Enlightenment",
  空: "null",
  才: "talent",
  按: "according to",
  下: "Down",
  云: "cloud",
  头: "head",
  径: "path",
  闯: "Break",
  入: "enter",
  朝: "towards",
  里: "inside",
  直: "straight",
  寻: "Looking for",
  到: "arrive",
  兵: "Soldier",
  器: "Device",
  馆: "Pavilion",
  武: "Wu",
  库: "Library",
  中: "middle",
  打: "beat",
  开: "open",
  扇: "fan",
  看: "look",
  时: "hour",
  面: "noodle",
  数: "number",
  械: "Machinery",
  刀: "knife",
  枪: "gun",
  剑: "sword",
  戟: "halberd",
  斧: "ax",
  钺: "ax",
  毛: "hair",
  镰: "sickle",
  鞭: "whip",
  钯: "palladium",
  挝: "Os",
  简: "simple",
  弓: "bow",
  弩: "crossbow",
  叉: "fork",
  矛: "spear",
  件: "Parts",
  俱: "all",
  备: "Prepare",
  一: "one",
  见: "See",
  甚: "very",
  喜: "happiness",
  道: "road",
  我: "I",
  能: "able",
  拿: "take",
  几: "Several",
  何: "what",
  还: "return",
  使: "make",
  个: "indivual",
  分: "point",
  身: "body",
  法: "Law",
  搬: "move",
  将: "Will",
  去: "go",
  罢: "stop",
  好: "good",
  猴: "monkey",
  即: "Right now",
  拔: "pull",
  把: "Bundle",
  毫: "海海",
  口: "mouth",
  嚼: "chew",
  烂: "rotten",
  喷: "spray",
  出: "out",
  念: "read",
  动: "move",
  咒: "curse",
  语: "language",
  叫: "Call",
  声: "Voice",
  变: "Change",
  做: "Do",
  千: "thousand",
  百: "Hundred",
  小: "Small",
  乱: "chaos",
  抢: "Rob",
  有: "have",
  力: "force",
  的: "of",
  五: "five",
  七: "seven",
  二: "two",
  尽: "All",
  罄: "exhausted",
  净: "net",
  踏: "tread",
  弄: "alley",
  摄: "Photo",
  唤: "Call",
  转: "change",
  狂: "mad",
  带: "bring",
  领: "collar",
  回: "Back",
  本: "Book",
  却: "but",
  说: "explain",
  花: "flower",
  果: "fruit",
  山: "Mountain",
  大: "big",
  儿: "Son",
  正: "just",
  在: "exist",
  洞: "Hole",
  外: "outside",
  顽: "stubborn",
  耍: "Play",
  忽: "suddenly",
  听: "listen",
  响: "ring",
  半: "Half",
  丫: "Ya",
  边: "side",
  岸: "shore",
  精: "Refined",
  唬: "fool",
  跑: "run",
  躲: "hide",
  少: "few",
  美: "beautiful",
  落: "fall",
  收: "receive",
  雾: "fog",
  抖: "shake",
  堆: "heap",
  前: "forward",
  们: "We",
  众: "All",
  只: "Only",
  独: "alone",
  立: "stand",
  平: "flat",
  阳: "Positive",
  之: "Of",
  地: "land",
  叩: "knock",
  问: "ask",
  故: "Therefore",
  应: "answer",
  事: "thing",
  遍: "all over",
  称: "say",
  谢: "Thanks",
  毕: "complete",
  夺: "Take it",
  争: "Contend",
  扯: "pull",
  扳: "pull",
  吆: "Ying",
  喝: "drink",
  日: "day",
  次: "Second-rate",
  依: "according to",
  旧: "old",
  排: "Row",
  营: "camp",
  会: "meeting",
  聚: "Gather",
  群: "group",
  计: "count",
  四: "Four",
  万: "Ten thousand",
  余: "Remain",
  早: "morning",
  满: "Full",
  怪: "Strange",
  兽: "beast",
  是: "yes",
  些: "some",
  狼: "Wolf",
  虫: "insect",
  虎: "Tiger",
  豹: "Leopard",
  麂: "muntjac",
  獐: "roe",
  狐: "fox",
  理: "reason",
  獾: "badger",
  貉: "Raccoon",
  狮: "lion",
  象: "elephant",
  狻: "小",
  猊: "lion",
  猩: "ape",
  熊: "Bear",
  鹿: "deer",
  野: "wild",
  豕: "hog",
  牛: "ox",
  羚: "antelope",
  羊: "sheep",
  青: "green",
  兕: "可",
  狡: "cunning",
  神: "god",
  獒: "mastiff",
  各: "each",
  样: "Sample",
  妖: "Demon",
  共: "common",
  十: "ten",
  参: "Ginseng",
  拜: "bye",
  为: "for",
  尊: "Honor",
  每: "Every",
  年: "Year",
  献: "offer",
  贡: "tribute",
  点: "point",
  卯: "南",
  也: "also",
  随: "With",
  班: "class",
  操: "Hold",
  演: "play",
  节: "Festival",
  征: "Confirmation",
  粮: "grain",
  齐: "together",
  整: "all",
  座: "seat",
  造: "make",
  似: "like",
  铁: "iron",
  桶: "bucket",
  金: "gold",
  城: "city",
  路: "road",
  又: "again",
  进: "Enter",
  鼓: "drum",
  彩: "color",
  旗: "flag",
  盔: "helmet",
  甲: "First",
  纷: "Fresh",
  攘: "throw into confusion",
  逐: "By",
  家: "Home",
  习: "habit",
  舞: "dance",
  兴: "prosper",
  师: "division",
};

const translations_de = {
  风: "Wind",
  起: "erheben",
  处: "Wo",
  惊: "Schock",
  散: "Verstreut",
  了: "Es ist",
  那: "Das",
  傲: "stolz",
  来: "Kommen",
  国: "Land",
  君: "Jun",
  王: "König",
  三: "drei",
  街: "Straße",
  六: "sechs",
  市: "Stadt",
  都: "Alle",
  慌: "Panik",
  得: "müssen",
  关: "schließen",
  门: "Tür",
  闭: "schließen",
  户: "Haushalt",
  无: "keiner",
  人: "Menschen",
  敢: "wagen",
  走: "Gehen",
  悟: "Aufklärung",
  空: "NULL",
  才: "Talent",
  按: "entsprechend",
  下: "Runter",
  云: "Wolke",
  头: "Kopf",
  径: "Weg",
  闯: "Brechen",
  入: "eingeben",
  朝: "in Richtung",
  里: "innen",
  直: "gerade",
  寻: "Auf der Suche nach",
  到: "ankommen",
  兵: "Soldat",
  器: "Gerät",
  馆: "Pavillon",
  武: "Wu",
  库: "Bibliothek",
  中: "Mitte",
  打: "schlagen",
  开: "offen",
  扇: "Lüfter",
  看: "sehen",
  时: "Stunde",
  面: "Nudel",
  数: "Nummer",
  械: "Maschinen",
  刀: "Messer",
  枪: "Pistole",
  剑: "Schwert",
  戟: "Hellebarde",
  斧: "Axt",
  钺: "Axt",
  毛: "Haar",
  镰: "Sichel",
  鞭: "Peitsche",
  钯: "Palladium",
  挝: "Betriebssystem",
  简: "einfach",
  弓: "Bogen",
  弩: "Armbrust",
  叉: "Gabel",
  矛: "Speer",
  件: "Teile",
  俱: "alle",
  备: "Vorbereiten",
  一: "eins",
  见: "Sehen",
  甚: "sehr",
  喜: "Glück",
  道: "Straße",
  我: "ICH",
  能: "fähig",
  拿: "nehmen",
  几: "Mehrere",
  何: "Was",
  还: "zurückkehren",
  使: "machen",
  个: "indival",
  分: "Punkt",
  身: "Körper",
  法: "Gesetz",
  搬: "bewegen",
  将: "Wille",
  去: "gehen",
  罢: "stoppen",
  好: "Gut",
  猴: "Affe",
  即: "Im Augenblick",
  拔: "ziehen",
  把: "Bündeln",
  毫: "海海",
  口: "Mund",
  嚼: "kauen",
  烂: "faul",
  喷: "Spray",
  出: "aus",
  念: "lesen",
  动: "bewegen",
  咒: "Fluch",
  语: "Sprache",
  叫: "Anruf",
  声: "Stimme",
  变: "Ändern",
  做: "Tun",
  千: "tausend",
  百: "Hundert",
  小: "Klein",
  乱: "Chaos",
  抢: "Rauben",
  有: "haben",
  力: "Gewalt",
  的: "von",
  五: "fünf",
  七: "Sieben",
  二: "zwei",
  尽: "Alle",
  罄: "erschöpft",
  净: "netto",
  踏: "treten",
  弄: "Gasse",
  摄: "Foto",
  唤: "Anruf",
  转: "ändern",
  狂: "verrückt",
  带: "bringen",
  领: "Kragen",
  回: "Zurück",
  本: "Buch",
  却: "Aber",
  说: "erklären",
  花: "Blume",
  果: "Obst",
  山: "Berg",
  大: "groß",
  儿: "Sohn",
  正: "Nur",
  在: "existieren",
  洞: "Loch",
  外: "draußen",
  顽: "hartnäckig",
  耍: "Spielen",
  忽: "plötzlich",
  听: "Hören",
  响: "Ring",
  半: "Hälfte",
  丫: "Ya",
  边: "Seite",
  岸: "Ufer",
  精: "Raffiniert",
  唬: "Narr",
  跑: "laufen",
  躲: "verstecken",
  少: "wenige",
  美: "Schön",
  落: "fallen",
  收: "erhalten",
  雾: "Nebel",
  抖: "Shake",
  堆: "Haufen",
  前: "nach vorne",
  们: "Wir",
  众: "Alle",
  只: "Nur",
  独: "allein",
  立: "Stand",
  平: "Wohnung",
  阳: "Positiv",
  之: "Von",
  地: "Land",
  叩: "klopfen",
  问: "fragen",
  故: "daher",
  应: "Antwort",
  事: "Ding",
  遍: "Überall",
  称: "sagen",
  谢: "Danke",
  毕: "vollständig",
  夺: "Nimm es",
  争: "Kämpfen",
  扯: "ziehen",
  扳: "ziehen",
  吆: "Ying",
  喝: "trinken",
  日: "Tag",
  次: "Zweitklassifiziert",
  依: "entsprechend",
  旧: "alt",
  排: "Reihe",
  营: "Lager",
  会: "treffen",
  聚: "Versammeln",
  群: "Gruppe",
  计: "zählen",
  四: "Vier",
  万: "Zehntausend",
  余: "Bleiben",
  早: "Morgen",
  满: "Voll",
  怪: "Seltsam",
  兽: "Tier",
  是: "Ja",
  些: "manche",
  狼: "Wolf",
  虫: "Insekt",
  虎: "Tiger",
  豹: "Leopard",
  麂: "Muntjac",
  獐: "Rogen",
  狐: "Fuchs",
  理: "Grund",
  獾: "Dachs",
  貉: "Waschbär",
  狮: "Löwe",
  象: "Elefant",
  狻: "小",
  猊: "Löwe",
  猩: "Affe",
  熊: "Tragen",
  鹿: "Reh",
  野: "wild",
  豕: "Schwein",
  牛: "Ochse",
  羚: "Antilope",
  羊: "Schaf",
  青: "Grün",
  兕: "可",
  狡: "listig",
  神: "Gott",
  獒: "Dogge",
  各: "jede",
  样: "Probe",
  妖: "Dämon",
  共: "gemeinsam",
  十: "zehn",
  参: "Ginseng",
  拜: "Tschüss",
  为: "für",
  尊: "Ehre",
  每: "Jeder",
  年: "Jahr",
  献: "Angebot",
  贡: "Tribut",
  点: "Punkt",
  卯: "南",
  也: "Auch",
  随: "Mit",
  班: "Klasse",
  操: "Halten",
  演: "spielen",
  节: "Festival",
  征: "Bestätigung",
  粮: "Getreide",
  齐: "zusammen",
  整: "alle",
  座: "Sitz",
  造: "machen",
  似: "wie",
  铁: "Eisen",
  桶: "Eimer",
  金: "Gold",
  城: "Stadt",
  路: "Straße",
  又: "wieder",
  进: "Eingeben",
  鼓: "Trommel",
  彩: "Farbe",
  旗: "Flagge",
  盔: "Helm",
  甲: "Erste",
  纷: "Viele",
  攘: "Verwirrung in Verwirrung werfen",
  逐: "Von",
  家: "Heim",
  习: "Gewohnheit",
  舞: "tanzen",
  兴: "gedeihen",
  师: "Division",
};

const translations_fr = {
  风: "vent",
  起: "augmenter",
  处: "Où",
  惊: "choc",
  散: "Dispersé",
  了: "C'est",
  那: "Que",
  傲: "fier",
  来: "Viens",
  国: "pays",
  君: "Juin",
  王: "roi",
  三: "trois",
  街: "rue",
  六: "six",
  市: "ville",
  都: "Tous",
  慌: "Panique",
  得: "devoir",
  关: "fermer",
  门: "Porte",
  闭: "fermer",
  户: "ménage",
  无: "aucun",
  人: "personnes",
  敢: "oser",
  走: "Marcher",
  悟: "Éclaircissement",
  空: "nul",
  才: "talent",
  按: "selon",
  下: "Vers le bas",
  云: "nuage",
  头: "tête",
  径: "chemin",
  闯: "Casser",
  入: "entrer",
  朝: "vers",
  里: "à l'intérieur",
  直: "droit",
  寻: "À la recherche de",
  到: "arriver",
  兵: "Soldat",
  器: "Appareil",
  馆: "Pavillon",
  武: "Wu",
  库: "Bibliothèque",
  中: "milieu",
  打: "battre",
  开: "ouvrir",
  扇: "ventilateur",
  看: "regarder",
  时: "heure",
  面: "nouille",
  数: "nombre",
  械: "Machinerie",
  刀: "couteau",
  枪: "pistolet",
  剑: "épée",
  戟: "hallebarde",
  斧: "hache",
  钺: "hache",
  毛: "cheveux",
  镰: "faucille",
  鞭: "fouet",
  钯: "palladium",
  挝: "OS",
  简: "simple",
  弓: "arc",
  弩: "arbalète",
  叉: "fourchette",
  矛: "lance",
  件: "Parties",
  俱: "tous",
  备: "Préparer",
  一: "un",
  见: "Voir",
  甚: "très",
  喜: "bonheur",
  道: "route",
  我: "je",
  能: "capable",
  拿: "prendre",
  几: "Plusieurs",
  何: "quoi",
  还: "retour",
  使: "faire",
  个: "autonome",
  分: "indiquer",
  身: "corps",
  法: "Loi",
  搬: "se déplacer",
  将: "Volonté",
  去: "aller",
  罢: "arrêt",
  好: "bien",
  猴: "singe",
  即: "Tout de suite",
  拔: "tirer",
  把: "Paquet",
  毫: "海海",
  口: "bouche",
  嚼: "mâcher",
  烂: "pourri",
  喷: "pulvérisation",
  出: "dehors",
  念: "lire",
  动: "se déplacer",
  咒: "malédiction",
  语: "langue",
  叫: "Appel",
  声: "Voix",
  变: "Changement",
  做: "Faire",
  千: "mille",
  百: "Cent",
  小: "Petit",
  乱: "chaos",
  抢: "Voler",
  有: "avoir",
  力: "forcer",
  的: "de",
  五: "cinq",
  七: "Sept",
  二: "deux",
  尽: "Tous",
  罄: "épuisé",
  净: "filet",
  踏: "bande de roulement",
  弄: "ruelle",
  摄: "Photo",
  唤: "Appel",
  转: "changement",
  狂: "fou",
  带: "apporter",
  领: "collier",
  回: "Dos",
  本: "Livre",
  却: "mais",
  说: "expliquer",
  花: "fleur",
  果: "fruit",
  山: "Montagne",
  大: "grand",
  儿: "Fils",
  正: "juste",
  在: "exister",
  洞: "Trou",
  外: "dehors",
  顽: "têtu",
  耍: "Jouer",
  忽: "soudainement",
  听: "écouter",
  响: "anneau",
  半: "Moitié",
  丫: "Toi",
  边: "côté",
  岸: "rive",
  精: "Raffiné",
  唬: "idiot",
  跑: "courir",
  躲: "cacher",
  少: "peu",
  美: "beau",
  落: "automne",
  收: "recevoir",
  雾: "brouillard",
  抖: "secouer",
  堆: "tas",
  前: "avant",
  们: "Nous",
  众: "Tous",
  只: "Seulement",
  独: "seul",
  立: "rester",
  平: "plat",
  阳: "Positif",
  之: "De",
  地: "atterrir",
  叩: "frappe",
  问: "demander",
  故: "Donc",
  应: "répondre",
  事: "chose",
  遍: "partout",
  称: "dire",
  谢: "Merci",
  毕: "complet",
  夺: "Prendre",
  争: "Combattre",
  扯: "tirer",
  扳: "tirer",
  吆: "Ying",
  喝: "boire",
  日: "jour",
  次: "De premier ordre",
  依: "selon",
  旧: "vieux",
  排: "Rangée",
  营: "camp",
  会: "réunion",
  聚: "Rassembler",
  群: "groupe",
  计: "compter",
  四: "Quatre",
  万: "Dix mille",
  余: "Rester",
  早: "matin",
  满: "Complet",
  怪: "Étrange",
  兽: "bête",
  是: "Oui",
  些: "quelques",
  狼: "Loup",
  虫: "insecte",
  虎: "Tigre",
  豹: "Léopard",
  麂: "muntjac",
  獐: "chevreuil",
  狐: "renard",
  理: "raison",
  獾: "blaireau",
  貉: "Raton laveur",
  狮: "lion",
  象: "éléphant",
  狻: "小",
  猊: "lion",
  猩: "singe",
  熊: "Ours",
  鹿: "cerf",
  野: "sauvage",
  豕: "porc",
  牛: "bœuf",
  羚: "antilope",
  羊: "mouton",
  青: "vert",
  兕: "可",
  狡: "rusé",
  神: "Dieu",
  獒: "mastiff",
  各: "chaque",
  样: "Échantillon",
  妖: "Démon",
  共: "commun",
  十: "dix",
  参: "Ginseng",
  拜: "au revoir",
  为: "pour",
  尊: "Honneur",
  每: "Chaque",
  年: "Année",
  献: "offre",
  贡: "hommage",
  点: "indiquer",
  卯: "南",
  也: "aussi",
  随: "Avec",
  班: "classe",
  操: "Prise",
  演: "jouer",
  节: "Festival",
  征: "Confirmation",
  粮: "grain",
  齐: "ensemble",
  整: "tous",
  座: "siège",
  造: "faire",
  似: "comme",
  铁: "fer",
  桶: "seau",
  金: "or",
  城: "ville",
  路: "route",
  又: "encore",
  进: "Entrer",
  鼓: "tambour",
  彩: "couleur",
  旗: "drapeau",
  盔: "casque",
  甲: "D'abord",
  纷: "Beaucoup",
  攘: "jeter dans la confusion",
  逐: "Par",
  家: "Maison",
  习: "habitude",
  舞: "danse",
  兴: "prospérer",
  师: "division",
};

const tianwen_translation_map_en = {
  风起处: "Where the wind blows",
  惊散了那傲来国君王: "The king of Aolai was dispersed",
  三街六市: "Three Streets and Six Cities",
  都慌得关门闭户: "Everyone is so panicked that they close their doors",
  无人敢走: "No one dares to leave",
  悟空才按下云头: "Wukong pressed the cloud head",
  径闯入朝门里: "Break into the door",
  直寻到兵器馆武库中: "Find it straight into the Armory Arsenal",
  打开门扇: "Open the door",
  看时: "When watching",
  那里面无数器械: "There are countless equipment inside",
  刀枪剑戟斧钺毛镰鞭钯挝简弓弩叉矛:
    "Swords, spears, swords, halberds, axes, hairs, sickles, palladiums, simple bows, crossbows, forks, spears",
  件件俱备: "All items are ready",
  一见甚喜道: "He said very happy at first sight",
  我一人能拿几何: "How many can I get by myself",
  还使个分身法搬将去罢: "I'll use a clone technique to move it",
  好猴王: "Good Monkey King",
  即拔一把毫毛: "Pull out a handful of hairs",
  入口嚼烂: "Chewed in the mouth",
  喷将出去: "Spray out",
  念动咒语: "Recite the mantra",
  叫声: "Crying",
  变: "Change",
  变做千百个小猴: "Turn into thousands of little monkeys",
  都乱搬乱抢: "All move and grab",
  有力的拿五七件: "Take five or seven pieces with force",
  力小的拿三二件: "Take three or two pieces if you have less strength",
  尽数搬个罄净: "All moved out",
  径踏云头: "Step on the cloud head",
  弄个摄法: "Have a way of shooting",
  唤转狂风: "Call the wind",
  带领小猴: "Lead the little monkey",
  俱回本处: "All return to the capital",
  却说那花果山大小猴儿: "But the monkeys of Huaguo Mountain",
  正在那洞门外顽耍: "Playing hard outside the cave door",
  忽听得风声响处: "Suddenly I heard the sound of the wind",
  见半空中: "See in the air",
  丫丫叉叉: "Yaya fork",
  无边无岸的猴精: "The boundless monkey spirit",
  唬得都乱跑乱躲: "It's so frightening that I run around and hide",
  少时: "A few times",
  美猴王按落云头: "Monkey King presses cloud head",
  收了云雾: "Received the clouds",
  将身一抖: "Shake your body",
  收了毫毛: "Received hair",
  将兵器乱堆在山前: "Pile weapons in front of the mountain",
  叫道: "Calling",
  小的们: "The young men",
  都来领兵器: "All come to get weapons",
  众猴看时: "When the monkeys are watching",
  只见悟空独立在平阳之地: "I saw Wukong alone in Pingyang",
  俱跑来叩头问故: "All came to kowtow and ask why",
  悟空将前使狂风: "Wukong will make the wind in front of him",
  搬兵器: "Weapons",
  一应事说了一遍: "Said it all",
  众猴称谢毕: "The monkeys thanked",
  都去抢刀夺剑: "Everyone goes to grab the sword",
  挝斧争枪: "Axe and gun",
  扯弓扳弩: "Pull the bow and pull the crossbow",
  吆吆喝喝: "Hear",
  耍了一日: "Have fun for a day",
  次日: "The next day",
  依旧排营: "Still arranged",
  悟空会聚群猴: "Wukong gathers monkeys",
  计有四万七千余口: "There are more than 47,000",
  早惊动满山怪兽: "Already alarmed monsters all over the mountain",
  都是些狼虫虎豹麂獐狐理獾貉狮象狻猊猩猩熊鹿野豕山牛羚羊青兕狡儿神獒:
    "All are wolf, insect, tiger, leopard, deer, deer, fox, badger, raccoon, lion, elephant, orangutan, bear, deer, wild pig, cow, wild goat, green rhino, cunning, divine mastiff",
  各样妖王: "All kinds of demon kings",
  共有七十二洞: "There are 72 holes in total",
  都来参拜猴王为尊: "Everyone comes to worship the Monkey King as respect",
  每年献贡: "Contribute tribute every year",
  四时点卯: "Four time points",
  也有随班操演的: "There are also class-based performances",
  也有随节征粮的: "There are also food collections",
  齐齐整整: "Totally neat",
  把一座花果山造得似铁桶金城:
    "Making a flower and fruit mountain like an iron barrel and a golden city",
  各路妖王: "All demon kings",
  又有进金鼓: "There is another golden drum",
  进彩旗: "Enter the Colorful Flag",
  进盔甲的: "Into the armor",
  纷纷攘攘: "Busy",
  日逐家习舞兴师: "Dance and development",
};

const tianwen_translation_map_de = {
  风起处: "Wo der Wind weht",
  惊散了那傲来国君王: "Der König von Aolai wurde verteilt",
  三街六市: "Drei Straßen und sechs Städte",
  都慌得关门闭户: "Jeder ist so in Panik, dass sie ihre Türen schließen",
  无人敢走: "Niemand wagt es zu gehen",
  悟空才按下云头: "Wukong drückte den Wolkenkopf",
  径闯入朝门里: "In die Tür einbrechen",
  直寻到兵器馆武库中: "Finden Sie es direkt in das Armory Arsenal",
  打开门扇: "Öffne die Tür",
  看时: "Beim Beobachten",
  那里面无数器械: "Es gibt unzählige Geräte im Inneren",
  刀枪剑戟斧钺毛镰鞭钯挝简弓弩叉矛:
    "Schwerter, Speere, Schwerter, Hellebarde, Äxte, Haare, Sicheln, Palladien, einfache Bögen, Armbrüste, Gabeln, Speere",
  件件俱备: "Alle Gegenstände sind fertig",
  一见甚喜道: "Er sagte auf den ersten Blick sehr glücklich",
  我一人能拿几何: "Wie viele kann ich alleine bekommen?",
  还使个分身法搬将去罢:
    "Ich werde eine Klonentechnik verwenden, um sie zu bewegen",
  好猴王: "Guter Affenkönig",
  即拔一把毫毛: "Ziehen Sie eine Handvoll Haare heraus",
  入口嚼烂: "Im Mund gekaut",
  喷将出去: "Aussprühen",
  念动咒语: "Das Mantra rezitieren",
  叫声: "Weinen",
  变: "Ändern",
  变做千百个小猴: "Verwandeln Sie sich in Tausende von kleinen Affen",
  都乱搬乱抢: "Alle bewegen sich und greifen",
  有力的拿五七件: "Nehmen Sie fünf oder sieben Stücke mit Kraft",
  力小的拿三二件:
    "Nehmen Sie drei oder zwei Teile, wenn Sie weniger Kraft haben",
  尽数搬个罄净: "Alle zogen aus",
  径踏云头: "Treten Sie auf den Wolkenkopf",
  弄个摄法: "Schießen",
  唤转狂风: "Rufen Sie den Wind an",
  带领小猴: "Führe den kleinen Affen",
  俱回本处: "Alle Rückkehr in die Hauptstadt",
  却说那花果山大小猴儿: "Aber die Affen des Huaguo -Berges",
  正在那洞门外顽耍: "Hart vor der Höhlentür spielen",
  忽听得风声响处: "Plötzlich hörte ich das Geräusch des Windes",
  见半空中: "In der Luft sehen",
  丫丫叉叉: "Yaya Fork",
  无边无岸的猴精: "Der grenzenlose Affengeist",
  唬得都乱跑乱躲:
    "Es ist so beängstigend, dass ich herumlief und mich verstecke",
  少时: "Ein paar Mal",
  美猴王按落云头: "Affenkönig drückt Wolkenkopf",
  收了云雾: "Erhielt die Wolken",
  将身一抖: "Schütteln Sie Ihren Körper",
  收了毫毛: "Haare erhalten",
  将兵器乱堆在山前: "Waffen vor dem Berg stapeln",
  叫道: "Berufung",
  小的们: "Die jungen Männer",
  都来领兵器: "Alle kommen, um Waffen zu bekommen",
  众猴看时: "Wenn die Affen zuschauen",
  只见悟空独立在平阳之地: "Ich sah Wukong allein in Pingyang",
  俱跑来叩头问故: "Alle kamen nach Kowtow und fragten warum",
  悟空将前使狂风: "Wukong wird den Wind vor ihm machen",
  搬兵器: "Waffen",
  一应事说了一遍: "Sagte alles",
  众猴称谢毕: "Die Affen dankten",
  都去抢刀夺剑: "Jeder geht, um sich das Schwert zu greifen",
  挝斧争枪: "Axt und Waffe",
  扯弓扳弩: "Ziehen Sie den Bug und ziehen Sie die Armbrust",
  吆吆喝喝: "Hören",
  耍了一日: "Viel Spaß für einen Tag",
  次日: "Am nächsten Tag",
  依旧排营: "Immer noch arrangiert",
  悟空会聚群猴: "Wukong sammelt Affen",
  计有四万七千余口: "Es gibt mehr als 47.000",
  早惊动满山怪兽: "Bereits alarmierte Monster auf dem ganzen Berg",
  都是些狼虫虎豹麂獐狐理獾貉狮象狻猊猩猩熊鹿野豕山牛羚羊青兕狡儿神獒:
    "Alle sind Wolf, Insekt, Tiger, Leoparden, Hirsche, Hirsche, Fuchs, Dachs, Waschbär, Löwe, Elefant, Orang -Utan, Bär, Hirsche, Wildes, Kuh, Wildziege, grünes Nashorn, List, göttlicher Mastiff",
  各样妖王: "Alle Arten von Dämonenkings",
  共有七十二洞: "Insgesamt gibt es 72 Löcher",
  都来参拜猴王为尊: "Jeder kommt, um den Affenkönig als Respekt anzubeten",
  每年献贡: "Tragen Sie jedes Jahr Tribut bei",
  四时点卯: "Vier Zeitpunkte",
  也有随班操演的: "Es gibt auch klassenbasierte Aufführungen",
  也有随节征粮的: "Es gibt auch Lebensmittelsammlungen",
  齐齐整整: "Total ordentlich",
  把一座花果山造得似铁桶金城:
    "Eine Blume und einen Fruchtberg machen wie ein Eisenfass und eine goldene Stadt",
  各路妖王: "Alle Dämonenkönige",
  又有进金鼓: "Es gibt noch eine goldene Trommel",
  进彩旗: "Geben Sie die farbenfrohe Flagge ein",
  进盔甲的: "In die Rüstung",
  纷纷攘攘: "Beschäftigt",
  日逐家习舞兴师: "Tanz und Entwicklung",
};

const tianwen_translation_map_fr = {
  风起处: "Où le vent souffle",
  惊散了那傲来国君王: "Le roi d'Aolai était dispersé",
  三街六市: "Trois rues et six villes",
  都慌得关门闭户:
    "Tout le monde est tellement paniqué qu'ils ferment leurs portes",
  无人敢走: "Personne n'ose partir",
  悟空才按下云头: "Wukong a appuyé sur la tête du nuage",
  径闯入朝门里: "Pénétrer dans la porte",
  直寻到兵器馆武库中: "Trouvez-le directement dans l'arsenal d'armurerie",
  打开门扇: "Ouvrir la porte",
  看时: "En regardant",
  那里面无数器械: "Il y a d'innombrables équipements à l'intérieur",
  刀枪剑戟斧钺毛镰鞭钯挝简弓弩叉矛:
    "Épées, lances, épées, halberdes, haches, poils, faucilles, palladiums, arcs simples, arbalètes, fourchettes, lances",
  件件俱备: "Tous les articles sont prêts",
  一见甚喜道: "Il a dit très heureux à première vue",
  我一人能拿几何: "Combien puis-je obtenir par moi-même",
  还使个分身法搬将去罢: "J'utiliserai une technique de clone pour le déplacer",
  好猴王: "Bon roi de singe",
  即拔一把毫毛: "Tirez une poignée de poils",
  入口嚼烂: "Mâché dans la bouche",
  喷将出去: "Jaillir",
  念动咒语: "Réciter le mantra",
  叫声: "Pleurs",
  变: "Changement",
  变做千百个小猴: "Se transformer en milliers de petits singes",
  都乱搬乱抢: "Tout bouge et saisir",
  有力的拿五七件: "Prendre cinq ou sept pièces avec force",
  力小的拿三二件: "Prenez trois ou deux pièces si vous avez moins de force",
  尽数搬个罄净: "Tout a déménagé",
  径踏云头: "Étape sur la tête de nuage",
  弄个摄法: "Avoir un moyen de tirer",
  唤转狂风: "Appeler le vent",
  带领小猴: "Conduire le petit singe",
  俱回本处: "Tous retournent à la capitale",
  却说那花果山大小猴儿: "Mais les singes de la montagne Huaguo",
  正在那洞门外顽耍: "Jouer dur devant la porte de la grotte",
  忽听得风声响处: "Soudain, j'ai entendu le bruit du vent",
  见半空中: "Voir dans les airs",
  丫丫叉叉: "Yaya Fork",
  无边无岸的猴精: "L'esprit de singe sans limites",
  唬得都乱跑乱躲: "C'est tellement effrayant que je cours et je me cache",
  少时: "Plusieurs fois",
  美猴王按落云头: "Monkey King presse la tête de nuage",
  收了云雾: "Reçu les nuages",
  将身一抖: "Secouez votre corps",
  收了毫毛: "Reçu les cheveux",
  将兵器乱堆在山前: "Pile des armes devant la montagne",
  叫道: "Appel",
  小的们: "Les jeunes hommes",
  都来领兵器: "Tous viennent pour obtenir des armes",
  众猴看时: "",
  只见悟空独立在平阳之地: "J'ai vu Wukong seul à Pingyang",
  俱跑来叩头问故: "Tous sont venus à Kowtow et ont demandé pourquoi",
  悟空将前使狂风: "Wukong fera le vent devant lui",
  搬兵器: "Armes",
  一应事说了一遍: "Dit tout",
  众猴称谢毕: "Les singes ont remercié",
  都去抢刀夺剑: "Tout le monde va attraper l'épée",
  挝斧争枪: "Hache et pistolet",
  扯弓扳弩: "Tirez l'arc et tirez l'arbalète",
  吆吆喝喝: "Entendre",
  耍了一日: "Amusez-vous pendant une journée",
  次日: "Le lendemain",
  依旧排营: "Toujours arrangé",
  悟空会聚群猴: "Wukong rassemble des singes",
  计有四万七千余口: "Il y en a plus de 47 000",
  早惊动满山怪兽: "Des monstres déjà alarmés dans toute la montagne",
  都是些狼虫虎豹麂獐狐理獾貉狮象狻猊猩猩熊鹿野豕山牛羚羊青兕狡儿神獒:
    "Tous sont loup, insecte, tigre, léopard, cerf, cerf, renard, blaireau, raton laveur, lion, éléphant, orang-ou ours, cerf, cochon sauvage, vache, chèvre sauvage, rhinocéros vert, rusé, mastiff divin",
  各样妖王: "Toutes sortes de rois de démon",
  共有七十二洞: "Il y a 72 trous au total",
  都来参拜猴王为尊: "Tout le monde vient adorer le roi singe comme respect",
  每年献贡: "Contribuer à hommage chaque année",
  四时点卯: "Quatre points temporels",
  也有随班操演的: "Il y a aussi des performances basées sur les classes",
  也有随节征粮的: "Il y a aussi des collections alimentaires",
  齐齐整整: "Totalement soigné",
  把一座花果山造得似铁桶金城:
    "Faire une montagne de fleurs et de fruits comme un baril de fer et une ville dorée",
  各路妖王: "Tous les rois de démon",
  又有进金鼓: "Il y a un autre tambour doré",
  进彩旗: "Entrez le drapeau coloré",
  进盔甲的: "Dans l'armure",
  纷纷攘攘: "Occupé",
  日逐家习舞兴师: "Danse et développement",
};





const synth = window.speechSynthesis;
let utterance = null;

// 状态跟踪
const charStates = {};

// 页面加载完成后初始化
document.addEventListener("DOMContentLoaded", function () {
  renderPoem();
});

// 渲染诗歌
function renderPoem() {
  const poemContainer = document.getElementById("poemContainer");
  const lines = poemText.split("\n");

  lines.forEach((line) => {
    const lineDiv = document.createElement("div");
    lineDiv.className = "poem-line";

    // 处理每个字符
    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      // 跳过空格
      if (char.trim() === "") {
        const spaceSpan = document.createElement("span");
        spaceSpan.textContent = " ";
        lineDiv.appendChild(spaceSpan);
        continue;
      }

      // 创建字符容器
      const charContainer = document.createElement("div");
      charContainer.className = "char-container";

      // 创建字符显示
      const charSpan = document.createElement("span");
      charSpan.className = "char";
      charSpan.textContent = char;

      // 创建拼音显示
      const pinyinSpan = document.createElement("span");
      pinyinSpan.className = "pinyin";

      // 创建翻译显示
      const transSpan = document.createElement("span");
      transSpan.className = "translation";

      // 添加到容器
      charContainer.appendChild(pinyinSpan);
      charContainer.appendChild(charSpan);
      charContainer.appendChild(transSpan);

      // 添加点击事件
      charContainer.addEventListener("click", () =>
        handleCharClick(char, pinyinSpan, transSpan)
      );

      // 添加到行
      lineDiv.appendChild(charContainer);
    }

    // 添加行控制按钮
    const controlsDiv = document.createElement("div");
    controlsDiv.className = "line-controls";

    const readBtn = document.createElement("button");
    readBtn.textContent = "朗读";
    readBtn.addEventListener("click", () => readLine(line));

    const transBtn = document.createElement("button");
    transBtn.textContent = "翻译";
    transBtn.addEventListener("click", () => showLineTranslation(line));

    controlsDiv.appendChild(readBtn);
    controlsDiv.appendChild(transBtn);
    lineDiv.appendChild(controlsDiv);

    // 添加到容器
    poemContainer.appendChild(lineDiv);
  });
}

// 处理字符点击
function handleCharClick(char, pinyinSpan, transSpan) {
  const charId = `${char}-${pinyinSpan.id}`; // 创建唯一标识

  // 初始化状态
  if (!charStates[charId]) {
    charStates[charId] = 0;
  }

  // 更新状态
  charStates[charId]++;
  if (charStates[charId] > 3) {
    charStates[charId] = 1;
  }

  // 根据状态执行操作
  switch (charStates[charId]) {
    case 1: // 朗读字符
      readChar(char);
      updateStatus(`朗读字符: ${char}`);
      break;
    case 2: // 显示拼音
      showPinyin(char, pinyinSpan);
      updateStatus(`显示拼音: ${char}`);
      break;
    case 3: // 显示翻译
      showTranslation(char, transSpan);
      updateStatus(`显示翻译: ${char}`);
      break;
  }
}

// 显示拼音
function showPinyin(char, pinyinSpan) {
  // 这里应该调用拼音库，简化处理

  const py = pinyinMap[char] || "?";
  pinyinSpan.textContent = py;
  pinyinSpan.style.display = "block";

  // 3秒后自动隐藏
  setTimeout(() => {
    pinyinSpan.style.display = "none";
    // 重置状态以便下次点击
    const charId = `${char}-${pinyinSpan.id}`;
    charStates[charId] = 0;
  }, 8000);
}

// 朗读字符
function readChar(char) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(char);
  utterance.lang = "zh-CN";
  utterance.rate = 0.7; // 设置为正常速度的70%
  synth.speak(utterance);
}

// 显示翻译
function showTranslation(char, transSpan) {
  const lang = document.getElementById("languageSelect").value;

  const translationCard = document.getElementById("translationCard");

  const translateMap = {
    de: translations_de[char] || "Keine Übersetzung",
    fr: translations_fr[char] || "Pas de traduction",
    en: translations_en[char] || "No translation",
  };
  const translate = translateMap[lang];
  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">汉字：</div>
    <div class="info-content">${char}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translate}</div>
  </div>
`;

  translationCard.style.display = "block";

  const charId = `${char}-${transSpan.id}`;
  charStates[charId] = 0;
}

function closeTranslationCard() {
  const translationCard = document.getElementById("translationCard");
  translationCard.style.display = "none";
}

// 朗读整行
function readLine(line) {
  if (synth.speaking) {
    synth.cancel();
  }

  utterance = new SpeechSynthesisUtterance(line);
  utterance.lang = "zh-CN";
  utterance.rate = 0.6; // 设置为正常速度的60%，更慢一些
  synth.speak(utterance);

  updateStatus(`朗读: ${line}`);
}

function showLineTranslation(line) {
  const lang = document.getElementById("languageSelect").value;
  const translatedMap = {
    de: tianwen_translation_map_de,
    fr: tianwen_translation_map_fr,
    en: tianwen_translation_map_en,
  };
  const translatedLine =
    translatedMap[lang]?.[line] || "（keine Übersetzung gefunden）";
  const translationCard = document.getElementById("translationCard");

  translationCard.innerHTML = `
  <div class="card-header">
    <button class="close-btn" onclick="closeTranslationCard()">×</button>
  </div>
  <div class="info-block">
    <div class="info-label">原文：</div>
    <div class="info-content">${line}</div>
    <div class="info-label">翻译：</div>
    <div class="info-content">${translatedLine}</div>
  </div>
`;

  translationCard.style.display = "block";

  updateStatus(`显示翻译: ${line.substring(0, 15)}...`);
}

// 更新状态栏
function updateStatus(message) {
  document.getElementById("statusBar").textContent = message;
}
